### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Heitortadeu** [opentibiabr/otservbr-global#1005]
**_--REPORTS DATA 09/04/2020_**

**Bugs encontrados:**

- [x] 1. escada n 8599 com bug no mapa
- [x] 2. quest arena - bug das portas https://github.com/opentibiabr/otservbr-global/issues/913
- [x] 3. buraco sem saida area free arrumar position: 32652 32120 11:1
- [x] 4. arrumado a porta de pedra que não abre em edron position 33177 31842 8:1
- [x] 5. arrumar porta que vai pros troll em carlin 32408 31785 7:1
- [x] 6. arrumar, que não funfou, portal que vai para boss 32915 31637 14:1   vai para: 32902 31630 14:1
- [x] 7. monstro no lugar errado Position: 33324, 32333, 13:1
- [x] 8. portal sem saida em ank 33205 32531 8:1
- [x] 9. portal do Deathbine em port hope bugado (32722 32762 8:1) ele vai para 32714 32735 8:1
- [x] 10. portas golden boots abrindo 33273 32440 12:1
- [x] 11. Position: 33562, 31775, 13: - bug portal
- [x] 12. tiles com no-logout (amarelo) positions 32785 32328 6 :1
- [x] 13. tiles com no-logout na ponte (amarelo) 32380 32179 7:1
- [x] 14. portal bugado 33167 31977 8:1

**_--REPORTS DATA 10/04/2020_**

**Bugs encontrados:**
- [x] 15. NPC Corym Ratter, que libera acesso a mission da Hidden Threats Quest, não tem script alguma, ou seja, não há como ir ao acesso, conforme video, bem como a quest está prejudicada nos demais pontos: https://www.youtube.com/watch?v=Y5G-yDI9OhM
- [x] 16. na position 33313, 32647, 6:1, era para ter o npc que trata da mission para o Boss Scarlett Etzel

**_--REPORTS DATA 11/04/2020_**

**Bugs encontrados:**
- [x] 17. oramond quest está bugada, fora entregado os pontos não surtiu efeito, e também não há o npc Doubleday's Tasks. https://www.tibiawiki.com.br/wiki/Oramond_Quest

**_--REPORTS DATA 15/04/2020_**

**Bugs encontrados:**
- [x] 18. NPC Maeryn em Grimvale, ele não inicia a missão da quest The Curse Spreads Quest. Pode ser conferido em https://www.tibiaroyal.com/br/guide/quest/272/the-curse-spreads-quest/spoiler
- [x] 19. loot do grimleech e vexclaw está muito hard, praticamente não cai os itens, bem como esses dois bixos passam por cima de energy, mas no tibia eles não passam.
- [x] 20. boss darkfang portal 33055 31910 9:1 vai para 33055 31889 9 e volta para 33054 31912 9:1
- [x] 21. boss sharpclaw portal 33128 31971 9:1 vai para 33121 31997 9 e volta para 33129 31972 9 :1
- [x] 22. boss black vixen portal 33167 31977 8:1 que vai para 33181 32012 8 e volta para 33167 31979 8:1
- [x] 23. boss obujos portal 33438 31248 11:1 tem que ir para 33420 31255 11:1 - https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/obujos.jpg.a77f08e72799ccd1b30c4095569e87de.jpg
- [x] 24. boss jaul portal 33558 31282 11 vai para 33544 31262 11 :1https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/Jaul.jpg.8f00a8357d01dc6dfe201b7dfbcc0a9e.jpg
- [x] 25. boss Tanjis portal 33648 31261 11 vai para 33640 31233 11:1https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/Tanjis.jpg.b14cb5b238bcabb409740d9a11a483d8.jpg
- [x] 26. Na position 33313, 32647, 6:1 portal para Boss Scarlett Etzel ir para position 33386 32628 7:1 e portal voltando para 33312 32647 6:1
33395 32662 6:1 saida da sala do boss da scarlet
33396 32659 6:1 entrada para sala do boss scarlet

**_--REPORTS DATA 16/04/2020_**

**Bugs encontrados:**
- [x] 27. falta adicionar esse tipo de portas id: 35608

**_--REPORTS DATA 17/04/2020_**

**Bugs encontrados:**
- [x] 28. alanvanca levou apenas um player Position: 33917, 31626, 8:1 - e position: 33918, 31646, 8:1 não tem o boss Urmahlullu the weakened
- [x] 29. npc Esrik.lua vendendo apenas 1 charge exercise weapons (o certo é 500 charges).
- [x] 30. npc Esrik.lua vendendo apenas 1 charge do stone skin amulet (o certo é 5 charges).
- [x] 31. Retro Summoner outfit GAMESTORE está OFFER_TYPE_OUTFIT_ADDON (não pode ter o ADDON).
- [x] 32. na position: 32208, 32296, 6:1, a plaquinha era para dar use e receber informações do server, se nasceu yasir, boss, conforme https://www.tibiawiki.com.br/wiki/World_Board

**_--REPORTS DATA 18/04/2020_**

**Bugs encontrados:**
- 33 Os monsters Boss, por exemplo, scarlet, bloodback, e outros em sua maioria, não estão deixando abrir o loot após matá-los.
- [x] 34. A The Secret Library Quest está bugada, não é possível passar da parte do livro, após ler o livro, era para aparecer a missão no quest log e passar para próxima etapa, contudo, voltando ao npc ele pede novamente pra ler o livro e não libera a missão seguinte. Spoiler: https://www.tibiawiki.com.br/wiki/The_Secret_Library_Quest
- [x] 35. colocar no andar da quest firewalker boots area nologout, pois tem players conseguindo, pelo lado direito, acessar o lado esquerdo e pegando a quest.
- [x] 36. boss Lady Tenebris, modificar a script, a fim de colocar a cada 15 segundos a magia que o boss puxa os players para perto, sendo a linha correta: attack name="death" interval="**15000**" chance="13" length="8" spread="0" min="-1200" max="-1500"

**_--REPORTS DATA 19/04/2020_**

**Bugs encontrados:**
- [x] 37. monster Stonerefiner não está dropando nada. Spoiler: https://www.tibiawiki.com.br/wiki/Stonerefiner
- [x] 38. npc A Sweaty Cyclops, mesmo com a quest full necessária, não está trocando iron ore por Gear Wheel, nessa parte ele está mudo e não responde.
- [x] 39. na position: 32934, 32026, 6:1 tem a rampa que desce mas não sobe.
- [x] 40. Lion's Rock Quest está bugada, na parte final de por as gemas nos 4 pontos e n aparece nem no quest log, bem como quando passar por cima de alguns sqm não aparece as mensagens, foi aberto fonte da recompensa, mas não saiu nada. Spoiler: https://www.tibiawiki.com.br/wiki/Lion%27s_Rock_Quest
- [x] 41. não há respawn de Water Buffalo no mapa. Spoiler: https://www.tibiawiki.com.br/wiki/Water_Buffalo

**_--REPORTS DATA 20/04/2020_**

**Bugs encontrados:**
- [x] 42. portal boss Black Vixen bugado, position: 33442, 32051, 9. Spoiler: https://www.tibiawiki.com.br/wiki/Black_Vixen
- [x] 43. portal boss Shadowpelt bugado, position: 33402, 32097, 9: Spoiler: https://www.tibiawiki.com.br/wiki/Shadowpelt
- [x] 44. portal position: 33429, 32083, 9 bugado, pois vai para portal position: 33064, 31977, 9 e vice versa (na hora de arrumar, colocar um sqm a frente tanto um quanto o outra pra não bugar, pois as positions é exatamente onde estão os portais).
- [x] 45. não é possível fazer Enchanted Werewolf Amulet. Spoiler: https://www.tibiawiki.com.br/wiki/Enchanted_Werewolf_Amulet

**_--REPORTS DATA 21/04/2020_**

**Bugs encontrados:**
- [x] 46. não a possibilidade de conseguir Gooey Mass na The Hive após dar use em um Insectoid Cell. Spoiler: https://www.tibiawiki.com.br/wiki/Gooey_Mass

**_--REPORTS DATA 22/04/2020_**

**Bugs encontrados:**
- 47 O Achievements não estão funcionando todos, exemplos de alguns: Após entrar pela primeira vez no covil dos Deathlings, você ganhará o Achievement "Spectulation".
"Do Not Disturb" Obtido fechando janelas 100 vezes.
 "Number of the beast" Obtido se você conseguir tirar o número "6" três vezes seguidas jogando um Dado.
Spoiler: https://www.tibiawiki.com.br/wiki/Achievements
- [x] 48. Não encontrei no projeto o evento que há no tíbia, A Piece of Cake. Spoiler: https://www.tibiawiki.com.br/wiki/A_Piece_of_Cake
- [x] 49. Não há como fazer a quest Sam's Old Backpack Quest, pois falta invasão do orc_sambackpack que dropa Old and Used Backpack. https://www.tibiaroyal.com/br/guide/quest/244/sams-old-backpack-quest/spoiler
- [x] 50. Não tem boss do Werewolf. Spoiler: https://www.tibiawiki.com.br/wiki/Werewolf

- [x] 51. retirado a pedra da POI, pois script bugou (a partir da terceira alavanca, todas travadas) 32851 32333 12:1
- [x] 52. retirada a parede da tocha em carlin, para quest cults, já que não ta funfando script 32396 31806 8:1
- [x] 53. Bug da quest blue legs, após matar o boss não está sendo possível abrir a porta da quest.,

**_--REPORTS DATA 25/04/2020_**

**Comment by travisani** [comment]
Realmente, #995  bugou algumas portas.

**Comment by dudantas** [comment]
> Realmente, #995 bugou algumas portas.

Quais? Manda as pos.

**Comment by travisani** [comment]
Testa estas:
32974, 32037, 5
33273, 32440, 12

**Comment by travisani** [comment]
Bug House 33298, 31998, 8

**Comment by dudantas** [comment]
- 1 resolvido

- 2 @Heitortadeu testa esse commit: https://github.com/opentibiabr/otservbr-global/pull/983 Corrigi as doors da arena nele, você deve tá com a base desatualizada.
(lembra de pegar o mapa tbm)

- 3 https://forums.tibiabr.com/threads/408915-Noob-(Eu)-preso-na-cave-da-Desert-Quest (cip troll, chamam carinhosamente de buraco da morte)

- 4 a 8 resolvidos

- 9 não está bugado, você precisa pegar a task de matar 150 carniphilas com o npc Grizzly Adams, matar as 150 carniphilas e depois voltar ao npc, falar report, aí vai poder acessar o TP.

- 10 resolvido

- 11 faz parte de alguma quest. Configurei o tp na position: 33555, 31632, 13 pra levar pra saída, foi o único TP que eu achei as destinations. Vou ver aqui como posso ver que quest é essa pra gente colocar ela na lista de desenvolvimento. (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 12 a 13 resolvidos

- 14 faz parte da The Curse Spreads Quest, ainda não foi desenvolvida, vou colocar na lista de quests que precisam ser desenvolvidas. (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 15 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 16 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 17 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 18, (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 19 corrigido não passar por energy, já o loot é complicado pois não há estatísticas de loot nos fóruns, daí não dá pra gente saber como é a chance real deles no global.
![image](https://user-images.githubusercontent.com/8551443/79722621-c0e54400-82ba-11ea-87b9-3a775b15b827.png)

- 20 a 22 movidos para o https://github.com/opentibiabr/otservbr-global/issues/726

- 23 a 25 fazem parte da deeplings world change: https://www.tibiawiki.com.br/wiki/Deeplings_World_Change
Ainda não foi desenvolvida (movido para https://github.com/opentibiabr/otservbr-global/issues/726)
No mapa eu corrigi os tps segundo suas informações aqui do issue, isso deve possibilitar a entrada até que desenvolvamos a quest completa. (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 26 não está desenvolvido, quest: https://www.tibiawiki.com.br/wiki/Grave_Danger_Quest
(movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 27 resolvido

- 28 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 29 resolvido

- 30 inconfirmado pois o Esrik não vende SSA.

- 31 inconfirmado, na base está sem o "_ADDON"
![image](https://user-images.githubusercontent.com/8551443/80231834-5457a580-862a-11ea-8fe9-f5341e74ce0e.png)

- 32 já tem um issue sobre isso https://github.com/opentibiabr/otservbr-global/issues/814

- 33 precisa de mais informações, desativei a tasklist dele, depois faz um issue sobre ele

- 34 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 35 resolvido

- 36 resolvido

- 37 estranho, pois olhei o script e parece tá normal, mas eu corrigi o loot dele (as chances)
![image](https://user-images.githubusercontent.com/8551443/79722328-3997d080-82ba-11ea-8bb5-c0309839d0c7.png)

- 38 testado e funcionando
![image](https://user-images.githubusercontent.com/8551443/80239456-a8688700-8636-11ea-8aa5-98d3fe8afccb.png)
![image](https://user-images.githubusercontent.com/8551443/80239494-b7e7d000-8636-11ea-9622-3e23e0ed9d10.png)

- 39 preciso testar como funciona essa escada no global, mas alterei umas coisas q vi errado nela

- 40 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 41 resolvido

- 42 a 43 (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 44 resolvido

- 45 resolvido

- 46 resolvido 

- 47 cria um novo issue com isso

- 48 - (movido para https://github.com/opentibiabr/otservbr-global/issues/726)

- 49 resolvido

- 50 sim tem, é na Position(32992, 31443, 7), só é liberado após fazer a task dos werewolfs da killing in the name of...

- 51 testei e funcionou normalmente, ou seja sem bug

- 52 resolvido

- 53 resolvido

**Comment by dudantas** [comment]
> 33298, 31998, 8:1

Qual o problema nessas houses?

**Comment by travisani** [comment]
Erros de marcação da house tile.

**Comment by dudantas** [comment]
> Erros de marcação da house tile.

Certo, já arrumei. Hoje ou amanhã eu subo o mapa com todas as correções reportadas nos últimos meses.

**Comment by htc16** [comment]
> * 2 @Heitortadeu testa esse commit: opentibiabr/otservbr-global#983 Corrigi as doors da arena nele, você deve tá com a base desatualizada.
>   (lembra de pegar o mapa tbm)
> * 3 https://forums.tibiabr.com/threads/408915-Noob-(Eu)-preso-na-cave-da-Desert-Quest (cip troll, chamam carinhosamente de buraco da morte)

Show Du!

**Comment by dudantas** [comment]
> > * 2 @Heitortadeu testa esse commit: opentibiabr/otservbr-global#983 Corrigi as doors da arena nele, você deve tá com a base desatualizada.
> >   (lembra de pegar o mapa tbm)
> > * 3 https://forums.tibiabr.com/threads/408915-Noob-(Eu)-preso-na-cave-da-Desert-Quest (cip troll, chamam carinhosamente de buraco da morte)
> 
> Show Du!

Vou ir atualizando esse meu primeiro comentário citando as correções.
Não entendi o das escadas, como assim? o n° 1

**Comment by htc16** [comment]
> > > * 2 @Heitortadeu testa esse commit: opentibiabr/otservbr-global#983 Corrigi as doors da arena nele, você deve tá com a base desatualizada.
> > >   (lembra de pegar o mapa tbm)
> > > * 3 https://forums.tibiabr.com/threads/408915-Noob-(Eu)-preso-na-cave-da-Desert-Quest (cip troll, chamam carinhosamente de buraco da morte)
> > 
> > 
> > Show Du!
> 
> Vou ir atualizando esse meu primeiro comentário citando as correções.
> Não entendi o das escadas, como assim? o n° 1

Aquela tipo de escada não é possível subir, no mapa tem 3 lugares, um na área free, e aí a galera cai no buraco e não sai por causa daquele tipo de escada.

**Comment by dudantas** [comment]
Outra coisa, eu coloquei um :1 depois das suas positions, é que assim quando eu copio ela e colo na janela de pos do rme já cola tudo certinho, n preciso copiar de um em um kkkkkkk
Ah, eu vou ir marcando como resolvido nos que eu já mexi ok ? Dai, quando eu subir o mapa eu peço q vc baixe e teste blz ?

**Comment by dudantas** [comment]
> > > > * 2 @Heitortadeu testa esse commit: opentibiabr/otservbr-global#983 Corrigi as doors da arena nele, você deve tá com a base desatualizada.
> > > >   (lembra de pegar o mapa tbm)
> > > > * 3 https://forums.tibiabr.com/threads/408915-Noob-(Eu)-preso-na-cave-da-Desert-Quest (cip troll, chamam carinhosamente de buraco da morte)
> > > 
> > > 
> > > Show Du!
> > 
> > 
> > Vou ir atualizando esse meu primeiro comentário citando as correções.
> > Não entendi o das escadas, como assim? o n° 1
> 
> Aquela tipo de escada não é possível subir, no mapa tem 3 lugares, um na área free, e aí a galera cai no buraco e não sai por causa daquele tipo de escada.

aaaaaaaaaaaa entendi kkkkkkkk 
colocaram a escada errada no mapa né ?

**Comment by dudantas** [comment]
@Heitortadeu atualizei meu comentário, dá uma olhada lá.

**Comment by htc16** [comment]
> 
> 
>     * 1 resolvido
> 
>     * 2 @Heitortadeu testa esse commit: opentibiabr/otservbr-global#983 Corrigi as doors da arena nele, você deve tá com a base desatualizada.
>       (lembra de pegar o mapa tbm)
> 
>     * 3 https://forums.tibiabr.com/threads/408915-Noob-(Eu)-preso-na-cave-da-Desert-Quest (cip troll, chamam carinhosamente de buraco da morte)
> 
>     * 4 a 8 resolvidos
> 
>     * 9 preciso saber onde dá acesso ao teleport, sei que é na task do grizzly adams, depois que mata as carniphilas, mas preciso saber a storage que ganha quando mata todas elas. Pode verificar pra mim? Que daí eu faço um acesso ao teleport quando ganhar essa storage.
> 
>     * 10 resolvido
> 
>     * 11 faz parte de alguma quest. Configurei o tp na position: 33555, 31632, 13 pra levar pra saída, foi o único TP que eu achei as destinations. Vou ver aqui como posso ver que quest é essa pra gente colocar ela na lista de desenvolvimento.
> 
>     * 12 a 13 resolvidos
> 
>     * 14 faz parte da The Curse Spreads Quest, ainda não foi desenvolvida, vou colocar na lista de quests que precisam ser desenvolvidas.
> 
>     * 15 movido para o opentibiabr/otservbr-global#726
> 
>     * 16 sabe o nome do NPC? Eu procurei e não achei nada referente a um NPC ali.
> 
>     * 17 movido para o opentibiabr/otservbr-global#726
> 
>     * 18, mesma situação do n° 14, movido para o opentibiabr/otservbr-global#726
> 
>     * 19 corrigido não passar por energy, já o loot é complicado pois não há estatísticas de loot nos fóruns, daí não dá pra gente saber como é a chance real deles no global.
>       ![image](https://user-images.githubusercontent.com/8551443/79722621-c0e54400-82ba-11ea-87b9-3a775b15b827.png)
> 
>     * 20 a 22 movidos para o opentibiabr/otservbr-global#726
> 
>     * 23 a 25 fazem parte da deeplings world change: https://www.tibiawiki.com.br/wiki/Deeplings_World_Change
>       Ainda não foi desenvolvida, vou mandar para o opentibiabr/otservbr-global#726
>       No mapa eu corrigi os tps segundo suas informações aqui do issue, isso deve possibilitar a entrada até que desenvolvamos a quest completa.
> 
>     * 26 não está desenvolvido, quest: https://www.tibiawiki.com.br/wiki/Grave_Danger_Quest
>       Movi para o issue de quests também.
> 
>     * 27 resolvido
> 
>     * 28 quest não desenvolvida
> 
>     * 29 resolvido, 30 inconfirmado pois o Esrik não vende SSA.
> 
>     * 35 resolvido
> 
>     * 36 resolvido
> 
>     * 37 estranho, pois olhei o script e parece tá normal, mas eu corrigi o loot dele (as chances)
>       ![image](https://user-images.githubusercontent.com/8551443/79722328-3997d080-82ba-11ea-8bb5-c0309839d0c7.png)
> 
>     * 39 preciso testar como funciona essa escada no global, mas alterei umas coisas q vi errado nela
> 
> 
> Alguns issues eu não olhei a fundo pois são em scripts e não necessariamente no mapa, vou deixar pra corrigir depois, no momento to corrigindo só o que é de mapa.
> Bugs inconfirmados:
> 
>     * 2 Confirmado e corrigido
> 
>     * 3 Não parece estar bugado, usou o amuleto no corpo do boss? Olhei os scripts e parece estar td ok. https://www.tibiawiki.com.br/wiki/Koshei_The_Deathless_Quest#Enfrentando_o_Koshei_the_Deathless

 * 9 - NPC Grizzly Adams, conforme https://www.tibiawiki.com.br/wiki/Paw_and_Fur_-_Hunting_Elite_Quest e acredito que a linha que você está comentando é essa: if player:getStorageValue(Storage.KillingInTheNameOf.MissionTiquandasRevenge) == 1 then  -- Check if he has already started the task.

 * 11 - esse lugar, quando pessoal cai nesse lugar não estão encontrando a saída...

 * 16 - na verdade não é NPC, é o acesso para cobra bastion, veja como é a ida e volta de lá, tem que dar use tanto na ida quanto na volta acho que na corda: https://www.tibiaroyal.com/br/guide/quest/282/cobra-bastion/spoiler

**Comment by dudantas** [comment]
O 11 não é bug, é armadilha que a CIP deixou mesmo. Quem cair, se mata ou pede algum amigo para ropar.

**Comment by dudantas** [comment]
O 16 não está funcionando? Eu vi que tem action no item, vou verificar o script.

**Comment by htc16** [comment]
> O 16 não está funcionando? Eu vi que tem action no item, vou verificar o script.

Bom dia Man. 

16. Nem a ida nem a volta funciona apesar da Action.

**Comment by dudantas** [comment]
> > O 16 não está funcionando? Eu vi que tem action no item, vou verificar o script.
> 
> Bom dia Man.
> 
> 1. Nem a ida nem a volta funciona apesar da Action.

Bom dia mano, certo, deve estar sem o script, vou ver aqui.
