### ISSUE TITLE
NPC Kais/Nomad (Blessing) Ausentes

### ISSUE THREAD

**Issue by daanyx** [opentibiabr/otservbr-global#1025]
Os NPC's Kais/Nomad estão presentes na DataBase.
Mas não estão presentes no Game/Mapa.
Através do comando /goto não é possível encontrar
/goto kais
/goto Nomad(NPC)

Já o comando /n (funciona)
/n kais
/n nomad

**Comment by dudantas** [comment]
Thanks for the report. I'm already putting them on the map, so I must go up here.
