### ISSUE TITLE
Ferumbras Ascendant Storage (Lua script error)

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global#1032]
**Describe the bug**
Getting console errors (see screenshot) when using any of the Ferumbras Ascendant boss levers.

**To Reproduce**
1. Go to the plagirath boss room.
2. Change the lever of plagirath's room to uid 9526.
3. Use the lever.

**Expected behavior**
No console errors.

**Screenshots**
https://imgur.com/a/QPMbmW2

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
It seems that this problem is with alot of things, I however have only tested it on the bosses of the Ferumbras Ascendant Quest.

**Comment by dudantas** [comment]
@oualid6496 put the positions.
When making an issue, always place the positions. There is no way for us to know.

**Comment by dudantas** [comment]
Another thing, you can just throw the image right here on github, you don't need to put it externally. Like this:

![image](https://user-images.githubusercontent.com/8551443/79693044-d157d900-823e-11ea-9a7a-995fb0dcc268.png)

**Comment by gpedro** [comment]
confirmed.
https://github.com/opentibiabr/otservbr-global/blob/dda5ef7dd523f9828e43ada45509bc406e9d089d/data/actions/scripts/quests/ferumbras%20ascendant/plagirathLever.lua#L39

`PlagirathTimer` is available on Storages (Player), not GlobalStorages (Game)
https://github.com/opentibiabr/otservbr-global/blob/9d8048fcbd322bfef6b2570aceb960b21de89b1b/data/lib/core/storages.lua#L311-L321

https://github.com/opentibiabr/otservbr-global/blob/9d8048fcbd322bfef6b2570aceb960b21de89b1b/data/lib/core/storages.lua#L1468-L1502
