### ISSUE TITLE
Chest Heavy Old Tome

### ISSUE THREAD

**Issue by mvmgs** [opentibiabr/otservbr-global#1037]
Uma chest que contém no global e lhe dará o item **Heavy Old Tome**, não se encontra aqui.

**Coordenada: 32348, 32194, 9** (Thaís)

**Screenshot Tibia Global:**
![unknown](https://user-images.githubusercontent.com/8450356/79520128-4c957100-802c-11ea-9cbe-c6fecca20e97.png)

**Screenshot OTServBR:**
![unknown (1)](https://user-images.githubusercontent.com/8450356/79520162-65058b80-802c-11ea-96de-98de625e006f.png)

**Comment by travisani** [comment]
Correto.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/79738795-a370a400-82d3-11ea-9f9d-f719b669ce52.png)

Fixado no opentibiabr/otservbr-global#1059
