### ISSUE TITLE
Equiping Ammo Bug - Action Bars

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global#1039]
This one is very tricky:

When you equip arrows/bolts, give that some requirements are fulfilled, 100 of your ammo will be thrown to the ground, beneath you.

1. Create a Paladin with level 150+ or a GM/Admin for the following tests
2. Have 100 power bolts in your arrow slot, and in your backpack, in this exact order:
 - 99 infernal bolts, 74 infernal bolts, 15 diamond arrows and 100 diamond arrows
3. Put the infernal bolts and diamond arrows on your action bar, set to equip.
4. Switch to infernal bolts through action bar
5. A stack of 100 should have been placed at your feet
6. Now with the 100 power bolts still in your arrow slot, switch to diamond arrows, again, through action bar
7. 100 arrows should be laying beneath you, 1 by 1 (because their decay time will be different, for some reason lol)

![image](https://user-images.githubusercontent.com/36482994/79527850-fbdb4380-803e-11ea-8786-85aa179e6de0.png)
![image](https://user-images.githubusercontent.com/36482994/79527872-0990c900-803f-11ea-9025-fb27c3cf2ec3.png)
![image](https://user-images.githubusercontent.com/36482994/79527881-0eee1380-803f-11ea-8800-49ae305aa4e5.png)
![image](https://user-images.githubusercontent.com/36482994/79527890-19101200-803f-11ea-8719-84aaa6d71ae5.png)
![image](https://user-images.githubusercontent.com/36482994/79527902-1f05f300-803f-11ea-9ec5-fa0f03ceac51.png)
![image](https://user-images.githubusercontent.com/36482994/79527915-24fbd400-803f-11ea-8a70-0cc02712b110.png)
![image](https://user-images.githubusercontent.com/36482994/79527949-347b1d00-803f-11ea-934c-259c1a8011a2.png)
![image](https://user-images.githubusercontent.com/36482994/79527980-41980c00-803f-11ea-8f9a-52023ad97dbd.png)
![image](https://user-images.githubusercontent.com/36482994/79527988-465cc000-803f-11ea-8f51-1b889e3046ca.png)
![image](https://user-images.githubusercontent.com/36482994/79528064-67bdac00-803f-11ea-9f8f-37d897232179.png)

The ammount of ammo does not matter, considering that you have more than 100 and the first stack of it is less than 100.

**Comment by gabz182** [comment]
it's that?

https://i.imgur.com/wnIdkvD.mp4

**Comment by rtsrick2017** [comment]
@gabz182 uh, not really, that is something else. what I meantioned happened when you try to switch from one type of arrow/bolt to another, that's why I used more than one for my test.

But that's another bug you've found then.

**Comment by 3Magic** [comment]
I think this is to do with Diamond Arrows not being stackable in your backpack.
On the floor, they are only stackable to a maximum of two.

**Comment by rtsrick2017** [comment]
@3Magic It might explain why they won't stack on the floor, but not why all kinds of ammo are being dropped on the floor when switched like that
