### ISSUE TITLE
Missing name item

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global#1044]
You see an item of type 12108.
Item ID: 12108
Position: 33364, 31321, 9

You see an item of type 12109.
Item ID: 12109
Position: 33362, 31322, 9

![image](https://user-images.githubusercontent.com/13306169/79604682-e9a3e880-80c4-11ea-8133-9293cdb32de3.png)

**Comment by gpedro** [comment]
you know which name?

**Comment by travisani** [comment]
No, i've tryied to check but no sucess.

**Comment by rtsrick2017** [comment]
@gpedro It's called "dragon spikes", back in the day I had all of the names up until zao, from exploring around with my main character.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/pull/1059/files#diff-02e835482c27350c416529c48adab50aR21861-R21862
