### ISSUE TITLE
containers bug

### ISSUE THREAD

**Issue by Emilianenko** [opentibiabr/otservbr-global#1054]
This bug only happens with normal characters ,gamemasters works fine .The bug happens when you have a container full of items, and inside this container a slot with some stackable item, for example a meat ,if i try to move a meat from the ground to the slot with the meat in my backpack i receive "you cannot put more objects in this container" even if i have capacity, and the slot is not full.
This bug seem to be related to this https://github.com/otland/forgottenserver/issues/1561
If the player has a large capacity left he can get the item, but if the capacity is low, even having enough to get the item he cannot .
https://vimeo.com/408981185

**Comment by rtsrick2017** [comment]
@Emilianenko possibly the same issue to what happens with the quick loot scripts that I've metioned here opentibiabr/otservbr-global#1030

**Comment by gpedro** [comment]
related otland/forgottenserver#2953

**Comment by FearLucien** [comment]
fix for this same issue on TFS https://github.com/otland/forgottenserver/pull/2955
