### ISSUE TITLE
Magic wall (Ms/ED)

### ISSUE THREAD

**Issue by joao-blip** [opentibiabr/otservbr-global#1076]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
When using the druid's magic wall and sorcerer the monsters are removing it
The correct thing would be when the player passes over it, but the monster cannot pass or remove it

**this is for no-pvp servers**

**Comment by Olimpotibia** [comment]
use the trap system

**Comment by Olimpotibia** [comment]
`local traps = {	
	[11099] = {transformTo = 2021, damage = {-0, -0}, type = COMBAT_EARTHDAMAGE},
	[10546] = {transformTo = 2021, damage = {-0, -0}, type = COMBAT_EARTHDAMAGE}
}

function onStepIn(creature, item, position, fromPosition)
	local trap = traps[item.itemid]
	if not trap then
		return true
	end

	if trap.ignorePlayer and creature:isPlayer() then
		return true
	end

	if trap.transformTo then
		item:transform(trap.transformTo)
	end

	doTargetCombatHealth(0, creature, trap.type or COMBAT_PHYSICALDAMAGE, trap.damage[1], trap.damage[2], CONST_ME_NONE)
	return true
end

function onStepOut(creature, item, position, fromPosition)
	item:transform(item.itemid - 1)
	return true
end

function onRemoveItem(item, tile, position)
	local itemPosition = item:getPosition()
	if itemPosition:getDistance(position) > 0 then
		item:transform(item.itemid - 1)
		itemPosition:sendMagicEffect(CONST_ME_POFF)
	end
	return true
end`

**Comment by Bipbop69** [comment]
with that the monster will pass, I think it would have to change in the src

**Comment by Olimpotibia** [comment]
you test it?

**Comment by Olimpotibia** [comment]
put it to walls in items.xml to monster no walk on

		<attribute key="type" value="field" />
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="45" />

**Comment by Bipbop69** [comment]
> put it to walls in items.xml to monster no walk on
> 
> ```
> 	<attribute key="type" value="field" />
> 	<attribute key="decayTo" value="0" />
> 	<attribute key="duration" value="45" />
> ```

this already exists as a default in the item in the .xml
