### ISSUE TITLE
deepling teleport

### ISSUE THREAD

**Issue by Juanzin420** [opentibiabr/otservbr-global#1156]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
nao da para passar no teleport

**To Reproduce**
1. Go to 'x33452 y31282 z14'
2. walk on teleport

**Expected behavior**
apos usar o teleport pela primeira vez vc ganha o atalho do teleport(33478 31312 7) para essa sala

**Screenshots**
![image](https://user-images.githubusercontent.com/64820180/81243871-fe4a1100-8fde-11ea-8a99-a02c2d6ca997.png)
![image](https://user-images.githubusercontent.com/64820180/81243909-10c44a80-8fdf-11ea-9197-74665a51cf80.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Comment by fabiobillz** [comment]
https://tibia.fandom.com/wiki/Liquid_Black_Quest

**Comment by Juanzin93** [comment]
Eu dei a volta como na quest.. o bug eh q nao da pra usar o teleport da sala pra voltar pro surface da ilha e ganhar acesso, invez de volta pro surface ele joga no meio da sala q vc esta

**Comment by gpedro** [comment]
can you test the PR opentibiabr/otservbr-global#1449?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
