### ISSUE TITLE
Ferumbras Ascension Road - Trapped Mobs

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/OTServBR-Global#119]
There are some mobs trapped on the Ferumbras Ascension Road. Also there is some spawn missing at the end of the road. Also I think there is some floor from above overlaping at the end of the road. 

20:02 You see a mountain.
Item ID: 4471
Position: 33305, 32417, 13

![feru](https://user-images.githubusercontent.com/51335460/58902659-d03fbb00-8703-11e9-81d8-839c34c4e2fe.PNG)

**Comment by eduardodantas95** [comment]
fixed, I will upload the map soon
ps: in fact the whole respawn was bugged, had monster inside the mountains and etc ... kkk
bugs inherited from otx ...
thanks
