### ISSUE TITLE
Creatures Can't Spawn - Fields

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global#1193]
If a creature is to be spawned through a script, such as the bigfoot burden/warzones, if there are energy fields (for example) where it would normally spawn, it won't.

What happens in global tibia is that the creature will spawn regardless, doesn't matter if there are stacked items, players or fields all over, it will be forced to spawn.

**Comment by jlcvp** [comment]
I think there's a flag to spawn forcibly
