### ISSUE TITLE
Portal to Winter Court - not working

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/OTServBR-Global#121]
Portal to Winter Court on Tyrsung isn't working.

20:08 You see a portal.
You can see the other side through it.
Item ID: 34618, Action ID: 3202
Position: 32354, 31247, 3

![winter court](https://user-images.githubusercontent.com/51335460/58903025-ae930380-8704-11e9-86df-8421fe5acaa2.PNG)

**Comment by eduardodantas95** [comment]
fixed on https://github.com/gpedro/OTServBR-Global/commit/72dddc61c93458b8bc7ac2a284d74cd9fe8ced7e
