### ISSUE TITLE
Item description bug

### ISSUE THREAD

**Issue by brunomaidana97** [opentibiabr/otservbr-global#1229]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

The second promotion (elite knight, royal paladin, elder druid, master sorcerer) is showing up when looking at items (equips, weapons, etc ...), which should not happen, as they are set to showindescription = "0" in movements.xml.

**To Reproduce**
1. Create a paladin armor or other armor
2. Click to look armor
3. See second promotion in armor
You see a paladin armor (Arm:12, distance fighting +2).
It can only be wielded properly by paladins and royal paladins.
Imbuements: (Empty Slot).
It weighs 65.00 oz.

**Expected behavior**
The correct is You see a paladin armor (Arm:12, distance fighting +2).
It can only be wielded properly by paladins.
Imbuements: (Empty Slot).
It weighs 65.00 oz.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version: [10]

**Comment by dudantas** [comment]
Fixed, thanks for your report!
