### ISSUE TITLE
Secret Library - Missing Spawn

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/OTServBR-Global#123]
There is missing spawn on the way to the Ice Section for sure. Sadly can't provide with any detailed pics on how it should look like there

**Comment by eduardodantas95** [comment]
Position?

**Comment by Szulcek69** [comment]
You need exact position of the missing mobs, or the position of the spawn Im talking about?

**Comment by Szulcek69** [comment]
Position: 32526, 32537, 12

**Comment by eduardodantas95** [comment]
Spawn of the area, thanks

**Comment by eduardodantas95** [comment]
fixed, I will upload the map soon
