### ISSUE TITLE
Itens no mapa.

### ISSUE THREAD

**Issue by neykos** [opentibiabr/otservbr-global#1239]
**#Venho reportar alguns itens no mapa que não deveriam estar no mapa.**

**1.  Holy orchid em Thais e Nostalgia.** 
Position: 32258, 32265, 7
Position: 32258, 32260, 7
Position: 33491, 31060, 7
Position: 33496, 31060, 7
**O item que se encontra nos barcos é id: 5922 e o correto seria 2761 .**
**Obs: O que está completamente errado porque assim os players podem coletar a cada vez que o servidor reiniciar.**

**2.  O segundo item fica na Position: 32599, 31748, 7.**
Seria um captured wolf em cima da magic wolf trap esse item não foi colocado pela cip ali em cima.

**3.  E possível pegar Rope belt no chão**
Position: 33241, 32574, 7
a cada vez que o servidor reiniciar.

**Comment by neykos** [comment]
4. É possível também achar na  Position: 33411, 32315, 12 e 33418, 32255, 11
strong health potion keg que é um item da store.

**Comment by dudantas** [comment]
Valeu, vou arrumar assim que possível

**Comment by LIKEAHYENA** [comment]
Na mesma cave onde está os potion kegs, também tem um Pharaoh Banner no chão.

00:39 You see pharaoh banner.
It weighs 10.00 oz.

Position: 33413, 32274, 12

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
