### ISSUE TITLE
Casas e premium time...

### ISSUE THREAD

**Issue by yehia** [opentibiabr/otservbr-global#1253]
Galera, seguinte....

Minha tabelas de houses está vazia... o myaac nem acha as casas.... e também verifiquei que o campo lastday do banco de dados está vazio.... mesmo comprando o premmium time, ele fica falando que a conta está freeacc...

**Comment by dudantas** [comment]
> Galera, seguinte....
> 
> Minha tabelas de houses está vazia... o myaac nem acha as casas.... e também verifiquei que o campo lastday do banco de dados está vazio.... mesmo comprando o premmium time, ele fica falando que a conta está freeacc...

Comprando premium através de comando ou store?

**Comment by dudantas** [comment]
Problema das casas: 
https://forums.otserv.com.br/index.php?/forums/topic/169318-myaac-problemas-ao-mostrar-casas/

**Comment by yehia** [comment]
Mesmo configurando os tows, ainda não funciona...

**Comment by dudantas** [comment]
> Mesmo configurando os tows, ainda não funciona...

Não sei o que te dizer. Não parece ser um bug do servidor, mas do site.

**Comment by yehia** [comment]
A tabela houses não tinha q sincronizar com o .xml?
