### ISSUE TITLE
PVP Hand

### ISSUE THREAD

**Issue by Juanzin420** [opentibiabr/otservbr-global#1255]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
if you close your pvp hand and die, the hand opens again

**Expected behavior**
keep hand closed even if u die

ubuntu 18.04

**Comment by Lycanzito** [comment]
when u die, everything is been "reseted", analyzers etc.

**Comment by Juanzin93** [comment]
Its not like that in real tibia, analyzer when u die it shows the exp u lost compared to the xp u made, if u made 30k xp , die and lose 25k xp , it shows u made 5k xp

**Comment by Lycanzito** [comment]
> Its not like that in real tibia, analyzer when u die it shows the exp u lost compared to the xp u made, if u made 30k xp , die and lose 25k xp , it shows u made 5k xp

Yep, I know.

Just adding this info to your issue;

=)

**Comment by FakeShinoda** [comment]
To fix all those things, we need to teleport the players to temple when they die like tibia rl, and not disconnet.

**Comment by Lycanzito** [comment]
> To fix all those things, we need to teleport the players to temple when they die like tibia rl, and not disconnet.

exactly

**Comment by Juanzin93** [comment]
That would be amazing👌 this way people can see how much exp and skill % they've lost
