### ISSUE TITLE
NO-PVP

### ISSUE THREAD

**Issue by brunomaidana97** [opentibiabr/otservbr-global#1277]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

it is not possible to walk through the player if you put the server in no-pvp

**To Reproduce**
1. Go to config.lua
2. Set in worldType = "no-pvp"
3. Enter the game and try to walk through another player where it is not PZ-zone or NO-PVP zone.

**Expected behavior**
Walk through the other player.

**Desktop (please complete the following information):**
- OS: Windows
 - Version: 10

**Comment by Bipbop69** [comment]
confirmed
