### ISSUE TITLE
Oberon Timer

### ISSUE THREAD

**Issue by CharlySample** [opentibiabr/otservbr-global#1279]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
If u pull the lever of Oberon and kill him or fail him. You get forever the timer of 20 hours and it will be at the char forever.

**To Reproduce**
1. Kill Oberon
2. Back the next day
3. See error
Note: include any configuration/script required to reproduce.

**Expected behavior**
It's expected to give u the chance to fight again with Oberon pass the 20 hours of storage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 18.04

**Additional context**

**Comment by CharlySample** [comment]
Fixed, just needs to change the formula of the boss storage like this:

`playerTile:setStorageValue(Storage.TheSecretLibrary.TheOrderOfTheFalcon.OberonTimer, os.time() + 20 * 60 * 3600) `

To

`playerTile:setStorageValue(Storage.TheSecretLibrary.TheOrderOfTheFalcon.OberonTimer, os.time() + 20 * 60 * 60)`

**Comment by dudantas** [comment]
It is not necessary to close the issue, only when it is corrected in the repository.

Thanks for the report and the solution.
