### ISSUE TITLE
Imbuing shrine bug

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global#1281]
**Describe the bug**
Items need not be upgraded if equipped, as that gives + 64k critical. Blocking when using imbue on an item in the set does not work as it can be used in the backpack and moved with WPE

**To Reproduce**
1. Put the item to improve in the backpack
2. Use the **Imbuing Shrine** to improve, but not "imbue"
3. Now the **WPE** with equip hotkey is used to move the item to the slot of the set without closing the **imbuing window** **(I think you should know how it would work, since I don't know how to explain it)**
4. Now yes, you have to imbue the item and then when you move the item to your backpack **you will have the skill bug, 64k mana, life leech or whatever you have chosen**.

**Expected behavior**
There should be a lock to be able to upgrade items when equipped, not simply add a lock when using the Imbuing Shrine to open the window.

**Desktop:**
 - OS: [e.g. **Debian Stretch**]
 - Version: [e.g. **9**]

Additional context:
None

**Comment by cacovi** [comment]
você quer dizer algo assim?

[https://streamable.com/onme0j](url)
