### ISSUE TITLE
Missing depot at Darashia's Eastern Guild Hall

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global#1287]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
There should be a depot in the basement of the Eastern Guildhall in Darashia.

**To Reproduce**
No need to.

**Expected behavior**
Add the depot.
Positions occupied by it:
X:33234 Y:32473 Z:8
X:33234 Y:32474 Z:8
X:33235 Y:32473 Z:8
X:33235 Y:32473 Z:8

**Additional context**
As shown in it's page on tibia fandom: [Darashia, Eastern Guildhall](https://tibia.fandom.com/wiki/Darashia,_Eastern_Guildhall), depot in the basement.

**Comment by gpedro** [comment]
can you test the PR opentibiabr/otservbr-global#1449?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
