### ISSUE TITLE
Wrong tile - Pool of blood in Carlin

### ISSUE THREAD

**Issue by LordSamoht** [opentibiabr/otservbr-global#1333]
**Describe the bug:**
Position: 32351, 31796, 7 (Carlin, next to NPC "Lector")
There's a pool of blood on this position, but the correct should be a pool of lifefluid

**To Reproduce:**
1. Go to NPC "Lector" in Carlin
2. Look on the pool

**Expected behavior:**
It says it's a pool of blood, but it should be a pool of lifefluid

**Desktop:**
 - OS: Windows
 - Version: 8.1

**Comment by gpedro** [comment]
unconfirmed. all images on internet show a pool of blood.

**Comment by dudztroyer** [comment]
https://i.imgur.com/8zwkFSC.jpg 

Confirmed, Pool of Lifefluid in Tibia Global as of 29/06/2020

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
