### ISSUE TITLE
Missing Daily Spawn and Decorations - Venore DP

### ISSUE THREAD

**Issue by LordSamoht** [opentibiabr/otservbr-global#1334]
**Describe the bug:**
There are some daily spawns missing on the Venore DP, next to NPC "Dove"
32920, 32074, 7 - missing "inkwell" (id: 2600)
32918, 32075, 7 - missing "venorean flower pot" (id: 19653)

**To Reproduce:**
1. Go to the center of the Venore DP

**Expected behavior:**
The daily spawn and the decorative plant are not there

**Desktop:**
OS: Windows
Version: 8.1

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
