### ISSUE TITLE
Can't open normal door - Villa Scapula (Black Knight Quest)

### ISSUE THREAD

**Issue by LordSamoht** [opentibiabr/otservbr-global#1335]
**Describe the bug:**
The door to the slime on "Villa Scapula" ("Black Knight Quest") can't be openend. You can normally open it without a key
Position: 32819, 31958, 8

**To Reproduce:**
1. Go to the first underground level of the "Villa Scapula" ("Black Knight Quest")
2. Go left and try to open the door

**Expected behavior:**
It should open, but it's not.

**Desktop:**
OS: Windows
Version: 8.1

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
