### ISSUE TITLE
rope spot not working but exani tera works

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global#1363]
![rope](https://user-images.githubusercontent.com/66652015/84817614-421f3580-afe3-11ea-8db2-c27134685e1f.png)

**Comment by gpedro** [comment]
![image](https://user-images.githubusercontent.com/2898638/85925903-7b6c6680-b869-11ea-8fd2-f58a58b79e4f.png)

this happens cuz rope spots should be a ground tile.
14435 (mud only) is not a ground tile, is just an "overground". 14436 is the correct ground tile and after changes, should work gracefully.


---
@dudantas please, replace 14435 to 14436.

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation

**Comment by runn3t** [comment]
I have a suggestion. If you try to get the ground thing + 1 in the "onUseRope" script and it's applied the same logic as for a ground rope thing should work correctly. Is just a idea idk if a problem can arise from this change :D
Then i think that all 14435 can work correctly. 

PD: I didn't test in all 14435 (just in one and was ok)

**Comment by gpedro** [comment]
@manolete6666 just updating my comment.
as i said, 14435 is not a rope spot, it is just a "hide tile" for rope spot. 14436 doesn't fit with the current ground terrain. so i decided to use the default rope spot and put 14435 on top.

**Comment by runn3t** [comment]
@gpedro okey understood! :+1:
