### ISSUE TITLE
Issues with NPC Astrad and his house's door.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global#1375]
**Describe the bug**
1 - Door to [Astrad](https://www.tibiawiki.com.br/wiki/Atrad) is locked.
2 - He should only talk to a player that has the Assassin Outfit, this is not needed atm.

**To Reproduce**
0. Go through the tedious step of going to Goroma.

1.1. Go to Astrad's house. Position: 32075, 32540, 7.
1.2. Try to open the door, says its locked. Shouldn't be.

2.1. Go to Astrad. Position: 32078, 32532, 9.
2.2. Try and talk to him, at the moment you only need to be on fire, but you should require level 80 and the base assassin outfit to talk to him. 

**Expected behavior**
The Door should be open and the npc should require the base assassin outfit.

**Additional context**
More information about him: [Astrad](https://tibia.fandom.com/wiki/Atrad)

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 and opentibiabr/otservbr-global#1405 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation

**Comment by nickolasdeluca** [comment]
> can you test PR opentibiabr/otservbr-global#1410 and opentibiabr/otservbr-global#1405 if the changes solve your problem?
> 
> --
> 
> If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation

Nope, still locked.
![image](https://user-images.githubusercontent.com/17858166/86026339-a8558080-ba05-11ea-98ff-edd3cada0a99.png)
