### ISSUE TITLE
Rashid Mission02 door with wrong action id.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global#1392]
**Describe the bug**
On RME, the door to get the package for Rashid has the actionId 1000, but the actions.xml on the datapack is triggered by actionId 1108.

**To Reproduce**
1. Go to X:32660 Y:32192 Z:8
2. Door doesn't open, doesn't matter if you have the correct storage.
3. Check the map on RME, you'll see that it calls for aid 1000.
4. On Actions.xml, the door script is waiting for aid 1108.

**Expected behavior**
Either set the actions.xml to aid 1000 or set the correct aid on the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/17858166/85472767-b2502d00-b588-11ea-9ee0-a3e48a2c53e0.png)

**Additional context**
Line 728 of data/actions/actions.xml: `<action actionid="1000" script="quests/the_travelling_trader/outlaw_camp_door.lua" />`

**Comment by gpedro** [comment]
can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation

**Comment by nickolasdeluca** [comment]
> can you test PR opentibiabr/otservbr-global#1410 if the changes solve your problem?
> 
> --
> 
> If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation

Testing it right now, I'll post back the results during lunch.

**Comment by nickolasdeluca** [comment]
Nope, the mentioned door still calls for aid 1108.

12:47 You see a closed door.
Item ID: 1223, Action ID: 1108
Client ID: 1642
Position: 32660, 32192, 8
