### ISSUE TITLE
Issavi map bug.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global#1394]
**Describe the bug**
After the commits of jun 14, Issavi map was damaged, some tiles are missing and the bridge was partially relocated.

**To Reproduce**
1. Go to X:33879 Y:31459 Z:7
2. As you can probably tell, the bridge is misplaced. 

**Expected behavior**
I don't know how to fix it, but the bridge shoud be crossable.

**Screenshots**
![image](https://user-images.githubusercontent.com/17858166/85491553-2222df80-b5aa-11ea-810b-6ca21341578e.png)

**Comment by perron5306987** [comment]
that position sends me to zao, not to issavi xd

**Comment by nickolasdeluca** [comment]
lol, sorry, I didn't know it was Zao, A player mentioned to me and I tp'd to him, don't even know how to get there, that's why I mentioned the XYZ position.
I'll correct the issue.

**Comment by lBaah** [comment]
It is NOT Zao. The position you wrote above sent him to Zao.

This is Issavi.

**Comment by nickolasdeluca** [comment]
> It is NOT Zao. The position you wrote above sent him to Zao.
> 
> This is Issavi.

Oh, I see my mistake now, I'll fix the issue, thanks!

**Comment by gpedro** [comment]
can you test the PR opentibiabr/otservbr-global#1449?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
