### ISSUE TITLE
Summons and monsters can move "immovable" items 

### ISSUE THREAD

**Issue by keloke1** [opentibiabr/otservbr-global#1422]
monsters and summons  can move immovable items with actionid:100

1) Create a movable item, chest, parcel, plant , etc
2) Set actionid:100 (makes the item immovable)
3) create a monster or summon with /s command or utevo res spell
4) make the summon walk on top of the items
5) this happens with monsters  who have flag canpushitems="1" in xml)

[click to see the gif ](https://gyazo.com/3c5e292489c70394756724e7766594a2)

Expected behavior
the summon or monsters  should walk over the item without moving it, in the case of the plant that can' t be walked on,  the summon or monster should dodge it without moving the plant.

quest chest (or item with uniqueid) summons walk over the item without moving it
[click to see the gif](https://gyazo.com/fe372aa63d61e5964c39c2fee1d42329)

**Comment by gpedro** [comment]
possible solution:
add a check if item has actionid 1000
- https://github.com/opentibiabr/otservbr-global/blob/fde29ef235ff7cfce5ee7fcf3d99c1df172f9f0f/src/monster.cpp#L1132

**Comment by gpedro** [comment]
can you test the PR opentibiabr/otservbr-global#1450 ?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
