### ISSUE TITLE
killing in the name of

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/OTServBR-Global#144]
**Describe the bug**
killing in the name of quest bosses storages are conflicting with storages in threaten dreams quest. 

example in flies 
OTServBR-Global\data\lib\miscellaneous
storages and killinginthenameof

value = {"Blood-Red Snapper"}},{type = "storage", value = {35000, 1}}
{"No More Hiding"}},{type = "storage", value = {35001, 1}} and so on.

	ThreatenedDreams = {
		-- WIP
		-- Reserved storage from 34999 - 35100
		Start = 35000,
		TroubledMission01 = 35001,
		TroubledMission02 = 35002,
		TroubledMission03 = 35003,

Threaten Dreams quest needs new storages.

**Comment by eduardodantas95** [comment]
@Raphaellb thanks for the report, fixed

**Comment by Raphaellb** [comment]
Hello, this is not fully fixed. the reason I asked for the Threaten Dreams quest storages to be changed is that the killing in the name of storages are used in two other files. 

We either need to update those two files as well, or update Threaten Dreams storages. Please re-open issue. 
@eduardodantas95 @gpedro 

OTServBR-Global-master/data $ grep -R "35006"
**movements/scripts/quests/killinginthenameof/boss.lua:**	[3236] = {bossName = 'fleshcrawler', storage = 35006, playerPosition = Position(33100, 32785, 11), bossPosition = Position(33121, 32797, 11), centerPosition = Position(33112, 32789, 11), rangeX = 15, rangeY = 13, flamePosition = Position(33106, 32775, 11)},
**lib/miscellaneous/051-storages.lua**:		FairyMission03 = 35006,
**lib/core/quests.lua:**					name = "Paw and Fur: Fleshcrawler", storageid = 35006, startvalue = 1, endvalue = 2, description = "Try find its hideout and kill it.",
