### ISSUE TITLE
[Bug] Heavy Old Tome.

### ISSUE THREAD

**Issue by ruanfurious** [opentibiabr/otservbr-global#1457]
Os baús pra pegar o Livro ta bugado, vc clica no bau fala que vc pegou o livro porem nao ta indo pra bp, ai vc clica de novo fala que ta empty.

OBS-  os demais baus existentes no mapa pra pegar o livro tbm mesma coisa.

Position - 32349, 32194, 9

**Comment by majestyotbr** [comment]
Confirmed.
