### ISSUE TITLE
Ferumbras Ascension 

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/OTServBR-Global#157]
Ferumbras Ascension Infernatil - Mazoran's Seal missing action ids on red and green tiles. blue seems to have it.

green with missing action id 
21:30 You see a large gem.
Item ID: 9565
Position: 33660, 32627, 13
red with missing action id 
21:31 You see a large gem.
Item ID: 9562
Position: 33626, 32621, 13
**blue with correct action id** 
21:32 You see a large gem.
Item ID: 9563, Action ID: 53813
Position: 33635, 32682, 13
movements.xml
	
	<movevent event="StepIn" actionid="53812" script="quests/ferumbras ascendant/redGem.lua" />
	<movevent event="StepIn" actionid="53813" script="quests/ferumbras ascendant/blueGem.lua" />
	<movevent event="StepIn" actionid="53814" script="quests/ferumbras ascendant/greenGem.lua" />

Mazoran lever has a unique ID of 9520 in Map, but in actions.xml has a different id. either change the id on actions.xml or in map to match.
21:45 You see a lever.
Item ID: 9825, Unique ID: 9520
Position: 33593, 32643, 14
<action actionid="24851" script="quests/ferumbras ascendant/mazoranLever.lua" />

**Comment by eduardodantas95** [comment]
Very thanks, fixed =D
