### ISSUE TITLE
Gambling money can be stolen now

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global#1578]
![gambling](https://user-images.githubusercontent.com/66652015/88491100-75ec6400-cf6e-11ea-8d5b-5427d6c5b688.png)

**Comment by gpedro** [comment]
how we can reproduce?

**Comment by ghost** [comment]
@Mortalot don't get me wrong with this comment, but I'm literally begging you, use the project's bug report template when opening new issues.

**Comment by majestyotbr** [comment]
It's just the wrong position of the NPC Cassino.

https://github.com/opentibiabr/otservbr-global/blob/develop/data/world/custom/otservbr-custom-spawn.xml

Change to:
```
<spawn centerx="32354" centery="32226" centerz="7" radius="1">
	<npc name="cassino" x="0" y="0" z="7" spawntime="60" />
</spawn>
```

**Comment by Mortalot** [comment]
> @Mortalot don't get me wrong with this comment, but I'm literally begging you, use the project's bug report template when opening new issues.

idk what you mean, sorry.

**Comment by ghost** [comment]
> > @Mortalot don't get me wrong with this comment, but I'm literally begging you, use the project's bug report template when opening new issues.
> 
> idk what you mean, sorry.

when creating a new issue ("New issue" green button) you have three options, as you can see on the following screenshot:
https://snipboard.io/4DNo6b.jpg

Click on "Get started" at "Bug report" and on the next page do not erase the text. Edit it filling with your bug report information:
https://snipboard.io/oivLfd.jpg

By doing that you will provide the necessary info for everyone who may be able to fix the bug you're reporting.
