### ISSUE TITLE
O Sistema de natação deveria limpar condições

### ISSUE THREAD

**Issue by antonioaraujo664** [opentibiabr/otservbr-global#1620]
Commit baixada do dia 12-07-2020

![image](https://user-images.githubusercontent.com/16484533/89290638-89af5e80-d62f-11ea-8893-ccc548362c99.png)

**Comment by antonioaraujo664** [comment]
https://www.tibiawiki.com.br/wiki/Nadar
"_Em uma parte do Updates/8.1, novas praias públicas foram abertas por todo o Tibia. Agora personagens podem sem problema algum dar um mergulho no mar. Esta função permitiu a prática de novos jogos, como Polo Aquático....

Um outro benefício de ir nadar é ao nadar apaga fogo, neutraliza eletricidade, limpa qualquer veneno, aguça devolta os sentidos, desfaz maldições, suaviza congelamentos, revitaliza um bêbado assim como também limpa qualquer outra Condição Especial!_"

**Comment by Briluxxx** [comment]
https://github.com/otland/forgottenserver/pull/3151

**Comment by majestyotbr** [comment]
Can you test opentibiabr/otservbr-global#1630?
