### ISSUE TITLE
Missing Teleport - West Thais Cyclops

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global#1621]
Position: 32225, 32276, 10
![image](https://user-images.githubusercontent.com/7588103/89295748-b4b2a600-d661-11ea-861d-c36a903524f7.png)

**Comment by gpedro** [comment]
this teleports should be teleport for where?

**Comment by cys9211** [comment]
This teleport should teleport to Position: 32231, 32276, 9
This is a return from the Mission
![image](https://user-images.githubusercontent.com/7588103/89308186-44f8e700-d672-11ea-9f50-e56d6d68f8b4.png)


https://youtu.be/5JlrxIouNOo?t=93

**Comment by dudantas** [comment]
The teleport should be created together with the entrance.
