### ISSUE TITLE
Players can use teleport scroll of game store  with pz

### ISSUE THREAD

**Issue by Attack787** [opentibiabr/otservbr-global#1665]
**Describe the bug**
Players with pz (combat by monster or fileds) can use teleport scroll. Players with pz combat (PVP) can't, this is right. In global you only can used scroll teleport without pz.

**To Reproduce**
1. Go hunt and get pz locked by monster or fields (fire, energy..)
2. Buy in store teleport scroll
3. You go to temple you are living

**Expected behavior**
You can't get teleport because you have a pz locked. After losing pz you can use teleport scroll

**Desktop (please complete the following information):**
WINDOWS 10

**Comment by marcosvf132** [comment]
![image](https://user-images.githubusercontent.com/66353315/90566699-4dc3df80-e17f-11ea-912f-b537064fb5b1.png)
I cant reproduce it, can you be more specific?

**Comment by attack787** [comment]
Yes. Look to the pictures.
![image](https://user-images.githubusercontent.com/47985212/90573255-6090e100-e18c-11ea-93a3-cd46785cd915.png)
Players with pz (combat by monster or fileds) can use teleport scroll purchased in gamestore. I said teleport scroll and correct is temple teleport.

**Comment by dudantas** [comment]
PZ (locked)
