### ISSUE TITLE
Stack bug

### ISSUE THREAD

**Issue by xThauma** [opentibiabr/otservbr-global#1748]
You can't take the stackable item from the ground if your backpack got all slots used and you have this stackable item.
Example:
1 gmp laying on the ground
Player Has 19 Items and 50 gmp in the backpack.
Player tries to pick up 1 gmp and put it into 50 gmp in the backpack.
Player gets an error saying he cannot do it

**Comment by MajestyOTBR** [comment]
Maybe this issue was fixed before, because i didn't confirmed here.

**Comment by MajestyOTBR** [comment]
Tested again with updated repository and compatible executable, can't reproduce the issue.
