### ISSUE TITLE
Gnome Helmet and Falcon Circlet can't get imbued with magic level boost

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/OTServBR-Global#177]
Gnome Helmet and Falcon Circlet can't get imbued with magic level boost

**Comment by luucassoares** [comment]
This is easy, go to scripts/imbuement/imbuement.lua and look for a variable named Weapons. Add the items' id on the correct section and that is it.

**Comment by gpedro** [comment]
@luucassoares can you send to us a PR with that?

**Comment by luucassoares** [comment]
I'm sorry i just saw this message.. seems like someone else already did it. But i find any other bug and I correct I will send u a PR

**Comment by gpedro** [comment]
@Szulcek69 can you test PR #194 ?
