### ISSUE TITLE
Bone Fiddle doesn't have a spirte and can't be moved when spawned as GM

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/OTServBR-Global#178]
Bone Fiddle doesn't have a spirte and can't be moved when spawned as GM

**Comment by eduardodantas95** [comment]
![image](https://user-images.githubusercontent.com/8551443/60209130-59906c00-9830-11e9-8758-005b2a0882ff.png)


You are using the repository client ?

**Comment by eduardodantas95** [comment]
![image](https://user-images.githubusercontent.com/8551443/60209201-8775b080-9830-11e9-834d-1c8617156280.png)

**Comment by eduardodantas95** [comment]
Sorry, have two bone fiddle registered in items.xml, thanks for the report

`<item id="32076" article="a" name="bone fiddle without strings">
		<attribute key="weight" value="3700" />
	</item>
	<item id="32077" article="a" name="bone fiddle">
		<attribute key="weight" value="3800" />
		<attribute key="absorbPercentLifeDrain" value="5" />
		<attribute key="showattributes" value="1" />
	</item>`

`<item id="33275" article="a" name="bone fiddle without strings">
		<attribute key="weight" value="3700" />
	</item>
	<item id="33276" article="a" name="bone fiddle">
		<attribute key="weight" value="3800" />
		<attribute key="absorbPercentLifeDrain" value="5" />
		<attribute key="showattributes" value="1" />
	</item>`
