### ISSUE TITLE
Correct body of The Sandking.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global#1808]
just change this line.
the boss is in data / monsters / quest / cults_of_tibia / bosses / the_sandking.xml

<look type = "1013" corpse = "29142" />

**Comment by majestyotbr** [comment]
Look in the datapack, the monsters in xml does not exists anymore, they are in revscriptsys now:
https://github.com/opentibiabr/otservbr-global/tree/develop/data/scripts/monsters

**Comment by majestyotbr** [comment]
About the corpse of The Sandking, i'll check later.

**Comment by ivansho92** [comment]
yeah, im sorry, already change the branch, the real way is:
data/scripts/monsters/quest/cults_of_tibia/bosses/the_sandking

monster.race = "venom"
monster.corpse = 29142

and is the real corpse.
