### ISSUE TITLE
Wrong price in outfit store.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global#1849]
in Store this outfit have a wrong price.

          name = "Full Sinister Archer Outfit",
          price = 120,
          sexId = {female = 1103,  male = 1102},
          addon = 3,

the real price is 600, literal, they are giving away with a super discount that outfit  LMAO

**Comment by majestyotbr** [comment]
FEEL FREE TO CONTRIBUTE AND SEND A PULL REQUEST WITH THE FIX.
