### ISSUE TITLE
Monsters moving a little too slowly

### ISSUE THREAD

**Issue by Tarien** [opentibiabr/OTServBR-Global#187]
Monsters such as Dragons/Dragon Lords move too slowly

**Comment by luucassoares** [comment]
I noticed Asuras, rats and rotworms in Thais sewer, Diremaw and Deepworms are walking slowly too

**Comment by gpedro** [comment]
yea, that's confirmed! I have updated all monsters health, mana, voices, loot (removed unknown drops) and speed using tibia.fandom.com. But i need confirm if this is a problem of monster or tile.
