### ISSUE TITLE
Showing Charges.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global#1883]
In tibia RL, every item with charges, show the real amount.
but in server just showing one charge.
Examples.
23:55 You see a silver amulet (protection earth +10%) that has 200 charges left.
It weighs 5.00 oz.
IN RL
but in last branch have problems with         <attribute key="showcharges" value="1" />

23:56 You see a silver amulet (protection earth +10%) that has 1 charge left.
It weighs 5.00 oz.  all items with charges just showing one charge

**Comment by xThauma** [comment]
This happends with prey loot. Extra loot appears with 1 charge.
Simply fix by changing to 

```
				local itemType = ItemType(k.itemId)
				if itemType then
					if itemType:getCharges() > 0 then
						local item = corpse:addItem(k.itemId, itemType:getCharges())
					else
						local item = corpse:addItem(k.itemId, math.random(k.maxCount))
					end
				end
```
The same happends with boss reward script. ^ will fix too

**Comment by Darcksody** [comment]
On line opentibiabr/otservbr-global#40 of **data/lib/core/container.lua** add this:

`if lootBlockType:getCharges() > 0 then
tmpItem:transform(item.itemId, lootBlockType:getCharges())
end`

**Comment by IgorCFG** [comment]
the problem is not in the "look" but in the `charges` the correct issue for this problem is opentibiabr/otservbr-global-datapack#211
