### ISSUE TITLE
Bath tub dissapears after server save

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global#1912]
the bathtub is the only item that disappears with each ss, everything else works fine, items, hirelings all fine.

**Comment by debone** [comment]
Thanks for the report @ivansho92 ! Have you tried fixing it? Seems like an easy one, and we could benefit from more contributions :)

Also, please stick to the bug report template when creating an issue.

**Comment by ivansho92** [comment]
yes bro i was trying some things but unsuccessfully

**Comment by IvanMir014** [comment]
Also item soulbleeder(id: 38923) disapear from houses dps after server save, also tried to fixed but unsuccessfully.

**Comment by gpedro** [comment]
confirmed. he disappears if the bathtub was filled.
