### ISSUE TITLE
Question about tibia.dat/tibia.spr

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global#1918]
Hey guys, sorry if this isnt the right place to ask questions. I'll try, feel free to bash and shame me. 
I'm trying to run the map in RME, but I cant locate tibia.dat/tibia.spr in assets. I suspect I need to use VS, but..but..but how?

**Comment by debone** [comment]
Hello @Davenorthern, there's no shame in asking questions :) I think the best place for you to find these answers are going to be in our Discord channel. We have a collection of links in the channel #links that will have the answer for this problem.
