### ISSUE TITLE
Loot: Charged amulets and charged rings

### ISSUE THREAD

**Issue by shumagoraa** [opentibiabr/otservbr-global#1943]
Charged amulets and charged rings are coming with 1 charge from the monsters.

elder wyrm
{id = "shockwave amulet", chance = 100},
{id = "lightning pendant", chance = 520},

after: 
{id = "shockwave amulet", charges = 5, chance = 100},
{id = "lightning pendant", charges = 200, chance = 520},

**Comment by IgorCFG** [comment]
This was not supposed to be an issue haha.
We need a list of the monsters that drop charged items to fix everything ♻

**Comment by debone** [comment]
Thanks for the report @shumagoraa  ! Have you got a go in trying fixing it? Seems like a simple one, and we could benefit from more contributions :) If you don't know how to contribute, you can try using this [tutorial](https://github.com/firstcontributions/first-contributions) and help the OTServBR project.

@IgorCFG I checked the original XMLs and it seems that we don't have such information. Maybe this was working before given the way we added the loot for xml monsters? May be worth a check before moving on to fix every monster.

**Comment by IgorCFG** [comment]
@debone yeah, maybe we can make this correction without having to correct each one.
It's possible that the attributes of **items.xml** are being overwritten by the attributes (or the lack of the attribute) of the loot inside the {monster}.lua

On `items.xml` that's ok.
```xml
<item id="10221" article="a" name="shockwave amulet">
	<attribute key="description" value="It tickles your neck in a rather pleasant way and absorbs loads of damage." />
	<attribute key="weight" value="700" />
	<attribute key="slotType" value="necklace" />
	<attribute key="loottype" value="amulet" />
	<attribute key="charges" value="5" />
	<attribute key="showcharges" value="1" />
	<attribute key="absorbPercentPhysical" value="60" />
	<attribute key="absorbPercentEnergy" value="40" />
</item>
```
