### ISSUE TITLE
Hp and mana gain per second

### ISSUE THREAD

**Issue by coney4** [opentibiabr/OTServBR-Global#196]
All gainhpticks, gainhpamount, gainmanaticks and gainmanaamount are wrong according to rl tibia.
Its easy to change. I would change it but i dont know how to create pull request it says (We dont support that file type). I tried to upload vocations.xml.

**Comment by gpedro** [comment]
open the file
https://github.com/opentibiabr/OTServBR-Global/blob/master/data/XML/vocations.xml

click on edit (pencil icon)
- github will automatically fork the repository
paste your changes and before that, he will ask if you want to create a pull request.

**Comment by coney4** [comment]
thank you
