### ISSUE TITLE
BUG: Summons ataque follow bug.

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global#1995]
Quando um Grovebeast ou qualquer outro summon de outras vocações é sumonado.. e você coloca para atacar um monstro, o seu summon não segue o monstro para ataca-lo, ele simplesmente fica parado.

**Comment by gerotib** [comment]
Theres also similar problem with convince creature rune, you need to re-attack target to make summons follow and attack it.

**Comment by mrleao** [comment]
Amigo lá no .lua do summon 
Altere o targetDistance = 0 para targetDistance = 1.

monster.flags = {
	summonable = true,
	attackable = true,
	hostile = false,
	convinceable = true,
	pushable = true,
	rewardBoss = false,
	illusionable = false,
	canPushItems = false,
	canPushCreatures = true,
	staticAttackChance = 90,
	targetDistance = 1,
	runHealth = 0,
	healthHidden = false,
	canWalkOnEnergy = false,
	canWalkOnFire = false,
	canWalkOnPoison = false
}
