### ISSUE TITLE
Charms.lua cannot add bestiary kills, charm expansion, runes...Hireling outfit change

### ISSUE THREAD

**Issue by Risk-CPU** [opentibiabr/otservbr-global#2116]
### **Commands that doesnt work:**

**/setbestiary ...  error**

> ```
> Lua Script Error: [Scripts Interface]
> C:\Users\kr\Desktop\otservbr-global-develop\data\scripts\talkactions\god\charms.lua:callback
> ...r-global-develop\data\scripts\talkactions\god\charms.lua:148: attempt to index global 'Bestiary' (a nil value)
> stack traceback:
>         [C]: in function '__index'
>         ...r-global-develop\data\scripts\talkactions\god\charms.lua:148: in function <...r-global-develop\data\scripts\talkactions\god\charms.lua:124>
> ```

 **/charmexpansion error**

> ```
> Lua Script Error: [Scripts Interface]
> C:\Users\kr\Desktop\otservbr-global-develop\data\scripts\talkactions\god\charms.lua:callback
> ...r-global-develop\data\scripts\talkactions\god\charms.lua:84: attempt to call method 'setCharmRuneSlotExpansion' (a nil value)
> stack traceback:
>         [C]: in function 'setCharmRuneSlotExpansion'
>         ...r-global-develop\data\scripts\talkactions\god\charms.lua:84: in function <...r-global-develop\data\scripts\talkactions\god\charms.lua:68>
> ```

**/charmrunes error**

> ```
> Lua Script Error: [Scripts Interface]
> C:\Users\kr\Desktop\otservbr-global-develop\data\scripts\talkactions\god\charms.lua:callback
> ...r-global-develop\data\scripts\talkactions\god\charms.lua:110: attempt to call method 'getCharmUnlockedRunesBit' (a nil value)
> stack traceback:
>         [C]: in function 'getCharmUnlockedRunesBit'
>         ...r-global-develop\data\scripts\talkactions\god\charms.lua:110: in function <...r-global-develop\data\scripts\talkactions\god\charms.lua:94>
> ```

**/resercharms error**

> ```
> Lua Script Error: [Scripts Interface]
> C:\Users\kr\Desktop\otservbr-global-develop\data\scripts\talkactions\god\charms.lua:callback
> ...r-global-develop\data\scripts\talkactions\god\charms.lua:52: attempt to call method 'setCharmPoints' (a nil value)
> stack traceback:
>         [C]: in function 'setCharmPoints'
>         ...r-global-develop\data\scripts\talkactions\god\charms.lua:52: in function <...r-global-develop\data\scripts\talkactions\god\charms.lua:36>
> ```

**Only one that works is /addcharms PLAYER NAME,AMOUNT but the rest doesnt work and doesnt update **database****

**Hireling outfit change cause tibia client crash, debug.**

**Comment by marcosvf132** [comment]
I have updated the PR opentibiabr/otservbr-global#2140, can you test all changes now?
