### ISSUE TITLE
MAP: 

### ISSUE THREAD

**Issue by Santejious** [opentibiabr/otservbr-global#2138]
#### What are the coordinates of the place where the issue with the map was found?

23:58 You see an ice shrine.
Item ID: 7510
Client ID: 152
Position: 32194, 31419, 2
---
23:58 You see an earth shrine.
Item ID: 7518
Client ID: 160
Position: 32973, 32226, 7
---
23:59 You see an energy shrine.
Item ID: 7514
Client ID: 156
Position: 33060, 32714, 5
---
23:59 You see a fire shrine.
Item ID: 7506
Client ID: 148
Position: 32910, 32339, 15
---

#### What kind of issue you found (respawns missing, details, large areas...)?
- shrine de feyrist

#### What was expected to be in place?
> dar tp para feyrist aos usar as pedrinhas

#### Environment
- OS (e.g. Windows): w10
- OTServ Version (e.g. commit): 12,6
- Tibia Version (e.g. 12.52): 12,6

#### Additional context
> Add any other context about the problem here.

**Comment by dudantas** [comment]
https://github.com/opentibiabr/otservbr-global/blob/bae6f3a930f036eb73c114e728109201bf3f7d41/data/scripts/actions/other/gems.lua#L92

As shown in this line, you need this storage to access the teleport.

**Comment by hyresu** [comment]
It is working as intended, check on what dudantas said
![image](https://user-images.githubusercontent.com/61813040/103076070-a2eb8400-45ab-11eb-95e1-22a0a7e4667f.png)
