### ISSUE TITLE
Svargrond arena doors bug

### ISSUE THREAD

**Issue by coney4** [opentibiabr/OTServBR-Global#218]
When you try open door it shows error

Lua Script Error: [Action Interface]
data/actions/scripts/quests/svargrond arena/arenaDoor.lua:onUse
data/actions/scripts/quests/svargrond arena/arenaDoor.lua:13: attempt to index global 'storages' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/actions/scripts/quests/svargrond arena/arenaDoor.lua:13: in function <data/actions/scripts/quests/svargrond arena/arenaDoor.lua:1>

**Comment by Raphaellb** [comment]
are you using the lastest distro+pack? I have already tested the svargrond arena, and everything worked correctly for me.

**Comment by coney4** [comment]
yes
Problem is something with this
```
local storages = {
	[26100] = Storage.SvargrondArena.Greenhorn,
	[27100] = Storage.SvargrondArena.Scrapper,
	[28100] = Storage.SvargrondArena.Warlord
}
```
this was deleted in some commit

and this line needs to be fixed 
`local cStorage = storages[item.actionid]`

**Comment by gpedro** [comment]
that's right. this commit 387cef00b2cb8cd556ca94f9909f6e51cae98527 removed this table

**Comment by eduardodantas95** [comment]
fixed on https://github.com/opentibiabr/OTServBR-Global/pull/224
