### ISSUE TITLE
BUG: Prey bonus

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global#2246]
#### Describe the bug
> Prey bonus changing (rare) when reroll monster

#### How to Reproduce?
> Reroll prey ( Cards or money)

#### Logs or errors
> none

#### Expected behavior
> Bonus should not change when rerolling creature

#### Screenshots
![Untitled](https://user-images.githubusercontent.com/55179288/103854015-5c059e80-5114-11eb-9063-edf4513edb4b.png)

**Comment by henriquesameshima** [comment]
Here it works normal.

![prey reroll](https://user-images.githubusercontent.com/9365346/106800108-d3a8e980-663e-11eb-8e12-ec0575637ee8.gif)

**Comment by yatozin** [comment]
> Here it works normal.
> 
> ![prey reroll](https://user-images.githubusercontent.com/9365346/106800108-d3a8e980-663e-11eb-8e12-ec0575637ee8.gif)

Doesnt happen everytime and with all monsters, as i said rare. its most likley just certian monsters, also try with cards were you select the monster if you try the one i used you will see the problem.
