### ISSUE TITLE
BUG: Cledwyn

### ISSUE THREAD

**Issue by joao-blip** [opentibiabr/otservbr-global#2374]
npc is not exchanging items
'pendulet', 'sleep shawl', 'blister ring', 'theurgic amulet' 

`
-  Lua Script Error: [Npc interface]
-  data/npc/scripts/cledwyn.lua:onCreatureSay
-  data/npc/scripts/cledwyn.lua:130: attempt to concatenate global 'charge' (a nil value)
-  stack traceback:
-   [C]: in function '__concat'
-   data/npc/scripts/cledwyn.lua:130: in function 'callback'
-   data/npc/lib/npcsystem/npchandler.lua:433: in function 'onCreatureSay'
-   data/npc/scripts/cledwyn.lua:13: in function <data/npc/scripts/cledwyn.lua:12>
`

**Comment by majestyotbr** [comment]
@joao-blip i said in other issue and i repeat, you don't need to close the issue. It can be closed after pull request merge.
