### ISSUE TITLE
svargrond otherworld entrance

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/OTServBR-Global#239]
**Describe the bug**
missing hole to enter the otherworld entrance in Svargrond

**To Reproduce**
go to position 
07:30 You see an ice hole.
You can see the movement of fish.
Item ID: 7236
Position: 32165, 31294, 6
**Expected behavior**
Should be a hole there to enter Otherworld spawn.

**Comment by EPuncker** [comment]
please test/check it after PR #294 get merged
