### ISSUE TITLE
Error on player login

### ISSUE THREAD

**Issue by coney4** [opentibiabr/OTServBR-Global#24]
[Error - Monsters::deserializeSpell] - Thawing Dragon Lord - Unknown spell name: Ice Crystal Bomb
[Warning - Monsters::loadMonster] Cant load spell. data/monster/11.8/thawing dragon lord.xml

**Comment by eduardodantas95** [comment]
@coney4 it's is need to create spell script "thawing dragon lord.lua" at spells/scripts/monster/

thanks for the report
