### ISSUE TITLE
Item 8478 bugado

### ISSUE THREAD

**Issue by EPuncker** [opentibiabr/OTServBR-Global#240]
**Describe the bug**
O item 8478 era pra ser uma stone wall, porém está com o sprite de uma claw of the noxius spawn

**To Reproduce**
1. /i 8478

**Expected behavior**
era pra ser uma stone wall

**Screenshots**
![2019-07-08 12_36_21-Window](https://user-images.githubusercontent.com/4684880/60823037-034ef180-a17d-11e9-8788-678d4a198c7e.jpg)

**Comment by eduardodantas95** [comment]
![image](https://user-images.githubusercontent.com/8551443/60853240-8437d880-a1d1-11e9-9aec-c78bf0eee670.png)

Thanks, fixed
