### ISSUE TITLE
BUG: Tortoise Egg from Nargor Mission

### ISSUE THREAD

**Issue by jollyrogers91** [opentibiabr/otservbr-global#2404]
#### Describe the bug
> A clear and concise description of what the bug is.

#### How to Reproduce?
> If you cannot reproduce an issue by redoing the same steps, we also will not be able :)
Just go to Position: 31938, 32837, 7 and click on tortoise egg it should give item(6125) during the pirate outfit quests, but sends a callback error on console and you get stucked on it.

> Give us all details to reproduce the behavior:
> 1. Walk to city '...'
> 2. Click on item '....'
> 3. Drag it to backpack '....'
> 4. See error

#### Logs or errors
> Please include any errors or logs that are relevant

#### Expected behavior
> A clear and concise description of what you expected to happen.

#### Screenshots
> If applicable, add screenshots to help explain your problem.
https://gyazo.com/28ada7b089ff1f11fbfd2e58c730195d

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52): 

#### Additional context
> Add any other context about the problem here.

**Comment by henriquesameshima** [comment]
@jollyrogers91 please update with opentibiabr/otservbr-global#2407 and let me know if it works.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: opentibiabr/otservbr-global#726
