### ISSUE TITLE
BUG: Several warzone 4/5/6 damaging each other and them self

### ISSUE THREAD

**Issue by thovanderlaann** [opentibiabr/otservbr-global#2414]
#### Describe the bug
Several monsters can damage each other

#### How to Reproduce?
Start warzone 4/5/6

> Give us all details to reproduce the behavior:
> 1. Go to warzone 4/5/6
> 2. Start it
> 3. Monsters will damage each other

#### Expected behavior
> They shouldn't damage each other

#### Screenshots
![image](https://user-images.githubusercontent.com/32771228/107856904-b983be00-6e2b-11eb-9a8a-ecc0ca69a110.png)

#### Environment
- OS: Windows
- OTServ Version: Latest
- Tibia Version: 12.62

#### Additional context
> The fiery hearts also damage the boss The Duke of the Depths and them self.
> Same goes for the aggressive lava, damaging itself and The Baron From Below
> Same goes for the ember beasts, damaging The Count Of The Core and it self.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: opentibiabr/otservbr-global#726
