### ISSUE TITLE
BUG: hunt analyzer

### ISSUE THREAD

**Issue by joao-blip** [opentibiabr/otservbr-global#2456]
It is not counting right I will use a photo that I found on discord 
![image](https://user-images.githubusercontent.com/64280614/109371417-9cb3a580-7883-11eb-9658-a09d343e96c2.png)

Guz today às 01:4
'drop 123 platinum, he scores 524 ... he drops 7 crystal coins he scores 112 ... (remembering that the bag you desire is not counting in the total balance amount ..) '

**Comment by dex-89** [comment]
Are you using the original otbr engine or do you have any add-ons (VIP loot etc)?

**Comment by Bipbop69** [comment]
original

**Comment by henriquesameshima** [comment]
@joao-blip thx for report it.
Make this change and let me know if it works properly.

https://github.com/opentibiabr/otservbr-global/compare/develop...henriquesameshima:fix-2456

**Comment by Bipbop69** [comment]
> @joao-blip thx for report it.
> Make this change and let me know if it works properly.
> 
> [develop...henriquesameshima:fix-2456](https://github.com/opentibiabr/otservbr-global/compare/develop...henriquesameshima:fix-2456)

![image](https://user-images.githubusercontent.com/64280614/109586334-ca972500-7ae3-11eb-8164-dfb61afd9b33.png)

23:12 Loot of a demon: 3 great spirit potions, 3 great mana potions, a demon horn, 3 fire mushrooms, 3 platinum coins, 45 gold coins, 100 gold coins

**Comment by henriquesameshima** [comment]
@joao-blip test again.
https://github.com/opentibiabr/otservbr-global/compare/develop...henriquesameshima:fix-2456

**Comment by Bipbop69** [comment]
> @joao-blip test again.
> [develop...henriquesameshima:fix-2456](https://github.com/opentibiabr/otservbr-global/compare/develop...henriquesameshima:fix-2456)

I'm testing it looks like it fixed
