### ISSUE TITLE
BUG: healing runes can heal monster 

### ISSUE THREAD

**Issue by Zapotoczny** [opentibiabr/otservbr-global#2563]
ultimate healing runes and intense healing runes can heal monsters

**Comment by rusaskii** [comment]
Exura gran mas res spell heals summons too.

**Comment by ArturKnopik** [comment]
if summons can be healed and other monster no put this code:
```cpp
if (damage.primary.type == COMBAT_HEALING && target && target->getMonster()) {
	if (target != attacker) {
		if (target->getMaster() != attacker){
			return false;
		}
	}
}
```
here: 
 https://github.com/opentibiabr/otservbr-global/blob/8427233cacf98d6c733be2ed91951e368eb5c05a/src/game/game.cpp#L5387
second case: if all monsters/summons cannot be healing 

this add
```cpp
if (params.combatType == COMBAT_HEALING && target->getMonster()){
	if (target != caster)		{
		return;
	}
}
```
 here 
https://github.com/opentibiabr/otservbr-global/blob/8427233cacf98d6c733be2ed91951e368eb5c05a/src/creatures/combat/combat.cpp#L868

and this:
```cpp
if (damage.primary.type == COMBAT_HEALING && target && target->getMonster()) {
	if (target != attacker) {
		return false;
	}
}
```
here 

https://github.com/opentibiabr/otservbr-global/blob/8427233cacf98d6c733be2ed91951e368eb5c05a/src/game/game.cpp#L5660

if that fixes the problem someone do pull request

**Comment by beats-dh** [comment]
Test if it works, if so cite the spells that have to be fixed I open PR

**Comment by beats-dh** [comment]
> ultimate healing runes and intense healing runes can heal monsters

any news?

**Comment by travisani** [comment]
I tryied to fix with this in a test server and no works

**Comment by Beats-Dh** [comment]
> I tryied to fix with this in a test server and no works

@ArturKnopik

**Comment by travisani** [comment]
later i will try to solve this too, im at work now.

**Comment by beats-dh** [comment]
> later i will try to solve this too, im at work now.

Call me on Discord: Beats#5410

**Comment by travisani** [comment]
Solved like a tibia global opentibiabr/otservbr-global#2633 opentibiabr/otservbr-global#2632
