### ISSUE TITLE
BUG: Off-hand items like Moon Mirror/Shining Sun Catcher protection bonus not working

### ISSUE THREAD

**Issue by Fernandoijui** [opentibiabr/otservbr-global#2593]
Off-hand items like Moon Mirror, Shining Sun Catcher, Bone Fiddle and all the others display their protection bonus but the bonus is not being applied to the character.

I made some testing first by equip the items in the character slot and then check the Character Stats on the Cyclopedia, the protection of all gear is listed there, but any off-hand item that I had equipped didnt add it's protection bonus to the list. In the print bellow we can see it show the bonus from butterfly ring and foxtail amulet, but nothing else.

![image](https://user-images.githubusercontent.com/84390290/118656047-86e9b880-b7c0-11eb-95b7-cb8f530bdd03.png)

Besides that, I also test every off-hand item by dealing the damage types it should be protecting us, the result was the same, Moon Mirror, Sun Catcher, etc didnt reduce any dmg taken.

Appreciate any help guys, have a nice week!

**Comment by MajestyOTBR** [comment]
Who let close the issue? The issue tracker is not a support forum to solve problems and close the issue.
