### ISSUE TITLE
BUG: most of protocolgame.cpp code crash server

### ISSUE THREAD

**Issue by gesior** [opentibiabr/otservbr-global#261]
I just get report about crash from someone on Discord. I think I found reason of it.

OTS multithreading is super simple:
- pass everything to 'dispatcher thread', 'dispatcher' executes one task at once = there is no multithreading problem
- only thing that is not executed in dispatcher thread is 'network packets decrypting and parsing'

#### How to Reproduce?
Run server. Get players. Wait for random crash.

#### Logs or errors
GDB:
```
#0  0x000055ac35bb6e77 in OutputMessage::append(NetworkMessage const&) ()
No symbol table info available.
opentibiabr/otservbr-global#1  0x000055ac35bbb027 in ProtocolGame::writeToOutputBuffer(NetworkMessage const&) ()
No symbol table info available.
opentibiabr/otservbr-global#2  0x000055ac35bca652 in ProtocolGame::sendResourceBalance(Resource_t, unsigned long) ()
No symbol table info available.
opentibiabr/otservbr-global#3  0x000055ac35bca597 in ProtocolGame::sendResourcesBalance(unsigned long, unsigned long, unsigned long) ()
No symbol table info available.
opentibiabr/otservbr-global#4  0x000055ac35bcb270 in ProtocolGame::sendMarketEnter(unsigned int) ()
No symbol table info available.
opentibiabr/otservbr-global#5  0x000055ac35922233 in Player::sendMarketEnter(unsigned int) ()
No symbol table info available.
opentibiabr/otservbr-global#6  0x000055ac35bc470d in ProtocolGame::parseMarketBrowse(NetworkMessage&) ()
No symbol table info available.
opentibiabr/otservbr-global#7  0x000055ac35bbc733 in ProtocolGame::parsePacket(NetworkMessage&) ()
No symbol table info available.
opentibiabr/otservbr-global#8  0x000055ac35bb6066 in Protocol::onRecvMessage(NetworkMessage&) ()
No symbol table info available.
opentibiabr/otservbr-global#9  0x000055ac35ba73d7 in Connection::parsePacket(boost::system::error_code const&) ()
No symbol table info available.
```

Probably 2 threads tried to send packet in same time. They both modified OutputMessage in same time, which result in crash.

#### Expected behavior
'Parse' functions should not execute functions on 'player' (like 'sendMarketEnter'). They should just get data from network packet and pass it to 'dispatcher thread' as 'Task'.

**Comment by Costallat** [comment]
Thanks!

No problem, one step at a time, we don't need the code from the "Masters of the Universe", we just need to share the fixes, so we can make it worker and later we can refactor things to improve it
