### ISSUE TITLE
BUG: Server crash when remove monster from charm

### ISSUE THREAD

**Issue by lichak232** [opentibiabr/otservbr-global#2657]
Describe the bug
> While removing monster from charm

How to Reproduce?
> It's hard to repeat

Give us all details to reproduce the behavior:
> Remove monster from charm
> It's hard to repeat!
> Need a lot players online

Logs or errors
> https://pastebin.com/VUJpHeaP

Expected behavior
> Server crash

Environment
> OS (Debian 10):
> OTServ Version (latest):
> Tibia Version (12.64):
Additional context
> It's clear and latest version, without any changes.

**Comment by beats-dh** [comment]
It's with develop without modifications, now right?

**Comment by lichak232** [comment]
> It's with develop without modifications, now right?

YES

**Comment by gccris** [comment]
I tried here and nothing happened. Any charm specific?

**Comment by yatozin** [comment]
> I tried here and nothing happened. Any charm specific?

it happens randomly, its hard to reproduce :s

**Comment by aokisama** [comment]
Looks like they talked about it here https://github.com/opentibiabr/otservbr-global/issues/2467 but it never got looked at again.

**Comment by Zapotoczny** [comment]
Has anyone managed to fix it? I have the same problem?
It's only happens when are some more players online. When click remove then crash server

**Comment by Zapotoczny** [comment]
I spent some money to fix this error, if someone needs help, please visit dsc Zapo #8085

**Comment by majestyotbr** [comment]
If someone have the fix, contribute it here. It's not allowed messages to contact in private.

**Comment by Bipbop69** [comment]
i'm having the same problem but can't reproduce the error to fix

**Comment by lichak232** [comment]
> i'm having the same problem but can't reproduce the error to fix

I made a lua script to remove monsters from charms and blocked the option to remove in cyclopedia

**Comment by Bipbop69** [comment]
> > i'm having the same problem but can't reproduce the error to fix
> 
> I made a lua script to remove monsters from charms and blocked the option to remove in cyclopedia

and could this release?
