### ISSUE TITLE
Inquisition map bug

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/OTServBR-Global#268]
Blood Hall teleport not bringing player back to the retreat.

The following teleport 
22:12 You see a magic forcefield.
You can see the other side through it.
Item ID: 1387
Position: 33372, 31614, 14

should be teleporting player to 
22:17 You see stone floor.
Item ID: 3152
Position: 33165, 31709, 14

**Comment by Raphaellb** [comment]
@eduardodantas95 I am working on all quest. once all map bugs are detected, I will remove (WIP) tag.

**Comment by Raphaellb** [comment]
I completed the quest, as far as I can tell, this is the only map bug I found.

**Comment by EPuncker** [comment]
please test/check it after PR #294 get merged
