### ISSUE TITLE
Alguns map/spawn bugs

### ISSUE THREAD

**Issue by EPuncker** [opentibiabr/OTServBR-Global#270]
**Describe the bug**
- [x] Esse cyc não deveria estar aqui {x = 32726, y = 31332, z = 7}, neste térreo existem apenas minotaurs comuns
- [x] Faltando um minotaur mage aqui {x = 32745, y = 31307, z = 8}
- [x] Falta um Squirrel aqui {x = 32828, y = 31226, z = 7}
- [x] Faltam 2 ou 3 Pirates Cutthroat aqui {x = 32658, y = 31317, z = 7}
- [x] Falta o texto nessa nota {x = 32357, y = 32212, z = 7} (Your gods need YOU!
Join the holy Inquisition to fight the enemies of your gods and your country!
Contact Henricus in the Inquisiton quarters beneath the Thaian jail!)
- [x] Falta[ sangue na parede e o texto](https://i.imgur.com/ZkHFNlK.jpg) na nota em {x = 32965, y = 32104, z = 6}
- [x] Faltando 2 blueberry bushes (dos q dão a fruta) na entrada de thais ([imagem](https://i.imgur.com/mPWTnQJ.jpg))
- [x] Faltam essas folhas e vassoura no templo de thais: [imagem](https://i.imgur.com/6XaCrYj.jpg)
- [x] Essa placa na parede em {x = 32364, y = 32212, z = 7} não deveria estar ali
- [x] [Placas corretas](https://i.imgur.com/PRlLWQR.jpg)
- [x] Remover npc cassino {x = 32354, y = 32226, z = 7}  e seus respectivos arquivos
- [x]  Faltando memorial do golden outfit em Thais na posição {x = 32377, y = 32205, z = 7} ([foto para referencia](https://i.imgur.com/gNtoSKZ.jpg))
- [x]  Faltando memorial do golden outfit em Yalahar na posição {x = 32797, y = 31244, z = 7}  ([foto para referencia](https://i.imgur.com/FV1zxuL.jpg))
- [x]  Faltando memorial do golden outfit em liberty bay na posição {x = 32345, y = 32844, z = 7}  ([foto para referencia](https://i.imgur.com/lW3uyMR.jpg))
- [x]  Faltando memorial do golden outfit em edron na posição {x = 33175, y = 31831, z = 7}  ([foto para referencia](https://i.imgur.com/KWRVVMB.jpg))
- [x]  Faltando memorial do golden outfit em carlin na posição {x = 32347, y = 31772, z = 7}  ([foto para referencia](https://i.imgur.com/xP7DYZj.jpg))
- [x]  Faltando memorial do golden outfit em darashia na posição {x = 33207, y = 32459, z = 7}  ([foto para referencia](https://i.imgur.com/C8SXUn0.jpg))
- [x]  Faltando memorial do golden outfit em Rathleton mas sou noob e não consegui ir lá kk
- [x]  O guia de darashia é para estar aqui {x = 33289, y = 32469, z = 7} e não em cima do barco
- [x]  O guia de carlin é para estar aqui {x = 32381, y = 31811, z = 7} e não em cima do barco
- [x]  Faltando NPC Edgar-Ellen em thais na posição {x = 32367, y = 32189, z = 7}
- [x] não tem esses 2 gang member aqui {x = 32725, y = 31301, z = 7} não é pra ter nada
- [x] aqui {x = 32730, y = 31303, z = 7} aqui falta 1 smuggler e 1 cat
- [x] exercise dummy de yalahar faltando em {x = 32780, y = 31251, z = 5}
- [x] falta uma giant spider aqui {x = 32601, y = 32250, z = 8}
- [x] descobrir oq ta escrito nesta placa
- [x] faltam 2 wyvern aqui {x = 33220, y = 31650, z = 6}
- [x] extender um pouco essa cave para evitar do jogador ver área preta do mapa {x = 33293, y = 31914, z = 9} ([aqui](https://i.imgur.com/SibpBYk.jpg)) e aqui {x = 33227, y = 31838, z = 9} ([imagem2](https://i.imgur.com/Qb2aXDo.jpg))
- [x] remover data/world/globalbr-house.xml data/world/globalbr-spawn.xml data/world/globalbr.otbm do arquivo gitignore
- [x] NPC Guide Elena em venore é pra ficar parada em 32952, 32030, 6 sem se mexer
- [x] Verificar no tibia se aqui ({x = 32605, y = 31924, z = 11}) tem 4 casas e caso sim, add elas

**Comment by gpedro** [comment]
> deixar o arquivo de houses e spawns fora para podermos fazer esses mudanças pequenas mais facilmente.

concordo. faz muito sentido inclusive!!
