### ISSUE TITLE
[Bug]: Demon beams

### ISSUE THREAD

**Issue by andrefusk** [opentibiabr/otservbr-global#2715]
### What happened?

The demons are using a big energy wave instead of the beam

### How to Reproduce?

Just summon a demon and see its attacks, it has no beam but an energy wave

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Schiffers** [comment]
https://github.com/opentibiabr/otservbr-global/pull/2716#issue-727270983
Some beams are wrong due the monsters converter change spread 0 to 3 ... 
So may have anothers Monsters with this issue..
 If you find another you can make a pr or comments.
