### ISSUE TITLE
ENHANCEMENT: Confirmation before selling items imbued in npcs

### ISSUE THREAD

**Issue by LeeoMacedo** [opentibiabr/otservbr-global#286]
as you can see in the image below, i have a noble ax imbued, and it is appearing for sale at npc.

![image](https://user-images.githubusercontent.com/34727091/115127750-60611380-9faf-11eb-90eb-6cd9d0fa111a.png)

**Comment by dudantas** [comment]
This issue has already been fixed in the canary/otbr compatibility pr
