### ISSUE TITLE
MAP: Missin Spawn -> Tainted Caves

### ISSUE THREAD

**Issue by imranhhk** [opentibiabr/otservbr-global#295]
https://tibia.fandom.com/wiki/Tainted_Caves
https://tibiamaps.io/map#32709,31939,7:1

**Comment by majestyotbr** [comment]
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
Thanks to @guispiller for the map contribution.
