### ISSUE TITLE
BUG: exercise training

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global#305]
How to make the bug.
Choose a training weapon let's use the example rod
choose the dummy leave attacking.
now press ctrl + g and choose the same character.
your character will log out and return will continue training the same with ctrl + q 

doing this over and over again will notice that the weapon charges will decrease with greater speed.

test done with latest version of git

**Comment by dudantas** [comment]
Fixed in the commit: https://github.com/opentibiabr/otservbr-global-archived/commit/a8aac86f78227d3616b14866416678aefc5ecd42
