### ISSUE TITLE
FEATURE: action pra liberar todos os charms

### ISSUE THREAD

**Issue by andrefusk** [opentibiabr/otservbr-global#307]
#### Describe your feature request
> A clear and concise description of what the request is about. Ex. I'm always frustrated when [...]

Fazer uma action pra abrir todas as charms, tipo a das quests, pra testar e pra quem só quer relaxar

#### Describe the solution you'd like
> A clear and concise description of what you expected to happen.

#### Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

#### Links
> If applicable, add links to help explain how this feature works.

#### Screenshots
> If applicable, add screenshots to help explain your feature request

#### Additional context
> Add any other context about the problem here.

**Comment by dudantas** [comment]
Isso não é feature. E já tem a talkaction para adicionar os charms.
