### ISSUE TITLE
Exercising Training on Store

### ISSUE THREAD

**Issue by reeizor** [opentibiabr/OTServBR-Global#309]
The exercise weapons are working normally, with 500 cartoons as stipulated. When creating items using the / i command the items work perfectly. However, when placing the Exercises Weapons in the Store, after purchase the item receives only 1 charge.

- gamestore.lua
![image](https://user-images.githubusercontent.com/53309738/61889117-34e4ee00-aedb-11e9-8cdc-4deeb171cbc8.png)

- items.xml
![image](https://user-images.githubusercontent.com/53309738/61889266-82f9f180-aedb-11e9-8954-bbe0be018524.png)
- In game

![image](https://user-images.githubusercontent.com/53309738/61889470-da985d00-aedb-11e9-9218-1a81ef743c93.png)

**Comment by EPuncker** [comment]
> count = 1,

???

**Comment by reeizor** [comment]
Count is how many exercise weapon.. I mean Charges.. it is 1 charge, even with the scripts telling 10 on Value..

**Comment by EPuncker** [comment]
if you have tried with count 500 and it not worked, then we need to fix it to add a charge stats to store

**Comment by reeizor** [comment]
Oh, that's it.. It's hard to do? someone that got no experience in scripts can do it?

**Comment by rickorion** [comment]
Here i use "**type = GameStore.OfferTypes.OFFER_TYPE_STACKABLE**" but with that i get a parcel, with alot o weapons with 100 charges.. so i changed this line in init.lua file: **elseif (offerCount > 100) then** 
 **to elseif (offerCount > 500) then** and now i get only one weapon with 500 charges. Maybe work for you... Maybe not

**Comment by reeizor** [comment]
it worked. Thank you very much!

**Comment by oualid6496** [comment]
but then this will happen to all stackable items that you buy through the store instead of getting charges of 100 you will be able to get them in 500
