### ISSUE TITLE
[Bug]: Bestiary de Silencer estágio 3 bugado

### ISSUE THREAD

**Issue by andrefusk** [opentibiabr/otservbr-global#309]
### What happened?

No bestiario do silencer, se botar o mouse na 3a barra, falta 100 na vez de 1000, outros bixos de 3 estrelas precisa de 1000, então é um typo do silencer

### How to Reproduce?

botar o mouse na 3a barra, falta 100 na vez de 1000

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sh3Ns** [comment]
![Sem título](https://user-images.githubusercontent.com/50599143/140239087-f299be14-5b7f-44a6-b16b-fed2f9ff87e4.png)
Feito teste.
Windows 10

**Comment by Sh3Ns** [comment]
![image](https://user-images.githubusercontent.com/50599143/149625998-09144d5c-e195-4b8f-a350-685c9e1f2299.png)

bug found after change.
