### ISSUE TITLE
[Bug]: The magic: Bruise Bane (exura infir ico) does not work for Knight.

### ISSUE THREAD

**Issue by Nilvagner** [opentibiabr/otservbr-global#315]
### What happened?

The magic: Bruise Bane
(exura infir ico) does not work for Knight.

### How to Reproduce?

The magic: Bruise Bane
(exura infir ico) does not work for Knight.

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sh3Ns** [comment]
Opa eu testei aqui funciona normal.
Windows 10
12.x (Default)

**Comment by majestyotbr** [comment]
The spell Bruise Bane (exura infir ico) work for Knight. 
Version: 12.x (Default).
OS: Windows 10.
