### ISSUE TITLE
[Bug]: Healing paralyze should be instant.

### ISSUE THREAD

**Issue by gg-martins091** [opentibiabr/otservbr-global#319]
### What happened?

On global tibia, when you get paralyzed and cast any haste spell (utani hur, utani gran hur, etc.) or healing spell (exura, exura gran, etc.) the paralyzed condition gets removed instantly, even if you are on your walk delay after walking diagonally (you still get the walk delay, but the condition itself gets removed instantly).

This is relevant because the way it works on theese sources is that the paralyze condition gets removed after your carachetr's walkdelay or actiondelay. And this, in some cases, can cause the paralyze condition to not be removed before your character can do another action (this means that it is possible for you to be paralyzed, heal, walk and still be paralyzed).

PS. When you walk diagonally while under a paralyze condition on global tibia, you get a huge delay for your next action **but not for removing the paralyze condition.**

### How to Reproduce?

Log into 2 characeters (1 of them must be a druid) and then:

1 - Use a paralyze rune on one of the characters
2 - walk diagonally (with the paralyzed character) and heal at the same time (utani hur or exura) (heal before your diagonal walk animation ends)
3 - you will see that the paralyze condition only gets removed after you are able to walk again.

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04, Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Solved on PR #320
