### ISSUE TITLE
[Bug]: Oramond City

### ISSUE THREAD

**Issue by jaysonoliiveira** [opentibiabr/otservbr-global#322]
### What happened?

bom os meus teste foi com uma conta ADM e uma conta PLAYER normal, vou explica o debug

"QUERO TAMBEM RESALTAR QUE O TESTE QUE FIZ COM O ADM ELE NAO TOMA DEBUG"

ESSE DEBUG SO CAUSA COM O PLAYER NORMAL, MAIS SE O ADM TIVER PERTO DO PLAYER E O PLAYER TOMA O DEBUG O ADM TOMA TAMBEM MAIS SE O ADM TIVER SOZINHO NA AREA ELE NAO TOMA DEBUG.

o cara vai na cidade de Oramond e vai ate os Rustheap Golem quando o player fica andando por lá próximo aos Rustheap Golem simplesmente da debug...

fiz o teste removendo os monstros da área no local e continuou os debug.

### How to Reproduce?

bom nao tem exatamente uma position X que defina esse debug ou seja é exatamente em uma AREA X que causa o debug mais a position da area é essa >> Position: 33647, 31973, 7

### Relevant log output

```shell
não mostra nenhum erro no console.
```

### Attach any relevant file

![ASAS](https://user-images.githubusercontent.com/92376578/139725259-2ee420d3-6caf-43fb-9815-4a9dcff4de0a.png)

ESSE É A A REA QUE DA O DEBUG

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sh3Ns** [comment]
Opa eu testei com player normal , não deu debug pra min , Hummmm....
Testado no Windows 10.

**Comment by dudantas** [comment]
It doesn't check, there's no problem.
