### ISSUE TITLE
[Bug]:  [ProtocolGame::onRecvFirstMessage] - RSA Decrypt Failed

### ISSUE THREAD

**Issue by Szmycu** [opentibiabr/otservbr-global#329]
### What happened?

I see warning in console  what to do with that? It shows even when im not connecting to game with cllient 

### How to Reproduce?

[warning] [ProtocolGame::onRecvFirstMessage] - RSA Decrypt Failed 

### Relevant log output

```shell
[warning] [ProtocolGame::onRecvFirstMessage] - RSA Decrypt Failed
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Costallat** [comment]
Nothing, this is just a warning showing that something tried to connect and didn't used the right 'key'.

**Comment by majestyotbr** [comment]
Is a ghost client trying to connect?

**Comment by Szmycu** [comment]
if no one connecting and it gives this warning too.  good if it is not disrupt anything

**Comment by dudantas** [comment]
> if no one connecting and it gives this warning too. good if it is not disrupt anything

![image](https://user-images.githubusercontent.com/8551443/142469129-4d8e86b7-77b5-44ac-aa15-d7b90d39721c.png)
This message only occurs when you try to log in (in the first message) with a different rsa than open tibia's rsa, your report doesn't make sense, it's not a server bug, it's some error of yours.
