### ISSUE TITLE
[Bug]: familiars creaturescripts 'vocation' nil value

### ISSUE THREAD

**Issue by garedgar** [opentibiabr/otservbr-global#332]
### What happened?

[2021-27-11 22:50:55.001] [error] Lua script error: C:\oblivion_server\Server\data\scripts\creaturescripts\others\familiars.lua:callback
[2021-27-11 22:50:55.002] [error] ...Server\data\scripts\creaturescripts\others\familiars.lua:90: attempt to index local 'vocation' (a nil value)
stack traceback:
        [C]: in function '__index'
        ...Server\data\scripts\creaturescripts\others\familiars.lua:90: in function <...Server\data\scripts\creaturescripts\others\familiars.lua:86>

![familiars1](https://user-images.githubusercontent.com/49217978/143723175-c3207d61-289b-44e7-a4c2-a93aac827e6a.png)

![familiars2](https://user-images.githubusercontent.com/49217978/143723179-538722f4-6234-4071-85ba-a5f34910b172.png)

### How to Reproduce?

Compile to latest version, and startup server, this happens randomly. I still have not managed to pin point whenit does it.  But sometimes my console is spammed with these errors.

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dex-89** [comment]
Do you have a set vocation and a minimum of 200 lvl?

**Comment by Kawkawka250123** [comment]
Go to ~/data/lib/tables/vocation.lua

and paste this


```
VOCATION = {
    ID = {
        NONE = 0,
        SORCERER = 1,
        DRUID = 2,
        PALADIN = 3,
        KNIGHT = 4,
        MASTER_SORCERER = 5,
        ELDER_DRUID = 6,
        ROYAL_PALADIN = 7,
        ELITE_KNIGHT = 8
    },
    CLIENT_ID = {
        NONE = 0,
        KNIGHT = 1,
        PALADIN = 2,
        SORCERER = 3,
        DRUID = 4
    },
    BASE_ID = {
        NONE = 0,
        SORCERER= 1,
        DRUID= 2,
        PALADIN= 3,
        KNIGHT= 4
    }
}
```

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/blob/main/data/lib/tables/vocation.lua
