### ISSUE TITLE
New imbument system fails compile

### ISSUE THREAD

**Issue by Szmycu** [opentibiabr/otservbr-global#340]
### What happened?

/home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.cpp: In member function ‘std::v
ector<Imbuement*> Imbuements::getImbuements(const Player*, Item*)’:
/home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.cpp:372:55: error: cannot conve
rt ‘std::tuple_element<1, std::pair<const unsigned int, Imbuement> >::type’ {aka ‘Imbuement’} to ‘int32_t&’ {aka ‘i
nt&’}
  372 |   && player->getStorageValue(imbuement->getStorage(), value)
      |                                                       ^~~~~
      |                                                       |
      |                                                       std::tuple_element<1, std::pair<const unsigned int, I
mbuement> >::type {aka Imbuement}
In file included from /home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.h:12,
                 from /home/mariankowalczysty/otservbr-global/src/lua/creature/events.h:23,
                 from /home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.cpp:21:
/home/mariankowalczysty/otservbr-global/src/creatures/players/player.h:514:53: note:   initializing argument 2 of ‘
bool Player::getStorageValue(uint32_t, int32_t&) const’
  514 |   bool getStorageValue(const uint32_t key, int32_t& value) const;
      |                                            ~~~~~~~~~^~~~~
/home/mariankowalczysty/otservbr-global/src/items/item.cpp: In member function ‘bool Item::getImbuementInfo(uint8_t
, ImbuementInfo*)’:
/home/mariankowalczysty/otservbr-global/src/items/item.cpp:99:72: error: ‘IMBUEMENT_SLOT’ was not declared in this 
scope; did you mean ‘IMBUEMENT_NONE’?
   99 |  const ItemAttributes::CustomAttribute* attribute = getCustomAttribute(IMBUEMENT_SLOT + slot);
      |                                                                        ^~~~~~~~~~~~~~
      |                                                                        IMBUEMENT_NONE
/home/mariankowalczysty/otservbr-global/src/items/item.cpp: In member function ‘void Item::setImbuement(uint8_t, ui
nt16_t, int32_t)’:
/home/mariankowalczysty/otservbr-global/src/items/item.cpp:108:53: error: ‘IMBUEMENT_SLOT’ was not declared in this
 scope; did you mean ‘IMBUEMENT_NONE’?
  108 |  std::string key = boost::lexical_cast<std::string>(IMBUEMENT_SLOT + slot);
      |                                                     ^~~~~~~~~~~~~~

### How to Reproduce?

when compiling

### Relevant log output

```shell
/home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.cpp: In member function ‘std::v
ector<Imbuement*> Imbuements::getImbuements(const Player*, Item*)’:
/home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.cpp:372:55: error: cannot conve
rt ‘std::tuple_element<1, std::pair<const unsigned int, Imbuement> >::type’ {aka ‘Imbuement’} to ‘int32_t&’ {aka ‘i
nt&’}
  372 |   && player->getStorageValue(imbuement->getStorage(), value)
      |                                                       ^~~~~
      |                                                       |
      |                                                       std::tuple_element<1, std::pair<const unsigned int, I
mbuement> >::type {aka Imbuement}
In file included from /home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.h:12,
                 from /home/mariankowalczysty/otservbr-global/src/lua/creature/events.h:23,
                 from /home/mariankowalczysty/otservbr-global/src/creatures/players/imbuements/imbuements.cpp:21:
/home/mariankowalczysty/otservbr-global/src/creatures/players/player.h:514:53: note:   initializing argument 2 of ‘
bool Player::getStorageValue(uint32_t, int32_t&) const’
  514 |   bool getStorageValue(const uint32_t key, int32_t& value) const;
      |                                            ~~~~~~~~~^~~~~
/home/mariankowalczysty/otservbr-global/src/items/item.cpp: In member function ‘bool Item::getImbuementInfo(uint8_t
, ImbuementInfo*)’:
/home/mariankowalczysty/otservbr-global/src/items/item.cpp:99:72: error: ‘IMBUEMENT_SLOT’ was not declared in this 
scope; did you mean ‘IMBUEMENT_NONE’?
   99 |  const ItemAttributes::CustomAttribute* attribute = getCustomAttribute(IMBUEMENT_SLOT + slot);
      |                                                                        ^~~~~~~~~~~~~~
      |                                                                        IMBUEMENT_NONE
/home/mariankowalczysty/otservbr-global/src/items/item.cpp: In member function ‘void Item::setImbuement(uint8_t, ui
nt16_t, int32_t)’:
/home/mariankowalczysty/otservbr-global/src/items/item.cpp:108:53: error: ‘IMBUEMENT_SLOT’ was not declared in this
 scope; did you mean ‘IMBUEMENT_NONE’?
  108 |  std::string key = boost::lexical_cast<std::string>(IMBUEMENT_SLOT + slot);
      |                                                     ^~~~~~~~~~~~~~
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
The pull request of the imbuement system **is not ready yet**. If you are testing pull requests, you can comment there.

**Comment by dudantas** [comment]
@Szmycu you dont' need to open an issue, you just comment on the pull request. I use windows so I didn't even notice the compilation broke on linux. I'll send the correction right away.

#Edit
Fixed, try again.
