### ISSUE TITLE
[Bug]: Vocation Familiars attacking players even if secure mode is on

### ISSUE THREAD

**Issue by CharlySample** [opentibiabr/otservbr-global#346]
### What happened?

Example: You are a Paladin and you summon your familiar, and the when you attack something the spells of your familiar will hit other people even you have pvp off.

### How to Reproduce?

Just summon a paladin familiar, put another character near a monster and then attack the monster.

### Version

12.x (Default)
![Untitled](https://user-images.githubusercontent.com/42224271/145142643-ef5a8a24-fed6-4bfe-941c-c0a5a136b36a.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beats-dh** [comment]
Do you get pz?

**Comment by CharlySample** [comment]
> Do you get pz?

Nope

**Comment by Nyedson** [comment]
Well, i tried something here.
Don't know if is 100% solved, of course.
in data/events/scripts/creature.lua
inside the function Creature:onTargetCombat(target) and above self:addEventStamina(target) i put this:

	local master = self:getMaster()
	if master and target:isPlayer() then
		if not master:isPzLocked() then
			return RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER
		end
	end

in my tests it worked, but maybe I forgot something

**Comment by CharlySample** [comment]
> Well, i tried something here. Don't know if is 100% solved, of course. in data/events/scripts/creature.lua inside the function Creature:onTargetCombat(target) and above self:addEventStamina(target) i put this:
> 
> ```
> local master = self:getMaster()
> if master and target:isPlayer() then
> 	if not master:isPzLocked() then
> 		return RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER
> 	end
> end
> ```
> 
> in my tests it worked, but maybe I forgot something

i'ts working very good sir :), thank you

**Comment by beats-dh** [comment]
https://user-images.githubusercontent.com/61994374/183801067-7c3687a1-55d8-4f7b-afb4-3cc4f5add09f.mp4
