### ISSUE TITLE
CONTENT: Wrath of the Emperor Quest

### ISSUE THREAD

**Issue by Alissonlv123** [opentibiabr/otservbr-global#348]
Wrath of the Emperor Quest esta bugada o npc zizzle não entrega o snake spectre eo npc A Sleeping Dragon não deixa o player passar pelo portão pra continua a quest

**Comment by dudantas** [comment]
Você precisa dar mais informações. Não entrega por que? O que acontece? Adiciona prints ao issue. A sleeping dragon responde o que? Não dá para eu testar a quest inteira só para descobrir onde exatamente tá o problema. Se você anexar mais detalhes, eu descubro mais facilmente.

**Comment by Alissonlv123** [comment]
vou mandar umas prints

**Comment by Alissonlv123** [comment]
![tibia](https://user-images.githubusercontent.com/68012933/145672641-84fcd76a-19f1-4c33-b6b2-5a319e6bca97.png)
aqui a gente pede a missão ele não entrega o item Snake Sceptre para continuar a missão
![Tibia 2](https://user-images.githubusercontent.com/68012933/145672675-cc5dfb19-bf58-464d-93bb-918489977874.png)
aqui a gente fala hi para o dragão ele diz essa palavra e mais nada mesmo que eu tente falar mission e todas palavras que pede na quest ele diz só isso
![TIBIA 3](https://user-images.githubusercontent.com/68012933/145672693-849ccfb5-f760-4b36-930b-d83ec9a43f75.png)
aqui como pode ver falei a palavra SOLOSARASATIQUARIUM e ele não me respondeu e não me deu a permissão pra entrar e eu ja tomei a poção que pede pra fala com ele mais mesmo não me da a permissão
![tibia 4](https://user-images.githubusercontent.com/68012933/145672715-04c04be1-83ce-4f22-b100-afb28480435e.png)
aqui eu estou tentando entrar no portão e tou sendo puxado novamente pra fora

**Comment by rigis1** [comment]
fixed
