### ISSUE TITLE
[Bug]: Able to pickup an unmovable item with aid 100

### ISSUE THREAD

**Issue by joelslamospersson** [opentibiabr/otservbr-global#359]
### What happened?

Soo, picture time..
Here, the 3 gold coins had a rune. That rune had aid 100. While using it and backing up made it possible for me to pick the item up which in this case has an aid 100 (Unmovable id).
https://i.gyazo.com/2f37367867fb8633cddc7cb3df9345b5.jpg

This was fixed by this:
https://github.com/otland/forgottenserver/pull/2834
https://github.com/otland/forgottenserver/pull/3609

### How to Reproduce?

aid: 100
Checked events, both onMoveItem and onTradeItem = 1
Solved this in the discord.

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
This doesn't seem to be an issue anymore, please update your source and datapack. 
If the issue persists to you, please contact me.
