### ISSUE TITLE
attempt to call method 'setReward' (a nil value) 

### ISSUE THREAD

**Issue by gpedro** [opentibiabr/OTServBR-Global#36]
```
Lua Script Error: [Raid Interface]
data/raids/scripts/mawhawk.lua:onRaid
data/raids/scripts/mawhawk.lua:4: attempt to call method 'setReward' (a nil value)
stack traceback:
[C]: in function 'setReward'
data/raids/scripts/mawhawk.lua:4: in function <data/raids/scripts/mawhawk.lua:1>

Lua Script Error: [Raid Interface]
data/raids/scripts/mad_mage.lua:onRaid
data/raids/scripts/mad_mage.lua:4: attempt to call method 'setReward' (a nil value)
stack traceback:
[C]: in function 'setReward'
data/raids/scripts/mad_mage.lua:4: in function <data/raids/scripts/mad_mage.lua:1>
```

**Comment by LucasCPrazeres** [comment]
@gpedro Com que frequência aparece esse erro?

**Comment by gpedro** [comment]
@LucasCPrazeres isso é um bug do reward, parece que os scripts das raids não carregam os scripts globals como `setReward`.
Vai até os MadMage e da start manual, qndo vc mata ele dá como se não existisse essa função.

**Comment by LucasCPrazeres** [comment]
Testei agora, parece que ta indo normal
12:51 The following items are available in your reward chest: 74 gold coins, 100 gold coins, 4 platinum coins, 5 strong mana potions, a strong health potion, a mind stone, a stealth ring, a piggy bank.
Vou ver se com a raid automática vai dar esse erro.

**Comment by gpedro** [comment]
vou baixar aqui e testar novamente.

**Comment by Sleet37** [comment]
This bug also extends to the Orshabaal raid on the latest build of the 'develop' branch.
Just compiled it on Ubuntu 18.04 to test it.

`Lua Script Error: [Raid Interface]                                                                                                                                                                                                        data/raids/scripts/orshabaal.lua:onRaid                                                                                                                                                                                                   data/raids/scripts/orshabaal.lua:4: attempt to call method 'setReward' (a nil value)                                                                                                                                                      stack traceback:                                                                                                                                                                                                                                  [C]: in function 'setReward'                                                                                                                                                                                                              data/raids/scripts/orshabaal.lua:4: in function <data/raids/scripts/orshabaal.lua:1>`

I am guessing it also extends to the other raids.

**Comment by Sleet37** [comment]
This is an update on the issue.

This bug will only occur when a "raid name".xml file calls for a lua script.

Whoever wrote this script thought that the setReward() method was already predefined in this script. However, since it is being called from a .xml file, it will not be loaded alongside the global functions from the lib folder.

Since the setReward() method [is already called when a monster is spawned](https://github.com/opentibiabr/OTServBR-Global/blob/53f0d20/data/events/scripts/monster.lua#L71) and since all of these lua scripts do what could have been done in the .xml files, I suggest simply removing these lua scripts and appending the working code to the .xml files.
