### ISSUE TITLE
[Bug]: Killing in the name of BUG

### ISSUE THREAD

**Issue by gabrielblanchett24** [opentibiabr/otservbr-global#361]
### What happened?

When a player ask for example to start Trolls task player get automatically Necromancer & Priestess task and if a player kills 1 troll the Necromancer & Priestess task count goes up but the Troll count keeps on 0. 
Also if player ask for Goblins tasks u get Minotaurs task instead (pretty sure some other tasks are wrong?)

### How to Reproduce?

Just ask Grizzly Adams for a task, and ask for Trolls tasks then for goblins tasks and u'll get another tasks instead of what player asked for

### Attach any relevant file

![127 0 0 1_client_57pbjRSxKU](https://user-images.githubusercontent.com/52180467/146809969-aef47bc9-5e40-4b93-bbe4-2ff95856c733.png)
![127 0 0 1_client_5jyw1C3FXG](https://user-images.githubusercontent.com/52180467/146809978-0dbd97b9-e40a-4460-bbe0-48bd14a7fe6c.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andersonfaaria** [comment]
most likely the storage is wrong

**Comment by rigis1** [comment]
fixed
