### ISSUE TITLE
[Bug]: hireling food

### ISSUE THREAD

**Issue by Slec** [opentibiabr/otservbr-global#369]
### What happened?

When o buy food from hireling and try to put it on my depot it doenst work.

This is relevant because those items are cap consuming and they came in a high amount to the char since the player buys tons of it by random until gets the one food they want. You cant consume the foods cause there is a cd, so the only way to free that cap is putting the foods you dont want in the depot (like in global tibia)

### How to Reproduce?

1 - get a hireling
2 - buy food
3 - try to put it on depot

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
> ### What happened?
> When o buy food from hireling and try to put it on my depot it doenst work.
> 
> This is relevant because those items are cap consuming and they came in a high amount to the char since the player buys tons of it by random until gets the one food they want. You cant consume the foods cause there is a cd, so the only way to free that cap is putting the foods you dont want in the depot (like in global tibia)
> 
> ### How to Reproduce?
> 1 - get a hireling 2 - buy food 3 - try to put it on depot
> 
> ### Relevant log output
> _No response_
> 
> ### Attach any relevant file
> _No response_
> 
> ### Version
> 12.x (Default)
> 
> ### What OS are you seeing the problem on?
> Windows 10
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

I tried to understand what you meant and I swear I couldn't. Try taking screenshots or recording a gif or I will close the issue.

**Comment by Slec** [comment]
Vou falar em portugues então.
No tibia voce tem os hirelings (npc q compra na store para colocar em casas), certo?
Voce pode dar upgrade na profissao do hireling. 
Uma das profissoes ele vira cozinheiro e te da a opcao de comprar comida dele, certo?
Acontece que: voce fala hi -> food -> yes e o npc manda uma comida aleatoria para o seu personage, mas não manda para a backpack, manda para a aba especial de itens de store, certo? Até ai tudo bem

O problema esta aqui: você tinha que ser capaz de pegar essa food e colocar ela dentro do depot.

E tem uma razao para isso: 
porque se você nao consegue colocar  no depot o seu personagem vai ficar lotado de cap rapidinho,porque até chegar na food que voce quer no npc, vai ter vqrias outras aleatorias antes que vao pesar no seu personagem

**Comment by dudantas** [comment]
> Vou falar em portugues então. No tibia voce tem os hirelings (npc q compra na store para colocar em casas), certo? Voce pode dar upgrade na profissao do hireling. Uma das profissoes ele vira cozinheiro e te da a opcao de comprar comida dele, certo? Acontece que: voce fala hi -> food -> yes e o npc manda uma comida aleatoria para o seu personage, mas não manda para a backpack, manda para a aba especial de itens de store, certo? Até ai tudo bem
> 
> O problema esta aqui: você tinha que ser capaz de pegar essa food e colocar ela dentro do depot.
> 
> E tem uma razao para isso: porque se você nao consegue colocar no depot o seu personagem vai ficar lotado de cap rapidinho,porque até chegar na food que voce quer no npc, vai ter vqrias outras aleatorias antes que vao pesar no seu personagem

Então em resumo, não tá sendo possível colocar essa food no dp, correto?

**Comment by Slec** [comment]
Correto

**Comment by beats-dh** [comment]
I just tested it and it's working.
