### ISSUE TITLE
[Bug]: client interface not saving windows pos/size

### ISSUE THREAD

**Issue by Slec** [opentibiabr/otservbr-global#371]
### What happened?

If i open a window (skill windown, bestiary window, backpacks windows, etc..) and organize them in my client (put an especific size and position) when i logout/close client theyr not saved.
The windows itself are saved, but the exact position and size are not and this is really relevant for the players gameplay.

### How to Reproduce?

1 - open one window (skill, analyzers, backpacks, etc)
2 - place it on a especific position and size on client
3 - close tibia our logout
4 - windows are still there, but the position and size you've placed are not right

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by omeranha** [comment]
this is already fixed in canary and when the compat happens, it will be resolved here too, so I will close
just in case, the pr: https://github.com/opentibiabr/canary/pull/144
