### ISSUE TITLE
[Bug]: Chivalrous Challenge and Divine Dazzle

### ISSUE THREAD

**Issue by Zapotoczny** [opentibiabr/otservbr-global#374]
### What happened?

How to fix it?
They should come up to you and stay for example 10sec
https://streamable.com/hicss4

### How to Reproduce?

use exeta amp res or exana amp res

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beats-dh** [comment]
![Animação](https://user-images.githubusercontent.com/61994374/149446058-dec4db46-10ae-418f-b0a8-469fb636ee9c.gif)

I am using the server updated and no problems. tested the 2 spells
