### ISSUE TITLE
[Bug]: Number of summons is exceeding the maximum stablished.

### ISSUE THREAD

**Issue by tiothiago** [opentibiabr/otservbr-global#380]
### What happened?

General Murius, for exemple, has a maximum number of Minotaur Guards set as 2. Same thing for Minotaur Archers. 

Yet, it happens to be that General Murius is summuning up to 4 Minotaur Guards or 4 Minotaur Archers, clearly a bug somewhere in monster.cpp

### How to Reproduce?

Just summon General Murius.

### Attach any relevant file

![unknown](https://user-images.githubusercontent.com/77829876/149506031-277967b3-bc74-4107-9574-dc77001e2778.png)
![unknown](https://user-images.githubusercontent.com/77829876/149505895-e263e865-c4ba-444b-8c14-178c135e5582.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tiothiago** [comment]
Solution https://github.com/otland/forgottenserver/commit/215713d6916044ec277517c22189c9485236e1a2#diff-62aa9c61dc49a0decc4065f0bf8a8038a56aea325a2c496a048e7657abd03cca

**Comment by dudantas** [comment]
> Solution [otland/forgottenserver@215713d#diff-62aa9c61dc49a0decc4065f0bf8a8038a56aea325a2c496a048e7657abd03cca](https://github.com/otland/forgottenserver/commit/215713d6916044ec277517c22189c9485236e1a2#diff-62aa9c61dc49a0decc4065f0bf8a8038a56aea325a2c496a048e7657abd03cca)

I think this is not the solution, possibly the solution is to fix the other function and not create a new one.

**Comment by dudantas** [comment]
@tiothiago, you can test the pr #381?
