### ISSUE TITLE
[Bug]: Don't work imbu elemental damage in distance weapons

### ISSUE THREAD

**Issue by lichak232** [opentibiabr/otservbr-global#382]
### What happened?

On current imbu does not work elemental damage in distance weapons.

### How to Reproduce?

Set anyone elemental imbuement in bow or crossbow. Target monster and he get 100% physical damage.
With swords, axes and clubs, elemental imbuements works fine.

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04, Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nyedson** [comment]
Are you sure?
I've tried it with the crossbow (ID: 2455) and elvish bow (ID: 7438) and everything is fine.
crossbow (powerful strike):
![Test](https://user-images.githubusercontent.com/41634901/149771088-5d9c6fb8-6526-4afc-8c98-d0b28c2967be.png)

elvish bow (basic strike):
![test 1](https://user-images.githubusercontent.com/41634901/149771763-2ce9c51d-ceb4-4b3c-91ac-3dffa0a3798d.png)

**Comment by Nyedson** [comment]
> ### What happened?
> On current imbu does not work elemental damage in distance weapons.
> 
> ### How to Reproduce?
> Set anyone elemental imbuement in bow or crossbow. Target monster and he get 100% physical damage. With swords, axes and clubs, elemental imbuements works fine.
> 
> ### Relevant log output
> _No response_
> 
> ### Attach any relevant file
> _No response_
> 
> ### Version
> 12.x (Default)
> 
> ### What OS are you seeing the problem on?
> Ubuntu 20.04, Windows 10
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Are you sure?
I've tried it with the crossbow (ID: 2455) and elvish bow (ID: 7438) and everything is fine.
crossbow (powerful):
![Test](https://user-images.githubusercontent.com/41634901/149771088-5d9c6fb8-6526-4afc-8c98-d0b28c2967be.png)

elvish bow (basic):
![test 1](https://user-images.githubusercontent.com/41634901/149771763-2ce9c51d-ceb4-4b3c-91ac-3dffa0a3798d.png)

**Comment by lichak232** [comment]
@Nyedson from the latest version?
I downloaded and compiled some minutes ago, and didn't work.
![image](https://user-images.githubusercontent.com/78379131/149781623-24c47ee1-cd30-4d54-830f-a1dbd3e2c4ed.png)

**Comment by travisani** [comment]
![2022-01-18_020301344_Script_Hotkey](https://user-images.githubusercontent.com/13306169/149873886-bdbfc60b-74a2-491b-a97f-fb42e114ca34.png)

No working with a bows and crossbows only.

Critical and mana/life is working fine.

**Comment by Nyedson** [comment]
> @Nyedson from the latest version? I downloaded and compiled some minutes ago, and didn't work. ![image](https://user-images.githubusercontent.com/78379131/149781623-24c47ee1-cd30-4d54-830f-a1dbd3e2c4ed.png)

Sorry for my earlier message, after you said that, I remembered that I didn't do the updates for c++ (https://github.com/opentibiabr/otservbr-global/commit/d84b1c82eb6f572c568522774131944c922e069c). These big changes usually start full of bugs (very hard to remember everything at the time of big updates, something is always missing), I wait for several patch updates later to put.

I don't know with 100% certainty that it was the cause of your problem but this update should be the difference between the imbuement I have and what's on otbr currently.

**Comment by Mirkaanks** [comment]
is something on quiver and player.lua

**Comment by lichak232** [comment]
> is something on quiver and player.lua

What do you mean?

**Comment by Mirkaanks** [comment]
> > is something on quiver and player.lua
> 
> What do you mean?

nothing, i've tested a fix but gets crash.

**Comment by mattyx14** [comment]
also the imbuid system is not working correctly for example vampirism or void regenerate little and has no effect other than the one you have Target and ignores the rest

**Comment by travisani** [comment]
https://github.com/opentibiabr/canary/issues/187

Now
