### ISSUE TITLE
[Bug]: On kill any monster mana/life restoration is too much

### ISSUE THREAD

**Issue by bashcode** [opentibiabr/otservbr-global#383]
### What happened?

Kill rat -> You were restored for 1030 mana.
Kill dog -> You were restored for 6100 mana.

### How to Reproduce?

after using any item with life leech (tested with cobra rod, soulhexer)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
This not seem to be an issue anymore, could you please test it again, with updated source and database? 
Otherwise, this issue will be closed.

**Comment by guispiller** [comment]
As I said before, this not seem to be an issue anymore, and due to the lack of information of who opened this issue, I am closing this.
Please update your source and datapack.
