### ISSUE TITLE
Piso 29040 dos Falcons bugado

### ISSUE THREAD

**Issue by Sargitarium** [opentibiabr/OTServBR-Global#383]
**Describe the bug**
O piso 29040 está com velocidade muito alta quando se anda sobre ela, e quando você é player normal os monstros não se aproximam, ou seja, você pode ficar ali parado que o monstro não vai até você.
Os items com ID 28972, 28982, 9436 e 12785, estão com o mesmo problema em comum, os monstros não passam sobre eles, com isso pode se atacar o boss de longe sem ele chegar perto, pois item inibe a aproximação.... como não testei no tibia global pode ser que seja erro apenas na otb...

**To Reproduce**
Para reproduzir o erro... apenas ande sobre o piso e verá a alta velocidade, e se for um char normal, tu ficará imune a ataques dos monstros...

**Expected behavior**
Necessário corrigir o item.id na otb

**Screenshots**
https://imagizer.imageshack.com/img923/6445/ghSkHW.png
https://imagizer.imageshack.com/img922/4035/QTvBPF.png

**Comment by rickorion** [comment]
Não há nenhum problema com a otb, e sim itens errados. Já abri um PR com os itens certos para estes locais. o item 9436 está correto e é normal os monstros não passarem por ele. Já os ids 28972 e 28982 testei e os monstros conseguem passar por cima.
Os únicos problemas são realmente as mesas e o piso 29040/29039 que não pertence a esse local.
