### ISSUE TITLE
[Bug]: Familiar still has pet flag inside monster files.

### ISSUE THREAD

**Issue by joelslamospersson** [opentibiabr/otservbr-global#385]
### What happened?

^
Title

### How to Reproduce?

pet = true
to:
familiar = true

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Fixed on PR #427
