### ISSUE TITLE
[Bug]: Amulet bug in amulet time result (onDeEquip).

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#386]
### What happened?

Two amulet are bugged on the team the enchanted sleep shawl and the enchanted werewolf amulet and the enchanted pendulet.

### How to Reproduce?

Equipping Amulet and Unequipping.

### Attach any relevant file

Enchanted sleep shawl

![image](https://user-images.githubusercontent.com/50599143/150520857-83c1e3c8-f98f-4c25-a896-7e1b67b488a1.png)

![image](https://user-images.githubusercontent.com/50599143/150520925-9b53884e-9ffb-4c24-8949-c3b8de3f1a56.png)

![image](https://user-images.githubusercontent.com/50599143/150520971-faeec942-bd16-43e6-b51c-860714f27d27.png)

enchanted werewolf amulet

![image](https://user-images.githubusercontent.com/50599143/150521648-0a92ae20-55df-4d03-8234-3ba56c69a21d.png)

![image](https://user-images.githubusercontent.com/50599143/150521708-597a84d0-3523-4a0b-9726-2f7ddc83ef79.png)
(onDeEquip)

enchanted pendulet amulet

![image](https://user-images.githubusercontent.com/50599143/150639924-6421ac8d-c9b8-43fa-b8ea-b52dd6a483b2.png)

![image](https://user-images.githubusercontent.com/50599143/150639934-121b71d5-fcb5-424d-92ca-b3f92e8ff747.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by attack787** [comment]
I did some tests regarding the problem.
After testing the amulets mentioned here and verifying that they are really in trouble, I decided to analyze other items with decay, such as rings. Rings such as (time, sword, club, axe, dwarven...) are also having decay problems, a little different.

After you equip them, they show that usage time is zero and when you remove it, you notice that no time has been spent.
Sword ring example:
While equipped (_You see a sword ring that will expire in 0 seconds._)
After removing it (_You see a sword ring that will expire in 30 minutes._)

Analyzing some of these rings in items.xml, we can see that they are all correctly written with their respective attributes.
So, I went to analyze the unscripted_movements.lua file. I also found that the attributes were written correctly, however I decided to remove the attribute in one of the script's rings to see if it would continue to perform its functions. I noticed that removing, for example, the sword ring from the script, it kept adding the attributes normally (+4 sword when using the ring) and when removing it the attribute was removed.

So I believe there is a problem with the unscripted_movements.lua file, which may not be working properly, generating this type of problem.

_**note: On older version servers, the movements.lua file contained the scripts for moving items. So I don't know if unscripted_movements.lua really has the same function.**_
