### ISSUE TITLE
[Bug]: Familiar time, error + familiar gone upon logout.

### ISSUE THREAD

**Issue by joelslamospersson** [opentibiabr/otservbr-global#389]
### What happened?

Timer issue, img below:
https://gyazo.com/51906eee71f93a192b9b65e58249073e

### How to Reproduce?

Change data\lib\tables\familiar.lua
From
for sendMessage = 1, #timer do
		player:setStorageValue(timer[sendMessage].storage, -1)
	end

to
for sendMessage = 1, #FAMILIAR_TIMER do
        player:setStorageValue(FAMILIAR_TIMER[sendMessage].storage, -1)
    end

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by travisani** [comment]
`function removeFamiliar(creatureId, playerId)
	local creature = Creature(creatureId)
	local player = Player(playerId)
	if not creature or not player then
		return true
	end
	creature:remove()
	for sendMessage = 1, #FAMILIAR_TIMER do
		player:setStorageValue(timer[sendMessage].storage, -1)
	end
end`

**Comment by travisani** [comment]
function removeFamiliar(creatureId, playerId)
	local creature = Creature(creatureId)
	local player = Player(playerId)
	if not creature or not player then
		return true
	end
	creature:remove()
	for sendMessage = 1, #FAMILIAR_TIMER do
		player:setStorageValue(timer[sendMessage].storage, -1)
	end
end
