### ISSUE TITLE
Blood halls teleporter back to Demon forge broken

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/OTServBR-Global#395]
**Describe the bug**
The "escape"-teleport in the start of the blood halls in inquisition quest is not working. 

**To Reproduce**
1. Go to Zugurosh boss room
2. Kill him ded
3. Enter the tp and arrive in the blood halls
4. Enter the teleporter next to you in the blood halls.

**Expected behavior**
The teleport should take you back to the Demon forge hub in deep edron. 

**Screenshots**

![Screenshot (4)](https://user-images.githubusercontent.com/52839094/62839564-d6b25c00-bc8b-11e9-90ba-9bb4ee7cf7d5.png)

win 10, client 11

:)

**Comment by oualid6496** [comment]
confirmed this is a map bug uid of the teleport has to be changed to 2158 to fix this

**Comment by Raphaellb** [comment]
@EPuncker can you make these changes too? this is similar to my issue #268 and PR #294.

**Comment by EPuncker** [comment]
@Raphaellb yes I'll do it today
