### ISSUE TITLE
[Bug]: Store items from floor to Normal backpack.

### ISSUE THREAD

**Issue by Mirkaanks** [opentibiabr/otservbr-global#398]
### What happened?

When you buy carpet in the store, you can unrap this on house (ok)  Later u can wrap this from floor and move this to your backpack and trade with other players.
Tested carpet "White fur carpet"

When correct action is move this only to store inbox but we can't move this to store box after move items there.
![image](https://user-images.githubusercontent.com/98285577/150856317-33637701-68e4-4a1a-8213-cfee91b06d6b.png)

### How to Reproduce?

Just buy a carpet or other item from store, unrap on floor, wrap and move to your backpack.

### Relevant log output

```shell
Nothing
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beats-dh** [comment]
I just tested it and it's working.
