### ISSUE TITLE
[Bug]: problem when equipping soul items

### ISSUE THREAD

**Issue by gabriel-strix** [opentibiabr/otservbr-global#402]
### What happened?

When equipping a soul weapon, which has critical damage, and then unequipping it, the player is over 65k critical %. This also occurs when putting the item in and out of the backpack.

### How to Reproduce?

Equip your character with any soul weapon and then unequip or put any soul weapon in the backpack and then remove it.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/25540139/151271322-e9ae3d3b-a30f-405d-8f6d-d739ece0519c.png)
![image](https://user-images.githubusercontent.com/25540139/151271346-26ee3f44-3fec-442d-8316-936db817736f.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
Soul item would be exactly what? Are you sure you have all the changes from the imbuement pull request?

**Comment by dudantas** [comment]
Make sure you have these fixes on your server: https://github.com/opentibiabr/otservbr-global/commit/6f4fddb8626912a505c46f4f139798ea2fc0d9d8

**Comment by gabriel-strix** [comment]
Soul Items is the new items from soulwar quest, for example: 

You see a Soulpiercer,
(Range: 6, Atk: +9, Hit% +6, distance fighting +4, protection death +7%, critical hit chance 10%, critical extra damage +10%).
It can only be wielded properly by paladins of level 400 or higher.
Imbuement Slots: 3.
Classification: 4. Max. Tier: 10
It weighs 40.00 oz.

**Comment by gabriel-strix** [comment]
and my server is up to date with the repository

**Comment by beats-dh** [comment]
> and my server is up to date with the repository

We've just released a new release, could you download and test with it?

**Comment by gabriel-strix** [comment]
I hadn't seen it, the fix was implemented in the new release, the bug is already fixed, I'm closing this issue

**Comment by dudantas** [comment]
> I hadn't seen it, the fix was implemented in the new release, the bug is already fixed, I'm closing this issue

Thanks for test. 🤝

**Comment by MuriloLoureiro** [comment]
thanks for report!
