### ISSUE TITLE
morgaroth loot

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/OTServBR-Global#415]
**Describe the bug**
log errors after killing raid boss morgaroth

**To Reproduce**
kill boss morgaroth

**Expected behavior**
all loot should show up without any errors on log

[Warning - Monsters::loadMonster] Unknown loot item "the devileye".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/Bosses/morgaroth.xml
[Warning - Monsters::loadMonster] Unknown loot item "the ironworker".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/Bosses/morgaroth.xml

**Comment by EPuncker** [comment]
oh yeah my bad
