### ISSUE TITLE
The Tainted Souls Quest

### ISSUE THREAD

**Issue by marcomoa** [opentibiabr/OTServBR-Global#42]
Não é possível juntar a Antlers com a Star Herb e a holy water para obter a Sacred Antler Talisman e prosseguir com a quest.

Source: http://tibia.wikia.com/wiki/The_Tainted_Souls_Quest

**Comment by eduardodantas95** [comment]
![image](https://user-images.githubusercontent.com/8551443/60268438-c94f3700-98c2-11e9-934e-484c3927e172.png)
