### ISSUE TITLE
[Bug]: If tile is a house, door/object(s) are not changed.

### ISSUE THREAD

**Issue by joelslamospersson** [opentibiabr/otservbr-global#424]
### What happened?

So, I changed the id of an locked door to an normal door for a house which does not change unless you manually remove it in-game with /r then reboot the server.

### How to Reproduce?

No idea

### Relevant log output

```shell
None
```

### Attach any relevant file

None

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
It turns out that the houses are saved in the database, everything inside them is saved there and loaded when loading the server, the doors are part of it.
