### ISSUE TITLE
[Bug]: quest dawnport

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#433]
### What happened?

Sem função quest dawnport.

### How to Reproduce?

Abrindo o bau da quest dawnport.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/50599143/154138951-d57a5aba-2593-4810-8b1c-a677282d0713.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by attack787** [comment]
Unique id of the chest is different than script (vocation_reward.lua). To fix you can change the unique id of the chest on the map like the script or vice versa.
