### ISSUE TITLE
[Bug]: Can't purchase most (or all) fluid containers

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global#438]
### What happened?

Can't purchase mugs of mead, mugs of tea, flasks of rum, etc. from shops
In Yalahar (NPC Pugwah) looking at mug of lemonade / mug of beer / mug of milk / mug of wine is working, still you can't purchase them

Looking at mug of tea / mug of mead in shop provides:
**19:39 You see a rum flask of unknown.
It weighs 2.80 oz.**
Same goes for flask of rum
Filling mug with water or other fluid is impossible

I checked, there are fluid subtypes:
```
enum FluidColors_t : uint8_t {
    FLUID_EMPTY,
    FLUID_BLUE,
    FLUID_RED,
    FLUID_BROWN,
...
FLUID_TEA = FLUID_BROWN + 32,
FLUID_MEAD = FLUID_BROWN + 40,
```

also I see in dankwart.lua (npc I was checking, other I checked was port hope tavern)
```
{ itemName = "mug of mead", clientId = 2880, buy = 5, count = 43 },
{ itemName = "mug of tea", clientId = 2880, buy = 3, count = 35 }
```
so setup seems correct, probably deeper kind of issue

### How to Reproduce?

go to npc (ex. dankwart in svarground) and try to purchase mug of tea / mug of mead
look at mug of tea / mug of mead / flask of rum in npc shop

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianomengue** [comment]
https://github.com/opentibiabr/canary/pull/228 should fix it.

Can you test it?

**Comment by ghost** [comment]
I checked, NPC trade window doesn't pop up after hi/trade
No console log

**Comment by adrianomengue** [comment]
Have u tested with other NPC?

**Comment by ghost** [comment]
I tried to talk to two NPCs in Venore, both didn't repsond to trade command so I abandoned

**Comment by adrianomengue** [comment]
How have you installed the PR? Because @dudantas had tested and it had worked properly.

**Comment by ghost** [comment]
cloned canary repo, built it following https://github.com/opentibiabr/canary/wiki/Compiling-on-Debian-or-Ubuntu
copied config.lua, key.pem data/ from my working server

**Comment by dudantas** [comment]
The fix: https://github.com/opentibiabr/canary/pull/228
