### ISSUE TITLE
MAP: Pugwah NPC Yalahar falls through trapdoor

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global#439]
#### What kind of issue you found (respawns missing, details, large areas...)?
-  Pugwah Tavern NPC Yalahar falls throught trapdoor

#### Screenshots
![Screenshot from 2022-02-21 10-35-05](https://user-images.githubusercontent.com/20152338/154929383-ddb95f81-9b44-44f8-9c0c-7181fa4aa634.png)
![Screenshot from 2022-02-21 10-41-28](https://user-images.githubusercontent.com/20152338/154929395-c2af062f-0c45-4fc3-9fdf-26bec61fec39.png)

#### What was expected to be in place?
> NPC not falling through trapdoor

#### Environment
- OS (e.g. Windows): ubuntu 20.04
- OTServ Version (e.g. commit): Stable-v1.2.0
- Tibia Version (e.g. 12.52): 12.85

**Comment by adrianomengue** [comment]
Hi,
Could you make a test? 

`https://github.com/opentibiabr/otservbr-global/blob/main/data/npclua/pugwah.lua#L23`

Replace **floorchange** to **floorChange**

Lemme know about the results.

**Comment by dudantas** [comment]
Its spawn position is on the ladder, so it automatically descends when it is created.

**Comment by dudantas** [comment]
> Hi, Could you make a test?
> 
> `https://github.com/opentibiabr/otservbr-global/blob/main/data/npclua/pugwah.lua#L23`
> 
> Replace **floorchange** to **floorChange**
> 
> Lemme know about the results.

This is not the problem, the flag is even lowercase
