### ISSUE TITLE
[Bug]: Cutuble bamboo respawns as wrong object

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global#441]
#### What kind of issue you found (respawns missing, details, large areas...)?
Tiquanda bandit camp (-2) bamboo door structure after being cut with machete respawns as invalid object (giant tree) resulting in permanent close of area
x: 32530 y: 32648 z:9

#### Screenshots
![Screenshot from 2022-02-21 22-56-03](https://user-images.githubusercontent.com/20152338/155041196-ae6a20a0-ae48-41b3-b127-e29067fef03f.png)

#### What was expected to be in place?
> bamboo cutuable door

#### Environment
- OS (e.g. Windows): ubuntu 20.04
- OTServ Version (e.g. commit): stable v1.2
- Tibia Version (e.g. 12.52): 12.85

**Comment by dudantas** [comment]
Lack explanation, what is the location of the place? What is the id of the items that are wrong? Without information it is difficult for us to help

**Comment by ghost** [comment]
I have updated location: x: 32530 y: 32648 z:9
ATM i can't provide ID, only the structure name: giant tree

**Comment by majestyotbr** [comment]
![image](https://user-images.githubusercontent.com/32709570/155815132-91e7a7d3-8792-414d-a03d-1adcb90f8fed.png)

**Comment by majestyotbr** [comment]
Ok, it's the wrong decay id. Will fix.
