### ISSUE TITLE
Dark Trails quest

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/OTServBR-Global#445]
The Ravager boss room needs an exit teleport here 

18:09 You see a carved stone tile.
Item ID: 3172
Position: 33487, 32088, 8

**Comment by Raphaellb** [comment]
The Ravager exit teleport is not working. 

**this teleport here**
18:13 You see a magic forcefield.
Item ID: 1387
Position: 33468, 32073, 8

**Needs to teleport player here.** 
8:14 You see a slime fungus.
Item ID: 13619
Position: 33422, 32105, 10

**Comment by Raphaellb** [comment]
Death Priest Shargon exit teleport here
18:16 You see a magic forcefield.
You can see the other side through it.
Item ID: 1387
Position: 33487, 32101, 9

**Should teleport player to this position**
18:17 You see dirt floor.
Item ID: 11491
Position: 33584, 31847, 10

**Comment by EPuncker** [comment]
> The Ravager boss room needs an exit teleport here
> 
> 18:09 You see a carved stone tile.
> Item ID: 3172
> Position: 33487, 32088, 8

onde fica isso pra mim poder add o portal

**Comment by Raphaellb** [comment]
coloca o portal nessa posicao 33487, 32088, 8, e teleporta o jogador pra fora da sala do boss pra essa posicao 33422, 32105, 10. @EPuncker

**Comment by Raphaellb** [comment]
lever to The Ravager boss is not working properly. the lever does summon the boss, but it is not teleporting players to boss room.

23:40 You see a lever.
Item ID: 1946, Unique ID: 9511
Position: 33416, 32102, 10

**Comment by Raphaellb** [comment]
lever to Death Priest Shargon is not working properly. the lever does summon the boss, but it is not teleporting players to boss room. 

23:42 You see a lever.
Item ID: 1946, Action ID: 9512
Position: 33582, 31844, 10

**Comment by Raphaellb** [comment]
cant open death priest shargon body. 

15:25 You see a dead body of Quandon.
Item ID: 23494
Position: 33484, 32105, 9

**Comment by Raphaellb** [comment]
23:06 You see a closed door.
Item ID: 22817
Position: 33666, 31924, 7

this should be a quest door with action id 20080.
