### ISSUE TITLE
[Bug]: Trying to sell item on Esrik

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#452]
### What happened?

tentando vender item e não está aceitando.

### How to Reproduce?

Apertando botão ok e não está aceitando.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/50599143/155716873-da7ff36b-f9b5-4f43-83d7-9c367593faf9.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Test:
https://github.com/opentibiabr/canary/pull/228
https://github.com/opentibiabr/otservbr-global/pull/445
