### ISSUE TITLE
[Bug]: bug in supply trash

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#456]
### What happened?

Após depositar o item no supply trash.

### How to Reproduce?

Tentando tirar item do supply trash.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/50599143/155830313-f94a136a-9108-4dde-8184-795a653faf94.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
It's working. If you are testing with god character disable ghost mode.
