### ISSUE TITLE
[Bug]: dont have occupation item of type 20473.

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#459]
### What happened?

Sem funcão item of type 20473.

### How to Reproduce?

tentando descer no item of type 20473.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/50599143/155852869-3b81f964-6f84-4aaa-8412-6972619f6eaa.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sh3Ns** [comment]
this stairs is going down 2 floors after correction

**Comment by majestyotbr** [comment]
I'm not testing the fixes. 
Test the behaviour floorchange with the correct ids and answer here.

**Comment by Sh3Ns** [comment]
yes it's going down 2 floors

**Comment by majestyotbr** [comment]
Fixed ladder rung behaviour.
