### ISSUE TITLE
[Bug]: Bug event scheduler

### ISSUE THREAD

**Issue by garaflaks** [opentibiabr/otservbr-global#461]
### What happened?

o evento ativa quando ligo o servidor, mas não aparece na parte de evento do cliente e também a exp não altera dentro do jogo.

### How to Reproduce?

.

### Relevant log output

```shell
.
```

### Attach any relevant file

![scheduler](https://user-images.githubusercontent.com/41268925/155853516-53c19f07-250f-4c90-92db-60520948610c.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 18.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
In the client, remember to set the cache/eventsschedule.json file blank and read-only. About the exp, someone need to check.

**Comment by beats-dh** [comment]
@garaflaks Could you test the PR I linked with this issue and see if it resolved?

The issue of not appearing on the client is just you delete the files inside the cache folder and reopen the client!

**Comment by garaflaks** [comment]
> @garaflaks Could you test the PR I linked with this issue and see if it resolved?
> 
> The issue of not appearing on the client is just you delete the files inside the cache folder and reopen the client!

the client problem solved, but the exp, skill not
![erro](https://user-images.githubusercontent.com/41268925/155909800-42c81887-da0d-4c76-bfd9-e90e79f2ae0f.png)

**Comment by garaflaks** [comment]
> > @garaflaks Could you test the PR I linked with this issue and see if it resolved?
> > The issue of not appearing on the client is just you delete the files inside the cache folder and reopen the client!
> 
> the client problem solved, but the exp, skill not ![erro](https://user-images.githubusercontent.com/41268925/155909800-42c81887-da0d-4c76-bfd9-e90e79f2ae0f.png)




the monsters have double exp is correct.

Inside the skills tab it's still 100% exp, not 200%

data/scripts/globalevents/others/startup.lua

	local lootRate = Game.getEventSLoot()
	if lootRate ~= 100 then
		SCHEDULE_LOOT_RATE = lootRate
	end

	local expRate = Game.getEventSExp()
	if expRate ~= 100 then
		SCHEDULE_EXP_RATE = expRate
	end

	local skillRate = Game.getEventSSkill()
	if skillRate ~= 100 then
		SCHEDULE_SKILL_RATE = skillRate
	end

**Comment by garaflaks** [comment]
we have another problem, double ml doesn't work for "exercise weapons"
