### ISSUE TITLE
[Bug]: bug em sqm Ab'dendriel 

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#462]
### What happened?

sqm de Ab'dendriel levando para o boss da wz versperoth.

### How to Reproduce?

pisando em sqms em Ab'dendriel quase todos pontos de sqms em Ab'dendriel .

### Attach any relevant file

![image](https://user-images.githubusercontent.com/50599143/155849308-683b6698-d987-4f8a-8b6b-bc97914793c5.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Post the position of the tile to investigate the issue.

**Comment by majestyotbr** [comment]
Unconfirmed, this is not happening here.
