### ISSUE TITLE
Autoloot

### ISSUE THREAD

**Issue by Tazer89** [opentibiabr/OTServBR-Global#467]
Autoloot don't work i was trying the autoloot mode 2.

No errors shown in console.

**Comment by krecikondexin** [comment]
https://github.com/opentibiabr/OTServBR-Global/commit/649ec416851f8e1a23418a48707e458f0d49489e

this patch break old "!add Monster_Name", i use old script but when i click add/backpack etc window close and do nithing (auto loot don't work)
