### ISSUE TITLE
[Bug]: exercise weapons 

### ISSUE THREAD

**Issue by garaflaks** [opentibiabr/otservbr-global#474]
### What happened?

any vocation can use exercise weapons.

Example
Knight can use exercise rod.

### How to Reproduce?

.

### Relevant log output

```shell
.
```

### Attach any relevant file

.

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 18.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sh3Ns** [comment]
testei aqui isso é padrão do jogo, elas não tem especificação de voc.
