### ISSUE TITLE
[Bug]: Bomb dando PZ wall & field

### ISSUE THREAD

**Issue by Sh3Ns** [opentibiabr/otservbr-global#475]
### What happened?

Só de utilizar as runas de bomb, wall e field, estão dando pz, como se estivesse atacando player.

O certo deveria ser dar apenas battle.

### How to Reproduce?

jogando bomb nos sqms.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/50599143/156271191-f1621d7b-368c-409f-8439-977733c917ce.png)
![image](https://user-images.githubusercontent.com/50599143/156271142-c07b6e4e-cf4e-47b8-87da-1a4a0c58abf3.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andersonfaaria** [comment]
duplicate of https://github.com/opentibiabr/canary/issues/59
can you confirm this isn't standard behavior?

**Comment by beats-dh** [comment]
It's the expected behavior.
