### ISSUE TITLE
twice loot channel

### ISSUE THREAD

**Issue by gpedro** [opentibiabr/OTServBR-Global#479]
**To Reproduce**
1. Go to 'Open new channel (Ctrl+O).'
4. See two 'Loot' channel

**Expected behavior**
Just one

**Screenshots**
![Screenshot_15](https://user-images.githubusercontent.com/2898638/63743752-4408e400-c86b-11e9-96f6-69e6d1b9962a.png)

**Comment by miezaF** [comment]
https://github.com/opentibiabr/OTServBR-Global/pull/498 FIXED
