### ISSUE TITLE
[Quest] Rottin Wood and the Married Men 

### ISSUE THREAD

**Issue by marcomoa** [opentibiabr/OTServBR-Global#48]
Mission 3: Bushwhacking- After set the traps on the ground, the passing merchants don't appear, making the quest incomplete.

Source: http://tibia.wikia.com/wiki/Rottin_Wood_and_the_Married_Men_Quest

**Comment by gpedro** [comment]
i closed the wrong issue. sorry. #468

**Comment by dudantas** [comment]
Moving alls quests issues for one unique issue.
