### ISSUE TITLE
[Bug]: MsgContains method not working correctly

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global#481]
### What happened?

```
 if MsgContains(message, 'gamel') and MsgContains(message, 'rebel') then
                npcHandler:say('Are you saying that Gamel is a member of the rebellion?', npc, creature)
                npcHandler:setTopic(playerId, 1)
```
this condition from Chester Kahs.lua will never work, something is broken inside MsgContains when it receives space separated string "gamel rebel" for single word condition:
```
function MsgContains(message, keyword)
        local lowerMessage, lowerKeyword = message:lower(), keyword:lower()
        if lowerMessage == lowerKeyword then
                return true
        end

        return string.find(lowerMessage, lowerKeyword)
                and string.find(lowerMessage, lowerKeyword.. '(%w+)')
                and string.find(lowerMessage, '(%w+)' .. lowerKeyword)
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianomengue** [comment]
`if MsgContains(message, 'gamel rebel') then`

Try it.

**Comment by ghost** [comment]
It's not resolving the issue,this condition should return true in both cases

**Comment by adrianomengue** [comment]
So, if I just say "gamel" or "rebel" it is supposed to work?

**Comment by dudantas** [comment]
```lua
if MsgContains(message, 'gamel') or MsgContains(message, 'rebel') then
```

**Comment by ghost** [comment]
> if MsgContains(message, 'gamel') and MsgContains(message, 'rebel') then

No, it should work when you type 'gamel rebel' or 'rebel gamel' or even 'gamel is fat and i'm the rebel'
MsgContains method should check if message contains provided string
ATM any of examples I provided would return false even tho they all contain both words

BUT only if the message contains BOTH of the words, so or condition is not correct

**Comment by dudantas** [comment]
> > if MsgContains(message, 'gamel') and MsgContains(message, 'rebel') then
> 
> No, it should work when you type 'gamel rebel' or 'rebel gamel' or even 'gamel is fat and i'm the rebel' MsgContains method should check if message contains provided string ATM any of examples I provided would return false even tho they all contain both words
> 
> BUT only if the message contains BOTH of the words, so or condition is not correct

It's not a problem, you simply need to set all the conditions:
```lua
MsgContains(message, 'gamel') or MsgContains(message, 'rebel') or MsgContains(message, 'gamel rebel')
```
![image](https://user-images.githubusercontent.com/8551443/156894179-b234a9c6-e248-42a0-aa91-2a57b6a4b658.png)

**Comment by ghost** [comment]
It is a problem because method MsgContains which is supposed to return true when message contains a string is not working correctly:
MsgContains(message, 'rebel') should return true when called by string "gamel rebel" and it's not doing that
why are you solving it by workarounds?

**Comment by kasiula03** [comment]
I've fixed it up temporary on my server, instead of 
`return string.find(lowerMessage, lowerKeyword)
                and string.find(lowerMessage, lowerKeyword.. '(%w+)')
                and string.find(lowerMessage, '(%w+)' .. lowerKeyword)` 
we can replace it with 
`return string.find(lowerMessage, "%f[%w_]" .. lowerKeyword .. "%f[^%w_]")`.
That's works fine, but problem occur in bank system, when command "deposit all" doesn't work because of conditions order (simple deposit is above the version with "all"). Changing the order fixed the issue.
Did you think that it can be valid solution or maybe you see another potential problem simillary to "deposit all"? I can do PR with these changes if you wish.

**Comment by dudantas** [comment]
> It is a problem because method MsgContains which is supposed to return true when message contains a string is not working correctly:
> MsgContains(message, 'rebel') should return true when called by string "gamel rebel" and it's not doing that
> why are you solving it by workarounds?

This has been changed to only identify the complete string, as using it to capture any string was causing npcs related issues, in some scenarios that I don't remember anymore. Anyway, it seems that the way it is today is the way that generates "less bugs" and I believe that there aren't many places that will use the way I put it above. And no, this is not a workaround, the ifs serve to return true or false as well.

This here is to use alternative method:
https://github.com/otland/forgottenserver/blob/7df369c91f5214df2cef5672b2fe0e7c8ecc35df/data/npc/scripts/bank.lua#L284
