### ISSUE TITLE
[Bug]: warzone 1,2,3

### ISSUE THREAD

**Issue by doenteverde** [opentibiabr/otservbr-global#504]
### What happened?

when many players enter the teleport, several bosses may appear 
 
from what I looked at the code I didn't find anything to check if there is already a boss in the room 

### How to Reproduce?

when many players enter the teleport, several bosses may appear 
 
from what I looked at the code I didn't find anything to check if there is already a boss in the room 

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Are you still facing this issue? I tried to reproduce it here, but it doesn't create more than one boss.

**Comment by guispiller** [comment]
Tested, couldn't reproduce it, it seems to be fine. Since you don't answered anymore, I'll close this.
If you face this issue again, please contact me.
