### ISSUE TITLE
Magic walls and wild growth disappear when someone steps over it

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global#507]
### What happened?

magic walls and wild growth disappear if a player or monster walks through them in open pvp and pvp enforced.
magic walls does not disappear in non pvp but monsters and players can walk through them.

### How to Reproduce?

x

### Relevant log output

```shell
x
```

### Attach any relevant file

local combat = Combat()
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_EARTH)

function onCreateMagicWall(creature, tile)
	local item = Game.createItem(Game.getWorldType() == WORLD_TYPE_NO_PVP and ITEM_WILDGROWTH_SAFE or ITEM_WILDGROWTH, 1, tile)
	item:setAttribute(ITEM_ATTRIBUTE_DURATION, math.random(38000, 45000))
end

combat:setCallback(CALLBACK_PARAM_TARGETTILE, "onCreateMagicWall")

local spell = Spell("rune")
function spell.onCastSpell(creature, variant, isHotkey)
    return combat:execute(creature, variant)
end

spell:name("Wild Growth Rune")
spell:group("attack")
spell:id(94)
spell:cooldown(2 * 1000)
spell:groupCooldown(2 * 1000)
spell:level(27)
spell:magicLevel(8)
spell:runeId(3156)
spell:charges(2)
spell:isBlocking(true, true)
spell:allowFarUse(true)
spell:vocation("druid;true", "elder druid;true")
spell:register()

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aerwix** [comment]
I confirm this bug.

Long ago I changed the ids for magic wall + wild growth bc they weren't decaying.
```C++
        ITEM_MAGICWALL = 2128,
	ITEM_MAGICWALL_PERSISTENT = 2129,
	ITEM_MAGICWALL_SAFE = 10181,

	ITEM_WILDGROWTH = 2130,
	ITEM_WILDGROWTH_PERSISTENT = 3635,
	ITEM_WILDGROWTH_SAFE = 10182,
	```

**Comment by Aerwix** [comment]
I was checking the old files and I noticed this changes.

> [OTLand TFS - Combat.cpp](https://github.com/otland/forgottenserver/blob/master/src/combat.cpp)
> [Canary - Combat.cpp](https://github.com/opentibiabr/canary/blob/a53d747c9de1580b276ad3e38a18f83b6ee92a9c/src/creatures/combat/combat.cpp)

I compared both text with [Diff Checker](https://www.diffchecker.com/diff) and there is the difference
![image](https://user-images.githubusercontent.com/26527255/158888963-09eaa0cc-f652-47f8-9246-b6b84a55738f.png)

Try this changes.

**Comment by Tefcio** [comment]
confirmed problem

**Comment by andersonfaaria** [comment]
> I was checking the old files and I noticed this changes.
> 
> > [OTLand TFS - Combat.cpp](https://github.com/otland/forgottenserver/blob/master/src/combat.cpp)
> > [Canary - Combat.cpp](https://github.com/opentibiabr/canary/blob/a53d747c9de1580b276ad3e38a18f83b6ee92a9c/src/creatures/combat/combat.cpp)
> 
> I compared both text with [Diff Checker](https://www.diffchecker.com/diff) and there is the difference ![image](https://user-images.githubusercontent.com/26527255/158888963-09eaa0cc-f652-47f8-9246-b6b84a55738f.png)
> 
> Try this changes.

did this worked for you?

**Comment by Tefcio** [comment]
> 

for me not working

**Comment by andersonfaaria** [comment]
> > 
> 
> for me not working

you did the changes shown by @Aerwix and it still didn't solved?

**Comment by Tefcio** [comment]
> > > 
> > 
> > 
> > for me not working
> 
> you did the changes shown by @Aerwix and it still didn't solved?

yes, still the same. In which file i can change wall ids?

**Comment by Aerwix** [comment]
> yes, still the same. In which file i can change wall ids?
Here you can change them. Test them and update this thread please.
https://github.com/opentibiabr/canary/blob/dd03479999cb50ea4fac8cd4d79bd4213802cff2/src/utils/utils_definitions.hpp
