### ISSUE TITLE
[Bug]:  Destroy field rune is not working

### ISSUE THREAD

**Issue by lafegob** [opentibiabr/otservbr-global#510]
### What happened?

Destroy field rune is not working. If you try to use it on a fire field for example, it's not destroying it.

### How to Reproduce?

Just try to use the Destroy Rune 

### Relevant log output

```shell
x
```

### Attach any relevant file

x

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by agon1982** [comment]
Try to change array FIELDS  in scripts/lib/register_spells.lua to:

FIELDS = {2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2131,2132,2133,2134,2135}
