### ISSUE TITLE
[Bug]: offline training in bed problem

### ISSUE THREAD

**Issue by Tefcio** [opentibiabr/otservbr-global#526]
### What happened?

Hi! I have problem with house's beds. when someone is sleeping in bed, bed is looking still like without any player sleeping in. It isnt changing it look. 

### How to Reproduce?

Put one character to sleep in bed, and check this bed with other character, how it looks, inspect etc

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by travisani** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/13306169/161158963-70b3a718-67a3-402d-9e4f-f024ba43e4d3.png)

**Comment by spectr0h** [comment]
--------PORTUGUÊS----------
Confirmado o bug.
Resolvi ele mudando no arquivo **"data\items\items.xml"**
as linhas que contém **key="femalesleeper"** mudando para **key="femaletransformto"**. E **key="malesleeper"** mudando para **key="maletransformto"**

----------ENGLISH------------

Bug confirmed.
I solved it by changing the file **"data\items\items.xml"**
the lines that contain **key="femalesleeper"** changing to **key="femaletransformto"**. And **key="malesleeper"** changing to **key="maletransformto"**

![image](https://user-images.githubusercontent.com/85084701/161814450-2bd42f50-a9af-4467-8166-77652b0af7f6.png)

**Comment by sircurse** [comment]
@spectr0h that worked for me, thx!

**Comment by Tefcio** [comment]
is works, thanks
