### ISSUE TITLE
MAP: Kazordoon Guild Hall: Hill Hideout, Missing depot box.

### ISSUE THREAD

**Issue by Dirhai** [opentibiabr/otservbr-global#530]
#### What are the coordinates of the place where the issue with the map was found?
Your current position is: 32579, 31823, 10.

#### What kind of issue you found?
-Kazordoon Guild Hall: Hill Hideout, Missing depot box and some decoration in the room the depot box was suposed to be. 

#### What was expected to be in place?
> Missing the depot box, and some decoration in the depot room.

#### Environment
- OS: Windows 10
- OTServ Version: https://github.com/opentibiabr/otservbr-global
- Tibia Version: 12.85

**Comment by guispiller** [comment]
According to Tibia fandom (https://tibia.fandom.com/wiki/Hill_Hideout), there are no depot box in this house, but there's some chests, is that what you're referring to?
If it's not, please post a screenshot for us to see how it's meant to be.
