### ISSUE TITLE
[Bug]: Hirelings duplicating and not working as they should

### ISSUE THREAD

**Issue by spectr0h** [opentibiabr/otservbr-global#533]
### What happened?

When purchased and placed in the house, the hireling changes all other hirelings on the server to the same name. And after that it stops working. running out of use

### How to Reproduce?

Well, what has happened on the server is the following:
**1st** I buy a Hireling with my char and name it as ex: João
**2nd** I activate the lamp and it is there normal, working normally...
**3rd** I go to another char in another house and buy a hireling and name her ex: Maria
**4th** I turn on the Maria's lamp in the other house and...
                            _--Errors begins..._
**5th** I say Hi to Maria, she answers and asks if I want any service...
**6th** I answer "Service" and nothing happens...
**7º** I go to the other house where João was, he automatically changes his name to Maria... Just like all other hirelings on the server. (sometimes only when the house owner logout)

### Attach any relevant file

![Screenshot_bug](https://user-images.githubusercontent.com/85084701/161846830-aade3861-30f7-4172-b530-943d56865786.png)
![Screenshot_bug2](https://user-images.githubusercontent.com/85084701/161846859-0d8c35fa-858a-48d9-96e5-a4c4875230f8.png)
![Screenshot_bug3](https://user-images.githubusercontent.com/85084701/161846925-507d5c23-9b5e-4ad5-a58c-b0687eb56e93.png)
![Screenshot_bug4](https://user-images.githubusercontent.com/85084701/161846944-7c2beaba-38c7-46de-b416-3688c498bfbb.png)
![Screenshot_bug5](https://user-images.githubusercontent.com/85084701/161846951-541ed769-f47b-45a7-9d3a-63f583b6338c.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04, Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by travisani** [comment]
Voce sai andando ou vai até outro hireling através de algum comando que te teleporta, tipo:
/a
/goto
/c
etc...

**Comment by spectr0h** [comment]
> Voce sai andando ou vai até outro hireling através de algum comando que te teleporta, tipo: /a /goto /c etc...

Sem nenhum comando, apenas andando.

**Comment by AdversarioV** [comment]
yeah this happens to me as well apparently you can only have 1 hireling per account

**Comment by fellipe006** [comment]
sim esse bug realmente esta rolando estou com um servidor on para teste se os players reportou sobre esse bug e testei em windows e ocorreu msm erro todos Hirelings do servidor vai puxar o nome e aparencia do primeiro comprado do server e as função dele para de funcionar .
