### ISSUE TITLE
Items that causing crash while using recent client from recommended tools.

### ISSUE THREAD

**Issue by gerotib** [opentibiabr/OTServBR-Global#546]
While using recent client following item ids on my "test" island caused crash:
34697, 34698, 34699, 35057, 35060 (and maybe some more that werent on my isle)

These items need "stackable" attribute in items.otb checked, then it work fine on new client. (but older version crashes)

**Comment by lBaah** [comment]
Have you applied latest items.otb from https://github.com/opentibiabr/OTServBR-Global/commit/09c3c977f0108d8a18eb9d8f1a09e80e354a6aa8 to your server?

**Comment by gerotib** [comment]
Yes, I went to test it after they were added, to test if crash would still happen (it did on prevoius otbm too). Then I realised that "stackable" attributes of these items in item editor were red (while unchecked), which caused a crash.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/64468749-a7620400-d0fe-11e9-9a6a-759a0c27e8da.png)
![image](https://user-images.githubusercontent.com/8551443/64468751-b1840280-d0fe-11e9-930a-79346f3803ca.png)
![image](https://user-images.githubusercontent.com/8551443/64468757-ba74d400-d0fe-11e9-82e6-fc276ec8bb41.png)
![image](https://user-images.githubusercontent.com/8551443/64468764-c2cd0f00-d0fe-11e9-8673-78b73d9e61f5.png)
![image](https://user-images.githubusercontent.com/8551443/64468766-ca8cb380-d0fe-11e9-9c47-b08b257a50e7.png)
That client you is using ?

**Comment by dudantas** [comment]
Ok, I got it. You refer to client10.
Well, I realize that I really crash on client 10. I'm updating items.otb and I'm already up the fix. My suggestion is that next time you are more specific and name which client you use (10 or 11). Thanks for the report, I'm correcting.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/64468925-9adeab00-d100-11e9-91d2-f805356014fd.png)
Thanks, it's ok.
