### ISSUE TITLE
[Bug]: Store items + Disintegrate Rune = 0 Store Items

### ISSUE THREAD

**Issue by Heppys** [opentibiabr/otservbr-global#557]
### What happened?

Store items can be disintegrated using the disintegrate rune.

### How to Reproduce?

Take any item from the store and use the disintegrate rune on it.

### Relevant log output

```shell
no
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by murilo09** [comment]
can you please update your sources and datapack and try it again? I just tested this issue and it's working fine.
