### ISSUE TITLE
Client/Server protocol problem.

### ISSUE THREAD

**Issue by Eyalon** [opentibiabr/otservbr-global#563]
### Priority

Critical

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

When i started to play local everything was ok. Today after a few days (I've been on holidays) after server was started and login to my account on the client i have error and can't login to any character. Look at the screenshot and marks. Ofc client is 12.85 version and it's correct.
![Error](https://user-images.githubusercontent.com/56226509/165181270-64f2e64d-e459-4502-bf94-2a84d821e9e0.png)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
This issue page is intended for issues in otserver datapack. Your problem is bad config (maybe on config.lua), not actually a datapack issue.
If you need support, please send message on discord channel, we could help you there.

**Comment by majestyotbr** [comment]
With updated Canary / OTServBR-Global Datapack:
![image](https://user-images.githubusercontent.com/32709570/165185011-6bac103e-36f4-4dd6-b186-45efbc4f821a.png)

**Comment by majestyotbr** [comment]
With updated Canary / OTServBR-Global Datapack:
![image](https://user-images.githubusercontent.com/32709570/165185120-89226640-193f-4dd6-b434-097a75b6b60d.png)

**Comment by Eyalon** [comment]
I've played this character before xD and i nothing changed.
![Error](https://user-images.githubusercontent.com/56226509/165186014-0d60380b-8ece-4d05-9154-e4152f338dab.png)
