### ISSUE TITLE
[MAP] Level Door instead of Quest Door on Corym cave

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#569]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

This region is very requested by player due to how easy is to generate gold hunting the Stonerefiner, to access this monster location you should complete a very short quest.

It supposed to have at the beginning of the quest, a Quest Door, and not a level door, I m planning to write this quest as is in global, so would be nice if we could change this door as well.

You see a gate of expertise for level 50.
Client ID: 1648, Action ID: 1050
Position: 33046, 32066, 12

![image](https://user-images.githubusercontent.com/11935651/165779985-dd11685f-ceeb-4a95-b6e7-3bc97641b25e.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
