### ISSUE TITLE
npcConfig.currency trade performing unintended actions

### ISSUE THREAD

**Issue by Sparkz023** [opentibiabr/otservbr-global#573]
### Priority

Low

### Area

- [ ] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

When trading with NPC's Cledwyn or Yana, and making use of the npcConfig.currency values, they'll initiate the trade buy regardless of items purchased, will only charge you for the first purchase.

This seems to only really be a problem for Magic Shield Potions, as if you have 100 silver tokens and opt to buy 100 of them, it will deliver all 100 potions, but only take one token. Due to the armors being 100 tokens a piece, these can not be abused.

The same can be done when purchasing gold token weapons. With 100 tokens you can purchase 2, but only have to pay for one. 

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
Thanks for reporting, I'll check this
