### ISSUE TITLE
[MAP] Missing depot in guild hall Outlaw Castle

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#576]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

This guild have a depot inside, but it is missing on map:
![image](https://user-images.githubusercontent.com/11935651/166069682-24d8cf79-60b7-490b-9575-1ab5259bc0b4.png)

Here is how it looks like on global:
![image](https://user-images.githubusercontent.com/11935651/166069891-3029a361-d0ab-466b-bc4c-a5c3d0a2976d.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
