### ISSUE TITLE
[MAP] Missing chest and decorations Stonerefiner cave

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#584]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

In Hidden Threats Quest, there is a part where it is missing a chest and some decorations.

Position: 33079, 32016, 13

How the map is right now:
![image](https://user-images.githubusercontent.com/11935651/167219689-1d028dc4-58f6-420f-9c71-deef02a9f096.png)

This is how the map should looks like:
![482](https://user-images.githubusercontent.com/11935651/167219749-f3132fb6-aec2-46b3-aa49-084c3e88c21b.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mirkaan** [comment]
Fix: 

[stonecavefix.zip](https://github.com/opentibiabr/otservbr-global/files/8841070/stonecavefix.zip)

You need to add a rusted key fragment action quest.

**Comment by mirkaan** [comment]
a

**Comment by travisani** [comment]
Fix: 

[stonecavefix.zip](https://github.com/opentibiabr/otservbr-global/files/8841070/stonecavefix.zip)

You need to add a rusted key fragment action quest.

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map available in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
