### ISSUE TITLE
[MAP] AIDs and UIDs that can be removed from map for The New Frontier Quest

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#595]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

With the review of the quest The New Frontier ([PR#594](https://github.com/opentibiabr/otservbr-global/pull/594)), somethings can be changed/removed from the map.

### **1:** Position(**_33170, 31254, 10_**)
This region of the map have two coal basin, when on it supposed to have only one as the global.
![image](https://user-images.githubusercontent.com/11935651/168670258-107d6b2b-46ca-4b4d-9dce-a9f35e5278c9.png)

This is how it should looks like:
![image](https://user-images.githubusercontent.com/11935651/168670555-2885051e-0af6-43f3-a8e0-11cca4cc2d04.png)

In this same location, the room doesnt looks accurate:
![image](https://user-images.githubusercontent.com/11935651/168673866-e01dec95-f744-4819-a1cf-ebb0b353bf47.png)

And this is how the room should look like:
![image](https://user-images.githubusercontent.com/11935651/168673794-cede3e98-d3a8-42cc-b66d-726042b371c5.png)

### **2:** Position(**_33170, 31254, 10_**)
The following action IDs can be removed from the map (8007)
![image](https://user-images.githubusercontent.com/11935651/168670685-aa52e233-db32-4bd7-82af-a3dd946072ca.png)

### **3:** Position(**_33061, 31527, 14_**) / Position(**_33061, 31527, 12_**) / Position(**_33061, 31527, 10_**) / Position(**_32991, 31539, 1_**) / Position(**_33065, 31489, 15_**)
The following action IDs can be removed from the map **(8006, 9123, 9122, 9121, 9120, 9118, 8005)**
These action IDs are actually levers, and all of them is now being controlled over scripts only.

### **4:** Position(**_33055, 31025, 7_**)
The following action and unique IDs can be removed from the map **(45440, 2000, 3158, 3159, 3160)**
![image](https://user-images.githubusercontent.com/11935651/168672019-96112af0-8efd-416e-a31d-9878b2c7395f.png)

Also the items inside the chests can be removed:
![image](https://user-images.githubusercontent.com/11935651/168672137-10ac2cbe-6b97-4d9e-a36e-34dcc92fc3cb.png)

![image](https://user-images.githubusercontent.com/11935651/168672194-9f44e565-e8a1-4628-ba9a-d7e3d4de2de9.png)

![image](https://user-images.githubusercontent.com/11935651/168672257-f4bd2ffb-98a5-4833-bcd7-8d7f085f4850.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
