### ISSUE TITLE
[STORE] Market Casks

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/otservbr-global#597]
**Describe the bug**
When buying any of the potion casks in the store, you get a get a Cask package delivered with nothing in it.

**To Reproduce**
open market, navigate to cask tab, and purchase any of the casks.

**Expected behavior**
you should receive the cask of potion

**Comment by VitorNM** [comment]
I got this error too, so i tried to fix it in `modules/scripts/gamestore/gamestore.lua`

![image](https://user-images.githubusercontent.com/29928255/73588042-97c6cb80-44a2-11ea-8c43-eeb7e81525f4.png)
When i change this string to `type = GameStore.OfferTypes.OFFER_TYPE_HOUSE` i receive a house parcel containing the cask, BUT with just 1 refill charge.

So, at this moment i tried to put in the store offer attribute something like `count = 1000, number = 1` or `count = 1, number = 1000` or `count = 1000, number = 1000` but without success atm.

If i solve this issue, i post here. I will keep trying.
