### ISSUE TITLE
The Great Dragon Hunt Quest

### ISSUE THREAD

**Issue by marcomoa** [opentibiabr/OTServBR-Global#60]
Não há quest, tem que ser iniciada do zero.

source:http://tibia.wikia.com/wiki/The_Great_Dragon_Hunt_Quest

**Comment by eduardodantas95** [comment]
Copse actionid: 4230
![image](https://user-images.githubusercontent.com/8551443/59518991-4cbd6100-8e9d-11e9-9311-3c9090787794.png)

Chest actionid: 4231

![image](https://user-images.githubusercontent.com/8551443/59519500-5e533880-8e9e-11e9-8ac1-2bfde86ff82f.png)


https://www.tibiawiki.com.br/wiki/The_Great_Dragon_Hunt_Quest

Ao repetir a quest 10 vezes, você receberá o achievement "Hoard of the Dragon".

**Comment by gpedro** [comment]
como assim repetir 10x a quest? matar 500 dragons?

**Comment by eduardodantas95** [comment]
Não, pode repetir quantas vezes quiser, no caso quando matar 50 dragons 10 vezes

**Comment by eduardodantas95** [comment]
La np wiki mostra como fica no server log tbm, mas isso pode deixar q eu faço

**Comment by gpedro** [comment]
essa actionid deve conflitar com outro item
https://github.com/opentibiabr/OTServBR-Global/blob/82fd233fd3b83d10c409078e303f73b9f923704c/data/movements/scripts/others/teleports/spikeTeleports.lua#L7

**Comment by eduardodantas95** [comment]
Será? Vou ver
