### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by Tibia-Servers** [opentibiabr/otservbr-global#603]
### Priority

Low

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

Hello, has anyone had this error and managed to fix it. I would like to know how thanks

![error](https://user-images.githubusercontent.com/31782523/169718488-27962cb5-29fb-44f9-b841-09862bc40ad2.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beats-dh** [comment]
> ### Priority
> Low
> 
> ### Area
> * [x]  Datapack
> * [ ]  Source
> * [ ]  Map
> * [ ]  Other
> 
> ### What happened?
> Hello, has anyone had this error and managed to fix it. I would like to know how thanks
> 
> ![error](https://user-images.githubusercontent.com/31782523/169718488-27962cb5-29fb-44f9-b841-09862bc40ad2.png)
> 
> ### What OS are you seeing the problem on?
> Windows
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

How much RAM?

**Comment by Tibia-Servers** [comment]
I have 16 ram and 500 ssd hard drive

PD:I have tested removing the monster folder in events and it starts the server in case that helps you find a solution

**Comment by majestyotbr** [comment]
It's not a bug or problem, you are doing something wrong. 
To use only Canary, you should use Canary default datapack.
To use OTServBR-Global Datapack, you compile Canary sources and place the compiled executable + dlls in OTServBR-Global Datapack folder.

**Comment by majestyotbr** [comment]
Next time, use the discord to ask for support: https://discordapp.com/invite/3NxYnyV
