### ISSUE TITLE
NPC Não responde mesmo que no script dele esteja tudo certo

### ISSUE THREAD

**Issue by Alissonlv123** [opentibiabr/otservbr-global#607]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

Olá galera então queria compartilhar isso pra vocês o NPCS quando ficaram em .lua com isso trouxe que os npcs fica-sem mudos então como posso explicar exemplo o script do lorek 

COMO PODEMOS VER TEM BANUTA LA EMBAIXO CERTO?? 
-- Travel
local function addTravelKeyword(keyword, text, cost, destination, condition)
	local travelKeyword = keywordHandler:addKeyword({keyword}, StdModule.say, {npcHandler = npcHandler, text = 'Do you seek a passage to ' .. (text or keyword:titleCase()) .. ' for |TRAVELCOST|?', cost = cost}, condition and function(player) return player:getPawAndFurRank() >= 3 end or nil)
		travelKeyword:addChildKeyword({'yes'}, StdModule.travel, {npcHandler = npcHandler, premium = false, cost = cost, destination = destination})
		travelKeyword:addChildKeyword({'no'}, StdModule.say, {npcHandler = npcHandler, text = 'Maybe another time.', reset = true})
end

addTravelKeyword('west', 'the west end of Port Hope', 7, Position(32558, 32780, 7))
addTravelKeyword('centre', 'the centre of Port Hope', 7, Position(32628, 32771, 7))
addTravelKeyword('darama', nil, 30, Position(32987, 32
729, 7))
addTravelKeyword('center', 'the centre of Port Hope', 0, Position(32628, 32771, 7))
addTravelKeyword('chor', nil, 30, Position(32968, 32799, 7), true)
addTravelKeyword('banuta', nil, 30, Position(32826, 32631, 7), true)
addTravelKeyword('mountain', nil, 30, Position(32987, 32729, 7), true)
addTravelKeyword('mountain pass', nil, 30, Position(32987, 32729, 7), true)
-------------------------------------------------------
EO NPC NÃO  Responde nada
![Captura de Tela (184)](https://user-images.githubusercontent.com/68012933/170465148-37cbdd48-047b-426d-a7f4-51a42dd9597a.png)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
As we spoke on Discord, this is not an issue. To travel to Chor, Banuta and Mountain, your character need to have Paw and Fur Rank >= 3 (set storage 2500 to >=20).
