### ISSUE TITLE
Speed Imbuement wrong value *imbuements.xml

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#609]
### Priority

Low

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

Value on speed "imbuements.xml" is wrong, should be 20/30/60 
+ 
this imbu should not be able to applied to boots that already have a native speed increase except for pair of soulwalkers and pair of soulstalkers

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
The bonus information is incorrect, according to every wiki site, the correct bonus is 10/15/30.

**Comment by rigis1** [comment]
> 

look at mounts.xml to verify value *2 difference.
I checked my changes and before update was +5 +7 +15 and after +10 +15 +30. 
btw It was correct in the oldest file history.

**Comment by guispiller** [comment]
> > 
> 
> look at mounts.xml to verify value *2 difference. I checked my changes and before update was +5 +7 +15 and after +10 +15 +30. btw It was correct in the oldest file history.

Allright, sorry haven't seen that.
Thanks for your report.
I'll fix that, and the items that can be imbued with.
Also, are you sure that Soulwalkers and Soulstalkers can be imbued with speed bonus? On wiki sites it says that they can't, but i'm not sure.

**Comment by rigis1** [comment]
> Also, are you sure that Soulwalkers and Soulstalkers can be imbued with speed bonus? On wiki sites it says that they can't, but i'm not sure.

I'm also not sure, I only found this source of information  [wiki](https://tibia.fandom.com/wiki/Imbuing?so=search#:~:text=Cannot%20be%20applied,of%20Soulstalkers)
