### ISSUE TITLE
[MAP] Wrong item and tiles on map - Threatened Dreams Quest

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#614]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

The request in a certain part request you to freedom some fairies, but one of the fairies is not on local, instead there is **a test wand of voodoo.**

**Position: 33621, 32214, 8**
![image](https://user-images.githubusercontent.com/11935651/170848137-4e9fe23b-c87e-42bb-ae12-8ca6e39da9af.png)

The correct item ID of the Fairy is:
Client ID: **25796**

Another part of the quest requires the player to swimming to an isle, but some of the IDs around the isle doesn't allow swimming:
**Position: 33547, 32250, 7**
![image](https://user-images.githubusercontent.com/11935651/170887033-218eff92-c08b-45e4-bf35-3ac3e33a18a1.png)

**The correct ID should be 632**

In this location **Position: 33496, 32196, 7**
There is a ferns, this item must be removed, the location is actually to be clean, it will have an event that will create a raven bush during the night and remove on sunrise.
![image](https://user-images.githubusercontent.com/11935651/171063971-c3842a29-b997-4e11-b4cb-f6a45e99f242.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
