### ISSUE TITLE
[MAP] Wrong IDs on Tiles map of Feyrist

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#616]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

The problem is more cosmetic, maybe due to a wrong convertion, the IDs of some tiles in this location is wrong, making the map looks weird:

Location: **Position: 33620, 32206, 9**
![image](https://user-images.githubusercontent.com/11935651/170870781-e38d273b-b816-4c27-9f82-df8ea3021d70.png)

How it should be:
![image](https://user-images.githubusercontent.com/11935651/170870804-ce7b0491-7577-41f3-bed4-5eef4fda790c.png)

Location: **Position: 33616, 32195, 9**
![image](https://user-images.githubusercontent.com/11935651/170870839-c80b14c5-b606-4f32-adfb-bcf0e434b30e.png)

How it should be:
![image](https://user-images.githubusercontent.com/11935651/170870852-702e8371-6688-4bcb-a9d9-850067f4548a.png)

Location: **Position: 33622, 32174, 9**
![image](https://user-images.githubusercontent.com/11935651/170870934-ad00359c-bedf-4238-82e0-e1d9c4d6dce8.png)

How it should be:
![image](https://user-images.githubusercontent.com/11935651/170871011-1cb1fb07-281d-4abf-b9fa-d1571c7a6346.png)

There is another location but I was not able to find how it should be, follow the list:
**Position: 33621, 32187, 8**

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
