### ISSUE TITLE
[BUG] buy shoping in bags

### ISSUE THREAD

**Issue by Alissonlv123** [opentibiabr/otservbr-global#620]
### Priority

Medium

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [X] Other

### What happened?

Bom Vamos começar com o mais dificil para vcs, então recentemente eu tava testando tudo do servido e enfim acabei encontrando varios bugs tem mais vou reportando com calma pra vcs, enfim buy shoping in bag não funciona até funciona compra os items mais não vem dentro da bag como pode ver nas prints 
![Sem_titulo](https://user-images.githubusercontent.com/68012933/171014604-3f3948c8-ace4-4e7d-8c65-16267d27e9fd.png)

era pra vim os items dentro da shoping bag mais não vem vem assim 
![Captura de Tela (230)](https://user-images.githubusercontent.com/68012933/171015357-3daa4bf2-eb20-4d41-bdc5-7f32dc808f44.png)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by murilo09** [comment]
this bug is still happening
