### ISSUE TITLE
[BUG] monster lion knight, lion warlock

### ISSUE THREAD

**Issue by Alissonlv123** [opentibiabr/otservbr-global#621]
### Priority

Medium

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [X] Other

### What happened?

Então os monstros Lion warlock e lion knight não era pra atacar os players mais eles estão tarado pelos players lion commander e lion archer não estão atacando os players mais só eles
![unknown (2)](https://user-images.githubusercontent.com/68012933/171015859-c9b6f50c-a8b9-4d10-9d8e-a27cf286679f.png)

 como podemos ver na print estão bugadinhos mais são so eles em cada monstro estão corretos as faction aliadas e as factions inimigas

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
You can test https://github.com/opentibiabr/canary/pull/473? @Alissonlv123
