### ISSUE TITLE
[MAP] Missing depots in Edron Guildhalls

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#626]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

Depot is missing in guildhalls in Edron:

**Position: 33236, 31878, 8**
How it should be:
![image](https://user-images.githubusercontent.com/11935651/171599086-3b84f1d0-6c90-4d34-9166-10de544bfc22.png)

**Position: 33279, 31824, 8**
How it should be:
![image](https://user-images.githubusercontent.com/11935651/171599914-9a179288-d054-4a5c-9723-6ace4d7a439a.png)

**Position: 33333, 31768, 8**
How it should be:
![image](https://user-images.githubusercontent.com/11935651/171600440-21f794a0-e21d-4af3-8313-9c19bc1ec198.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
