### ISSUE TITLE
[MAP] Feyrist missing protection zones in depots & training area

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#627]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

The depots in Feyrist is not in protection zone.
Depots
**Position: 33491, 32221, 6**
![image](https://user-images.githubusercontent.com/11935651/171606889-ee1f39f2-e3ef-405b-96a2-33b8a8706266.png)

![image](https://user-images.githubusercontent.com/11935651/171606914-7219d571-be7b-427e-a46b-6e421e399c87.png)

Training area:
**Position: 33484, 32228, 8**

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
