### ISSUE TITLE
[MAP] A border item is covering a quest item

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#628]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

During the workflow of the Threatened Dream quest, there is a part where you need to grab a herb, this herb only shows up during the night.

But while the herb is being created a border on the map is still covering the herb, making it impossible to grab.
A simple solution would be by just removing this border (Forest Floor) from the map. I have done it by command /r and I was able to move forward with the quest.

**Position: 33496, 32196, 7**
![image](https://user-images.githubusercontent.com/11935651/171607672-29c79d29-23cb-4521-a872-94ad4968b85f.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed issue, the updated global map will be released after merge pull requests about quests.

**Comment by majestyotbr** [comment]
Updated otservbr-global map in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
