### ISSUE TITLE
Gaffir Wall

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global#640]
### Priority

Missing Content

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What is missing?

![image](https://user-images.githubusercontent.com/13306169/172989451-a1ae1c80-5d97-4364-8332-34ff16144888.png)

Need to add any script on wall client id: 5062 to prevent monsters pass and attacking behind her.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alissoncmachado** [comment]
Analyzing the possible IDs of the burning wall (vertical), I got the following result:
ID = 5062, player passes, can use magic above the item, but also passes creatures;
ID = 6288, impossible to pass;
ID = 32021, player passes, creatures do not, but does not cast spells above the item.

The solution using stepin and stepout with id's = 32021 and 5062.

I don't know if I'm doing it right, but I'm not full on github... Sorry if I'm doing it wrong.

![Gaffir Wall](https://cdn.discordapp.com/attachments/965214901566070826/991466943674601482/Gaffir_Parede.gif)

data/scripts/movements/quests/grave_danger/cobra_bastion/firewall_gaffir.lua

```
local above = {[32021] = 5062}
local outside = {[5062] = 32021}

-- onStepIn
local gaffirwall = MoveEvent()

function gaffirwall.onStepIn(creature, item, position, fromPosition)
	if not above[item.itemid] then
		return true
	end

	local player = creature:getPlayer()
	if not player or player:isInGhostMode() then
		return true
	end
	item:transform(above[item.itemid])
end

gaffirwall:type("stepin")

for index, value in pairs(above) do
	gaffirwall:id(index)
end
gaffirwall:register()

gaffirwall = MoveEvent()

function gaffirwall.onStepOut(creature, item, position, fromPosition)
	if not outside[item.itemid] then
		return false
	end

	local player = creature:getPlayer()
	if not player or player:isInGhostMode() then
		return true
	end

	item:transform(outside[item.itemid])
	player:setSpecialContainersAvailable(false, false)
	return true
end

gaffirwall:type("stepout")
for index, value in pairs(outside) do
	gaffirwall:id(index)
end
gaffirwall:register()
```

**Comment by alissoncmachado** [comment]
Chance name item in items.xml

	<item id="32021" name="burning wall"/>
	<item fromid="32022" toid="32035" name="addled egg">
		<attribute key="weight" value="100"/>
	</item>
