### ISSUE TITLE
(NPC) say trade to yasir causes a client crash

### ISSUE THREAD

**Issue by antoniovikernes** [opentibiabr/otservbr-global#650]
### Priority

Low

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

When you say Trade to NPC yasir it cause a client crash.!
tried with other npc and i haven't found another one with the same problem.

![a](https://user-images.githubusercontent.com/8410034/173402854-09a28508-a780-400e-8b9a-f495289c3198.PNG)
![b](https://user-images.githubusercontent.com/8410034/173402864-138595b4-166a-42b3-be45-9e9cf9fe88b1.PNG)
![c](https://user-images.githubusercontent.com/8410034/173402868-c211731f-6936-42cb-80d8-f9f41c86212e.PNG)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
This issue was fixed on the last commit from canary repo, please test this: https://github.com/opentibiabr/canary/commit/493e46f4246b5d2b6b016a35b25e4812d2b74c1e
