### ISSUE TITLE
Create custom item

### ISSUE THREAD

**Issue by lewalmeida** [opentibiabr/otservbr-global#652]
### Priority

Enhancement

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What is missing?

Guys, how can i create a custom item using this new appearences.dat? i know how to put on client but when the game load. I cant buy this item in any NPC, i add the item on item.xml/npc.xml, but the item still broken.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcosvf132** [comment]
- Following this simple tutorial you can edit your client and add new customized items/outfits/effects. 
> https://majestyotbr.gitbook.io/opentibiabr/projects/canary

- Doing that, your can just /i on it. If you did set name on the item throught the assets editor, you can even /i by it's name.
