### ISSUE TITLE
(CRASH) at the end of the imbuement counter

### ISSUE THREAD

**Issue by antoniovikernes** [opentibiabr/otservbr-global#656]
### Priority

Critical

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

I've tried it many times
when the imbuement time counter reachs 0 it crashes the server!

![CRITICAL](https://user-images.githubusercontent.com/8410034/174351608-3847a145-74d6-4915-bc17-4f0b8ce32e30.PNG)
![crash](https://user-images.githubusercontent.com/8410034/174352004-84c6090b-cb94-4397-89f9-05ee14ec9336.PNG)

its basic strike

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Just tested here 3 times with the exact knight axe, basic strike on canary main+otbr main and it's not crashing.
You have updated canary and datapack?

**Comment by travisani** [comment]
Normal here, nothing happens, can you share the crash log?
