### ISSUE TITLE
Oberon Stop working after the second stage 

### ISSUE THREAD

**Issue by Mimsol** [opentibiabr/otservbr-global#663]
### Priority

Low

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

Grand Master Oberon stop work after the second stage he get Imortal and after some time when you don /r oberon the server get crashed 

Latest Updates Otservbr datapack and Canary (Source) 1.3.1

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Could you please update your datapack and source and try it again? I just tested it and it's working fine.
