### ISSUE TITLE
Missing Npc For Hunting Task in Prey Window Walter Jaeger

### ISSUE THREAD

**Issue by Koras443** [opentibiabr/otservbr-global#664]
### Priority

Medium

### Area

- [X] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

There it's No Npc For Hunting Task To Change Hunting Task Points For The Addon Or Mount Or Throphy
 His Name it's Walter Jaeger

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Koras443** [comment]
did anyone maybe got that npc? ;P

**Comment by AdversarioV** [comment]
I have same issue, anyone knows about this?
