### ISSUE TITLE
some chests from chest.lua stopped working

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#665]
### Priority

Critical

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

Due last changes (#641) of structure, some chests from chest.lua stopped working.
Update: 
now when i tested more of them problem isn't that big as i thought
List that i tested and not working:
`6100, 6083, 6084, 6079, 6020, 6001, 6005`

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sircurse** [comment]
hi @rigis1 , can you specify some of the chests that are not working?

**Comment by rigis1** [comment]
> hi @rigis1 , can you specify some of the chests that are not working?

sure, i'm testing which one are not working, i'll update my post

**Comment by sircurse** [comment]
@rigis1, can you check if you have updated your datapack accordingly? I have tested some of the chests you are posting here, and all of them I have tested so far is working as expected.

**Comment by rigis1** [comment]
> @rigis1, can you check if you have updated your datapack accordingly? I have tested some of the chests you are posting here, and all of them I have tested so far is working as expected.

I'll set up new machine and run some tests.

**Comment by rigis1** [comment]
@sircurse i downloaded your branch tree "Quest-storages-restructuring" and all works good, but on main branch otservbr-global is not working. I'll done some more tests.

**Comment by sircurse** [comment]
@rigis1, weird because I have tested on main

**Comment by rigis1** [comment]
I found out from which point the problem occurs for me. #586 (4f2fcae6a22e860928ea330b9ee1b116dbb57fdd)
Now i'll done some more test to find out what's causing.

**Comment by rigis1** [comment]
@[sircurse](https://github.com/sircurse)
I found out whats cousing this problem, in [6095] `itemPos = {x = 33080, y = 32014, z = 13},` if i fixing this value, problem disappear. 
[Problem solved]

**Comment by majestyotbr** [comment]
@rigis1 did you updated your map? With PR 586, 594 and 633 the map was updated, i said in the pull requests.

Updated otservbr-global map available in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map

**Comment by rigis1** [comment]
@majestyotbr
i didn't updated map and that was the issue here, sorry

**Comment by majestyotbr** [comment]
@rigis1 
No problem. We will change how to update the map without increase the repo history.
