### ISSUE TITLE
Bug on "Move up"

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global#666]
When you try to move up something the mensage "sorry not is possible " appear and the function doenst work

a video to explain it better:

https://www.youtube.com/watch?v=VmkDdtHeeFM

**Comment by FakeShinoda** [comment]
Confirmed. Any item stackable doesn't matter the count, can't be moved to a previous container.

**Comment by HeberPcL** [comment]
Bug has already been fixed.
