### ISSUE TITLE
Npc spectulus error in callback

### ISSUE THREAD

**Issue by sebaz54321** [opentibiabr/otservbr-global#669]
### Priority

Critical

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

Hi, i have an issue. Wen the player talk with npc spectulus (hi>>mission>> yes) i got an error in console:
[2022-29-06` 20:07:54.179] [error] Lua script error:
scriptInterface: [Scripts Interface]
scriptId: [C:\Users\48663\Desktop\otservbr-global-main2\usus\data\npc\spectulus.lua:callback]
timerEvent: []
 callbackId:[]
function: []
error [data/npclib/npc_system/npc_handler.lua:582: attempt to compare number with boolean
stack traceback:
        [C]: in function '__lt'
        data/npclib/npc_system/npc_handler.lua:582: in function 'say'
        ...esktop\otservbr-global-main2\usus\data\npc\spectulus.lua:348: in function 'callback'
        data/npclib/npc_system/npc_handler.lua:415: in function 'onSay'
        ...esktop\otservbr-global-main2\usus\data\npc\spectulus.lua:55: in function `<...esktop\otservbr-global-main2\usus\data\npc\spectulus.lua:54>]

Also when player resay  agin "yes" then he geting  exp  again.

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
This issue was fixed and already merged on: https://github.com/opentibiabr/otservbr-global/pull/642

Please, update your datapack.
![image](https://user-images.githubusercontent.com/11639062/176514107-daeb174a-01cc-4acf-962b-6fdfeb6bea50.png)

**Comment by sebaz54321** [comment]
i have actual datpack, but still i getiing error

**Comment by brunorf99** [comment]
sebaz, when was the last time that you compiling your canary? I would like know cause before than i compile mine, that npc was working normal, after the compiling, i had this problema too (still with). my last compiling was 26/06

**Comment by rigis1** [comment]
@sebaz54321 can you try this? its my old spectulus.lua that fix spectulus before #642
[spectulus.zip](https://github.com/opentibiabr/otservbr-global/files/9028859/spectulus.zip)

**Comment by guispiller** [comment]
Guys, this error has nothing to do with Canary, it's a NPC issue, on datapack. Fixed on PR #642

**Comment by rigis1** [comment]
> Guys, this error has nothing to do with Canary, it's a NPC issue, on datapack. Fixed on PR #642

yup i can confirm that #642 solved this issue

**Comment by guispiller** [comment]
Sorry about that, my mistake.
The issue persists, when saying yes after mission, some problem in addEvent(releasePlayer, 1000, npc, creature) function. Working on a fix, issue reopened.

**Comment by guispiller** [comment]
Pull request opened, please test it if you can.
