### ISSUE TITLE
Market Change Name Bug

### ISSUE THREAD

**Issue by Heronbeluci** [opentibiabr/otservbr-global#673]
Ao comprar o changename no market a input de digitar o novo nome fecha antes de dar tempo de digitar... concluindo a transação sem você ter colocado um nome.

**Comment by EleanorRigby1** [comment]
I confirm it, it also takes away your coins

**Comment by Sargitarium** [comment]
Alread Test here... and work fine to me.... After buy apear Screan animated... make one click... and wait... Label to choose name continue open.... you edit name and click OK.... Your character logout and work....

**Comment by beluci-dev** [comment]
I've tested on client 10.0...

**Comment by Lycanzito** [comment]
Tested on client 11, it take your coins before you can choose a name, also you have to pay twice..

Also, if you are outside the protection zone, it take yours coins either, and you cant change your name there.

**Comment by chriscarp** [comment]
change:

    player:removeCoinsBalance(offerPrice)
    GameStore.insertHistory(player:getAccountId(), GameStore.HistoryTypes.HISTORY_TYPE_NONE, offer.name, (offerPrice) * -1)

for:

    if not (offer.type == GameStore.OfferTypes.OFFER_TYPE_NAMECHANGE) then
        player:removeCoinsBalance(offerPrice)
        GameStore.insertHistory(player:getAccountId(), GameStore.HistoryTypes.HISTORY_TYPE_NONE, offer.name, (offerPrice) * -1)
    end
	
	
	
add:

    db.query("UPDATE accounts SET coins = coins - 250 WHERE id = " .. player:getAccountId())
    GameStore.insertHistory(player:getAccountId(), GameStore.HistoryTypes.HISTORY_TYPE_NONE, "Name Change.", -250)


below:

    message = "You have successfully changed you name, relogin!"

**Comment by Johncorex** [comment]
**The bug remains on client 10x, client 12 works normally.**
