### ISSUE TITLE
[MAP] Missing elements 

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#676]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?
(Wagons declareted in #675)
Wagons aid can be removed on positions:
```
{x = 32578, y = 31488, z = 9}, -- start
{x = 32577, y = 31508, z = 9}, -- bridge stage after completion
{x = 32628, y = 31514, z = 9}, -- rubble stage after completion
{x = 32599, y = 31505, z = 13}, -- city's entrance
{x = 32603, y = 31339, z = 11}, -- location exit
{x = 32700, y = 31452, z = 13}, -- corner maze room
{x = 32699, y = 31492, z = 11}, -- coal wagon logic
{x = 32688, y = 31471, z = 13}, -- maze logic update map
{x = 32570, y = 31508, z = 9}, -- bridge stage
{x = 32615, y = 31514, z = 9}, -- rubble stage
{x = 32651, y = 31508, z = 10}, -- broken bridge
{x = 32633, y = 31508, z = 10}, -- stairs
{x = 32693, y = 31502, z = 11}, -- wagon station
{x = 32688, y = 31472, z = 13}, -- maze
{x = 32683, y = 31508, z = 10}, -- ladder
{x = 32548, y = 31408, z = 11}, -- infested tavern
{x = 32700, y = 31449, z = 15}, -- npc tehlim
{x = 32662, y = 31496, z = 13}, -- mushroom quest
{x = 32703, y = 31506, z = 12}, -- small tunnel with golems
{x = 32720, y = 31488, z = 15} -- troll tribe's hideout
```
Chests aid change to 2001 need in positions due changes in #687:
```
{x = 32796, y = 31226, z = 7}
{x = 32795, y = 31185, z = 7}
{x = 32701, y = 31082, z = 8}
```
### Position: 33310, 31183, 7 insted aid 3244 should be uid 3244
![image](https://user-images.githubusercontent.com/22598283/177070031-731fd506-a298-4cf0-9e96-1828115837e1.png)
### Position: 32745, 31399, 14 missing wall
![2022-07-03 (5)](https://user-images.githubusercontent.com/22598283/177030102-15c62c65-7928-49fb-97a2-96798ea79be2.png)
![2022-07-03 (8)](https://user-images.githubusercontent.com/22598283/177030118-66fcd7f5-3081-4af1-bc1d-80695206ecec.png)
### Position: 32743, 31398, 13 missing wall
![2022-07-03 (4)](https://user-images.githubusercontent.com/22598283/177030145-e6b13aa6-3c42-464f-96cb-5c5f070cc2e9.png)
![2022-07-03 (7)](https://user-images.githubusercontent.com/22598283/177030147-46f2ef44-a452-4486-b0b5-8d8a06a411ba.png)
### Position: 32688, 31471, 13 missing wagon
![2022-07-03 (3)](https://user-images.githubusercontent.com/22598283/177030188-fd47efde-182d-4409-a7ad-ac078fac6658.png)
![2022-07-03 (2)](https://user-images.githubusercontent.com/22598283/177030189-5f6d9160-c4ba-4335-bf52-8cbed420f768.png)
### Position: 32570, 31504, 10 missing water
![2022-07-03 (1)](https://user-images.githubusercontent.com/22598283/177030255-71b348dd-6389-4d66-aa73-c3f4e880b664.png)
![2022-07-03 (6)](https://user-images.githubusercontent.com/22598283/177030258-370eb962-226b-45e5-bf50-1e1f46edfcec.png)
### Position: 33161, 31265, 10 wrong doors
![2022-07-03 (6)](https://user-images.githubusercontent.com/22598283/177030485-d7896eb3-ec84-4709-bd52-a82dab1fc1af.png)
![2022-07-01](https://user-images.githubusercontent.com/22598283/177030490-d9b7bc26-1cd4-44b2-9afa-0f7931df6d3c.png)
### Position: 32027, 31444, 6 wrong door id, it's locked but it should be open

![2022-07-03 (7)](https://user-images.githubusercontent.com/22598283/177030589-6a7bb260-027f-4279-af27-17a0bc70ff8a.png)
### Position: 32168, 31941, 9 wrong id pick
![2022-07-03 (9)](https://user-images.githubusercontent.com/22598283/177030860-40837ab0-2df4-4d4b-97d8-51defd0b6055.png)
![2022-07-03 (8)](https://user-images.githubusercontent.com/22598283/177030863-9316118c-55fc-4a9c-8342-a3aa148db615.png)
### Position: 32180, 31933, 11 wrong door
![2022-07-03 (10)](https://user-images.githubusercontent.com/22598283/177030892-ed012a41-7941-4b3a-a117-20ee9902ee64.png)
![2022-07-03 (11)](https://user-images.githubusercontent.com/22598283/177030922-4edc1581-73e5-4665-90bd-8f3eadf400be.png)
### Position: 32785, 32696, 8 missing hole 
![2022-07-03 (12)](https://user-images.githubusercontent.com/22598283/177031107-a998b65a-61a6-4267-8c58-185d1c2387cc.png)
![2022-07-03 (13)](https://user-images.githubusercontent.com/22598283/177031119-cf94c220-9768-49c3-ba46-b9b9033a4737.png)
### Position: 32949, 31810, 7 wrong corpses
![2022-06-28](https://user-images.githubusercontent.com/22598283/177031234-1e7d99d6-338a-4d46-b991-aba0a04f6de8.png)
![2022-07-03 (14)](https://user-images.githubusercontent.com/22598283/177031262-feeab68a-2afe-4d31-ad67-5cd808e6f828.png)
### Position: 32090, 31145, 0 wrong tile
![2022-07-03 (16)](https://user-images.githubusercontent.com/22598283/177031426-84aa02c3-f791-4cfb-aca1-dffe124b4431.png)
![2022-07-03 (15)](https://user-images.githubusercontent.com/22598283/177031427-652ee865-d2e3-40d9-9705-616be0301f8d.png)
### Position: 33266, 32422, 7 feathers missing
![2022-07-04 (4)](https://user-images.githubusercontent.com/22598283/177059186-bd0c7288-7973-4b1b-957f-d46f783eb5bc.png)
![2022-07-04 (1)](https://user-images.githubusercontent.com/22598283/177059201-b9f876fe-d9a8-480f-b6be-029a70e79e6c.png)
### Position: 33258, 32401, 7 remove feathers
![2022-07-04](https://user-images.githubusercontent.com/22598283/177059238-db237621-14e9-4cb4-beda-e8e28f6f0167.png)
### Position: 32696, 31082, 8 missing oven
![2022-07-04 (4)](https://user-images.githubusercontent.com/22598283/177063265-1f0fe853-9b05-4c8e-b4b6-85beb626f45c.png)
![2022-07-04 (5)](https://user-images.githubusercontent.com/22598283/177063286-ae8a40a3-47db-4a32-9b5f-a8e1187cb711.png)
### Position: 32860, 32517, 11 wrong door
![image](https://user-images.githubusercontent.com/22598283/177091493-f99f9261-5e99-4b75-938f-d83f0b825734.png)
![image](https://user-images.githubusercontent.com/22598283/177091571-1561c2f8-c937-4f4d-bb81-f92e06a8426b.png)
### Position: 32305, 31817, 7 wrong door id, it's locked but it should be open
![image](https://user-images.githubusercontent.com/22598283/177244256-ba63115a-3a1e-456b-b1b3-c4da6a441b07.png)
### Position: 32672, 31231, 11 wrong door id, it's locked but it should be open
![image](https://user-images.githubusercontent.com/22598283/177447780-83b2b93f-143a-4f52-8e42-e5d10eec2300.png)
### Position: 32698, 31227, 11 wrong door id, it's locked but it should be open
![image](https://user-images.githubusercontent.com/22598283/177447923-5c81b49b-d97d-4b42-8d7f-2b9b5e9cb9ca.png)
### Position: 32698, 31235, 11 wrong door id, it's locked but it should be open
![image](https://user-images.githubusercontent.com/22598283/177447983-aa5628de-78f6-4a91-ad81-25ec11033209.png)
### Position: 32621, 31404, 10 aid 2001 missing
![image](https://user-images.githubusercontent.com/22598283/177451109-c7c3862b-c293-40d6-bdb8-ac3f698227a2.png)
### Position: 32908, 32112, 7 wrong door id, it's open but it should be closed
![image](https://user-images.githubusercontent.com/22598283/177472264-ae1e5e29-4dd8-44f5-abf0-aa1b6a9fbc20.png)
### wrong skeleton corpses, should be 4285
```
Position: 32203, 31272, 10
Position: 32509, 32181, 13
```
### Position: 33154, 31297, 3 chest with tome of knowledge missing
![image](https://user-images.githubusercontent.com/22598283/177889436-b808d952-2e13-439c-8bab-8bb7ac3230d9.png)
![image](https://user-images.githubusercontent.com/22598283/177889384-296632b1-8203-40b1-9485-61d5f93818e5.png)
### Position: 33043, 31288, 5  Position: 33043, 31289, 5  Position: 33043, 31290, 5  bamboo wall missing
![image](https://user-images.githubusercontent.com/22598283/177890077-376ba5c2-3d35-4d7c-a6b1-82e8a7c26935.png)
![image](https://user-images.githubusercontent.com/22598283/177890299-3e2756ea-8dea-4756-8956-3c91fbee2bda.png)
### Position: 33047, 31295, 7 wrong door, should be quest door
![image](https://user-images.githubusercontent.com/22598283/177890447-a1efe78e-638d-4983-a53b-5168006868ee.png)
![image](https://user-images.githubusercontent.com/22598283/177890506-21996f89-b534-4ba8-9ae5-0d5ea27ce760.png)
### Position: 33345, 31117, 7 visual difference
![image](https://user-images.githubusercontent.com/22598283/178090043-0605efcf-1489-44d7-b843-cf0cc1fdea75.png)
![image](https://user-images.githubusercontent.com/22598283/178090082-e6e61141-16eb-4268-9682-0560bf1f7828.png)

### What OS are you seeing the problem on?
Windows 10
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Updated otservbr-global map available in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map
