### ISSUE TITLE
Ape City

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#678]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

"Ape City Quest"
NPC "Hairycles" should allow you to open door 

10:29 You see a closed door.
Client ID: 1698, Action ID: 51068
Position: 32781, 32910, 8

in order to get  whisper moss

but "10:29 The door seems to be sealed against unwanted intruders."

![image](https://user-images.githubusercontent.com/107372680/177057336-13726c32-8efe-4f28-abf6-6b62bf9a0d8f.png)

Even if i use my GOD to go thru the door, it doesn't matter if i have the whisper moss on my backpack

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
ill try to fix it

**Comment by rigis1** [comment]
You can test it. I'll revised this quest till the end later.
- you can see mine issue with quests at the end here opentibiabr/canary#618

**Comment by AdversarioV** [comment]
> You can test it. I'll revised this quest till the end later.
> 
> * you can see mine issue with quests at the end here [Quests that need to be developed or revised #276](https://github.com/opentibiabr/canary/issues/618)

This did not solve the quest, i still can't open the door and cannot have hairycless advance on the quest

**Comment by rigis1** [comment]
> This did not solve the quest, i still can't open the door and cannot have hairycless advance on the quest


hmm, on my server it works fine, i need more details, take some screenshots and server log if errors occur.

**Comment by AdversarioV** [comment]
> > This did not solve the quest, i still can't open the door and cannot have hairycless advance on the quest
> 
> hmm, on my server it works fine, i need more details, take some screenshots and server log if errors occur.

No errors on the console, i have the same exact issue as on the pictures described before

**Comment by rigis1** [comment]
```
Client ID: 1698, Action ID: 51062
Position: 32781, 32910, 8
Client ID: 2469, Action ID: 2000, Unique ID: 6102
Position: 32782, 32910, 8
```

**Comment by AdversarioV** [comment]
> ```
> Client ID: 1698, Action ID: 51062
> Position: 32781, 32910, 8
> Client ID: 2469, Action ID: 2000, Unique ID: 6102
> Position: 32782, 32910, 8
> ```

Ok the chest does have the same ID and it works, however the door does have a different ID, i added the lines you mentioned on the file....however the door remains as 
22:00 You see a closed door.
Client ID: 1698, Action ID: 51068
Position: 32781, 32910, 8

**Comment by rigis1** [comment]
> Ok the chest does have the same ID and it works, however the door does have a different ID, i added the lines you mentioned on the file....however the door remains as
> 22:00 You see a closed door.
> Client ID: 1698, Action ID: 51068
> Position: 32781, 32910, 8

problem is in your door_quest.lua
if you edit door_quest.lua as i did, problem shouldn't appear

**Comment by AdversarioV** [comment]
> > Ok the chest does have the same ID and it works, however the door does have a different ID, i added the lines you mentioned on the file....however the door remains as
> > 22:00 You see a closed door.
> > Client ID: 1698, Action ID: 51068
> > Position: 32781, 32910, 8
> 
> problem is in your door_quest.lua

You were right i messed something up, it's working now please merge
