### ISSUE TITLE
The explorer society

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#679]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

On mission 13 of "The explorer society quest"

![image](https://user-images.githubusercontent.com/107372680/177057495-a7c2c7f2-df29-4e5e-94fd-5e554eecee05.png)

When you try to use the Spectral stone according to the RL tibia wiki on both headquarters of the explorer society

![image](https://user-images.githubusercontent.com/107372680/177057524-aebe4587-0f11-47a4-9c81-a80d3fb1cc1d.png)

You are supposed to use them in here 

![image](https://user-images.githubusercontent.com/107372680/177057542-ef9c46e8-d305-4144-a0cb-4c696967499d.png)

And here

![image](https://user-images.githubusercontent.com/107372680/177057700-e29cac81-1134-4445-9aca-960a11ce7f69.png)

This is from the RL tibia wiki

![image](https://user-images.githubusercontent.com/107372680/177057692-fbcf01f3-fd7e-457b-9416-eb563f006ab1.png)

Please do tell me if im doing something wrong

Problem: It doesn't do anything....and when i step on the carving i get pushed back

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
You can test #692 to see if it works.
