### ISSUE TITLE
Liquid black

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#680]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

This happens when you find the coordinates on the chest on gray island, you sit down on the chair and use the machine and you do get teleported to Spectulus

![image](https://user-images.githubusercontent.com/107372680/177057974-324005be-661e-4055-a16e-2d69e6c9e3ed.png)

but when you talk to him and say "Machine" nothing happens

![image](https://user-images.githubusercontent.com/107372680/177057952-bc5fe921-1513-40b6-919e-e5cf9b8adc0a.png)

![image](https://user-images.githubusercontent.com/107372680/177057939-06821a4f-6eda-4edf-b35f-3bb1df97195e.png)

Can't continue quest

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
isn't #672 fix this?

**Comment by AdversarioV** [comment]
> isn't #672 fix this?

Will try

**Comment by AdversarioV** [comment]
> isn't #672 fix this?

This solved the issue, you can merge, however it did not add any entrance to my quest log, even if it did say my quest was updated, but the root cause of this issue is solved

**Comment by rigis1** [comment]
fixed
