### ISSUE TITLE
The Ice islands quest (Ecological Terrorism)

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#681]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

In the second mission of the ice island quests

![image](https://user-images.githubusercontent.com/107372680/177058144-da80ec06-f2ac-450c-afaf-704f0d25c985.png)

when you try to use 

![image](https://user-images.githubusercontent.com/107372680/177058154-b92ae1e3-a518-4d8c-b3f3-1ab9ee16f9a7.png)

on

![image](https://user-images.githubusercontent.com/107372680/177058163-5eb21f25-35ff-4d57-a4c5-efdd7eb449fe.png)

nothing happens

![image](https://user-images.githubusercontent.com/107372680/177058174-ea2d68d3-f901-49b7-a029-775b11f3fa32.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
you can test #689

**Comment by AdversarioV** [comment]
> you can test #689

Yes, this fixed it
