### ISSUE TITLE
In Service of Yalahar

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#682]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

On the third mission of Yalahar

![image](https://user-images.githubusercontent.com/107372680/177058259-4ba8976c-41ad-4aae-9b6c-e6d7145f2551.png)

I need to open a door and retrieve some notes and read them

![image](https://user-images.githubusercontent.com/107372680/177058284-83063d0e-d031-4e7a-b4a6-ca11018a2b50.png)

![image](https://user-images.githubusercontent.com/107372680/177058291-37075f86-338a-4c3e-9617-3c9244fd90b2.png)

Got a bag with this

![image](https://user-images.githubusercontent.com/107372680/177058301-49a6cf37-2769-4024-8c48-89c12dd47342.png)

Notes are unreadable (Nothing happens when you read them)

![image](https://user-images.githubusercontent.com/107372680/177058312-93f979f1-0063-4d98-82bd-ba34d991835f.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
You can test #687 to see if it helps you.

**Comment by AdversarioV** [comment]
> You can test #687 to see if it helps you.

Will try and let you know

**Comment by AdversarioV** [comment]
> You can test #687 to see if it helps you.

Yes, this solved the issue
