### ISSUE TITLE
Threatened Dreams (The Swan Maiden)

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#684]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

All the location for the feathers work except one

![image](https://user-images.githubusercontent.com/107372680/177058666-dcf86b43-7b15-44f8-a197-58d0949a4ffc.png)

![image](https://user-images.githubusercontent.com/107372680/177058729-dcea03b7-ef97-4eb6-8405-19c02ef9aefd.png)

Doesn't do anything when clicked

![image](https://user-images.githubusercontent.com/107372680/177058715-416bb8e2-7d31-4ce4-8070-29329387dbe9.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
Go here 
```
00:19 You see a dustbin.
Client ID: 2526
Position: 33259, 32401, 7
```
probably map issue related

**Comment by AdversarioV** [comment]
> Go here
> 
> ```
> 00:19 You see a dustbin.
> Client ID: 2526
> Position: 33259, 32401, 7
> ```
> 
> probably map issue related

This solved the issue
