### ISSUE TITLE
Threatened Dreams ( Troubled Animals)

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#685]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

After collecting all 5 feathers

![image](https://user-images.githubusercontent.com/107372680/177059141-1216bcba-8732-4f56-8352-e1c5888e27c8.png)

Saying "Mission" to NPC "A Swan"

i get the following 

![image](https://user-images.githubusercontent.com/107372680/177059164-400b3f0b-380a-46f6-aedd-919baefa5b88.png)

Seems to be related to the previous quest storage structure (curse)

local ThreatenedDreams = Storage.Quest.U11_40.ThreatenedDreams

![image](https://user-images.githubusercontent.com/107372680/177059182-b37b1086-d0b0-4be1-ada9-6a9b594ad6cd.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
i tested this phase on my server and don't have issue here
check /get GOD, 45752

**Comment by AdversarioV** [comment]
> i tested this phase on my server and don't have issue here check /get GOD, 45752

will do

got this 18:08 The storage with id: 45752 from player GOD Mictlantecuhtli is: 13.

it should be 14 but i have gone to all the five places, maybe i got bugged, how can i fix this?

**Comment by AdversarioV** [comment]
Nvm, fixed, it thanks
