### ISSUE TITLE
#679 #684 bugs

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/OTServBR-Global#686]
#679 `Lua Script Error: [Main Interface]
in a timer event called from:
(Unknown scriptfile)
data/globalevents/scripts/serversave.lua:18: attempt to perform arithmetic on local 'remaningTime' (a nil value)
stack traceback:
        [C]: in function '__sub'
        data/globalevents/scripts/serversave.lua:18: in function <data/globalevents/scripts/serversave.lua:17>`

#684 `[Warning - Event::checkScript] Can not load script: scripts/quests/cults of tibia/vortexSpawnCarlin.lua
...ipts/scripts/quests/cults of tibia/vortexSpawnCarlin.lua:20: ')' expected near ','`

**Comment by Costallat** [comment]
Tks!

I sent the fixes, you can try with those changes

And thanks again for helping testing

**Comment by yatozin** [comment]
`Lua Script Error: [Main Interface]
in a timer event called from:
(Unknown scriptfile)
data/globalevents/scripts/serversave.lua:19: attempt to perform arithmetic on local 'remaningTime' (a nil value)
stack traceback:
        [C]: in function '__sub'
        data/globalevents/scripts/serversave.lua:19: in function <data/globalevents/scripts/serversave.lua:17>`
