### ISSUE TITLE
"Quest log updated" on "Killing in the name of..."

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#686]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

This is super low priority but, when killing anything on a task will receive the following message

![image](https://user-images.githubusercontent.com/107372680/177059663-1f371114-1be3-41b8-8159-e2db2b9fa1fe.png)

Is there a way to remove this so it only does it once you finish the quest?

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Koras443** [comment]
i got same thing anyone could help with that?
