### ISSUE TITLE
Tibia Secret Service (The weakest spot)

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#688]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

On mission 6 of the "Tibia Secret Service" quest

![image](https://user-images.githubusercontent.com/107372680/177063516-7fcf4e43-0c4a-4837-b9f6-6306dd599305.png)

When using the cask after getting item 397

Nothing happens, i did check the storage value of the player but i believe it could have something to do with Looktype 137

![image](https://user-images.githubusercontent.com/107372680/177063606-627384f7-c007-4b7a-8d17-3c48803725af.png)

![image](https://user-images.githubusercontent.com/107372680/177063627-054c35da-667a-4ad0-be70-db7d2661def4.png)

Player is using this crowbar

![image](https://user-images.githubusercontent.com/107372680/177063655-c68dc33c-d960-4da9-a612-354e06752746.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
you have old datapack, i fixed this issue in #659
line 858 secretService should be SecretService

**Comment by AdversarioV** [comment]
> you have old datapack, i fix this issue in #659 line 858 secretService should be SecretService

Will test
