### ISSUE TITLE
Bug with exp rate in client or engine sources

### ISSUE THREAD

**Issue by Koras443** [opentibiabr/otservbr-global#694]
### Priority

Medium

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [X] Other

### What happened?

![image](https://user-images.githubusercontent.com/108338780/177293991-f27183a8-926a-4896-b663-9879315b34a5.png)
shows 7500 exp rate instead of normal 100/150 etc..

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beats-dh** [comment]
Change the values ​​from 500 to 100. https://github.com/opentibiabr/otservbr-global/blob/main/data/XML/events.xml

**Comment by rigis1** [comment]
or edit startdate="2/2/2022" enddate="11/7/2022"

**Comment by Koras443** [comment]
it's not about event it happen without exp event.

**Comment by Koras443** [comment]
![image](https://user-images.githubusercontent.com/108338780/177436131-e7438576-e2fc-44a0-b759-d0a4642a9fea.png)
![image](https://user-images.githubusercontent.com/108338780/177436191-4e7bd88d-41ea-422e-8b87-061fcfc729f9.png)
![image](https://user-images.githubusercontent.com/108338780/177436256-b47d1330-371f-44c5-ab14-ba792719775e.png)

**Comment by rigis1** [comment]
check config.lua 
```
rateExp = 1
rateSkill = 1
rateLoot = 1
rateMagic = 1
rateSpawn = 1
```
or if `rateUseStages = true`
check stages.lua

**Comment by Koras443** [comment]
![image](https://user-images.githubusercontent.com/108338780/177438458-c1912925-7c4b-4238-89f6-f55bf5d76187.png)
![image](https://user-images.githubusercontent.com/108338780/177438485-ab0bbe20-2a27-4de9-ab80-3be708254624.png)

**Comment by rigis1** [comment]
change multiplier to 1 and
![image](https://user-images.githubusercontent.com/22598283/177438846-9e5883cc-3b2e-4d4b-ac2f-0230ce4be5fa.png)
![image](https://user-images.githubusercontent.com/22598283/177438923-5983fddb-4d52-4a42-b7bf-f3259d41bb1f.png)

**Comment by Koras443** [comment]
then i will have x1 exp rate i don't want exp like real tibia bro think what you saying XD 
it's something inside engine for sure not about that what you tellin me

**Comment by rigis1** [comment]
> then i will have x1 exp rate i don't want exp like real tibia bro think what you saying XD it's something inside engine for sure not about that what you tellin me

so you wanna have high multiplier and have 100%/150%?

**Comment by guispiller** [comment]
> then i will have x1 exp rate i don't want exp like real tibia bro think what you saying XD 
> it's something inside engine for sure not about that what you tellin me

That's not an issue, it's a config.

If you want exp display to ignore the exp stages, on startup.lua, change Game.setStorageValue(GlobalStorage.XpDisplayMode) to 0

**Comment by Koras443** [comment]
where it's that located? i mean which folder?

**Comment by Koras443** [comment]
> > then i will have x1 exp rate i don't want exp like real tibia bro think what you saying XD
> > it's something inside engine for sure not about that what you tellin me
> 
> That's not an issue, it's a config.
> 
> If you want exp display to ignore the exp stages, on startup.lua, change Game.setStorageValue(GlobalStorage.XpDisplayMode) to 0

where it's that located? i mean which folder?

**Comment by guispiller** [comment]
> > > then i will have x1 exp rate i don't want exp like real tibia bro think what you saying XD
> > > it's something inside engine for sure not about that what you tellin me
> > 
> > 
> > That's not an issue, it's a config.
> > If you want exp display to ignore the exp stages, on startup.lua, change Game.setStorageValue(GlobalStorage.XpDisplayMode) to 0
> 
> where it's that located? i mean which folder?

data\scripts\globalevents\others\startup.lua Line 156
