### ISSUE TITLE
Distance Weapons Imbuing with elemental damage like ice/holy etc.. not working

### ISSUE THREAD

**Issue by Koras443** [opentibiabr/otservbr-global#697]
### Priority

High

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [X] Other

### What happened?

Any elemental imbuement in bow or crossbow. Target monster and he get 100% physical damage.
With swords, axes and clubs, elemental imbuements works fine.
![image](https://user-images.githubusercontent.com/108338780/177508729-35377770-0e8c-49c3-be46-1730aaff89aa.png)
![image](https://user-images.githubusercontent.com/108338780/177509015-a5b94c50-f8d7-4249-a99a-1d6345a16c74.png)

literally all the time it's same dmg only from physical.

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Repeated, #382.
