### ISSUE TITLE
Hireling shop incorrect bolt id - generate infinite gold

### ISSUE THREAD

**Issue by hireheherling** [opentibiabr/otservbr-global#700]
### Priority

Critical

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

In Hireling npc shop, bolt have incorrect id: 3483, this is id of fishing rod which allow player to make infinite gold by buying this "bolt" for 4gp and sell the received fishing rod to npc for 40gp

{ itemName = "bolt", clientId = 3483, buy = 4 }
{ itemName = "fishing rod", clientId = 3483, sell = 40 }

### What OS are you seeing the problem on?

Debian 11, Ubuntu 20.04, Ubuntu 22.04, Windows 10, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdversarioV** [comment]
Please check if this solves the issue 

#712

**Comment by AdversarioV** [comment]
New PR #712
