### ISSUE TITLE
The New Frontier (Farmine)

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#710]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

When using the boat from cormaya to farmine it returns you to and old instance of farmine, you need to use the lever  and back to get to the new (finished) farmine

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rigis1** [comment]
fixed in #696, you have old datafiles.

**Comment by AdversarioV** [comment]
> fixed in #696, you have old datafiles.

Yes, this solved the issue
