### ISSUE TITLE
Market not working on certain depots

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#717]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

I found out that the market does not work on certain depots, so far on the gnomebase, custom traders island

When you click the market inside the depot it does not open

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Koras443** [comment]
**### _because you have to select town id in a Rme like thais or something._**

**Comment by AdversarioV** [comment]
> **### _because you have to select town id in a Rme like thais or something._**

Let me test this since one is on the custom map, ill let you know if it works

**Comment by AdversarioV** [comment]
Yes, this work, no need for PR, it was just me being dumb

**Comment by CzajaTwitch** [comment]
Its simple, rme map editor, click on depot and select town like Thais do Thais and should work.
