### ISSUE TITLE
Teleport to feroxa, map missing

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#719]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

When you teleport to feroxa there is part missing of the map 
(00:35 You see a magic forcefield.
Client ID: 1949
Position: 33457, 31529, 11)

You can walk as if there was normal floor

![image](https://user-images.githubusercontent.com/107372680/179450668-976def5c-1265-4917-983d-d5c32a7b1b6a.png)
![image](https://user-images.githubusercontent.com/107372680/179450731-561a17f0-379a-41a2-9076-80b9392d4422.png)
![image](https://user-images.githubusercontent.com/107372680/179450792-9670bacc-5597-4ea4-84c5-a2fe120649d8.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed, thanks to @Johnevictor for the map contribution.
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
