### ISSUE TITLE
[MAP] teleport, aid and uid to remove, missing map objects

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#722]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?
<details>
  <summary>Done</summary>
  
### this aid can be removed from map 
32362
- {x = 33378, y = 31112, z = 8}
- {x = 33378, y = 31111, z = 8}
- {x = 33377, y = 31112, z = 8}
- {x = 33376, y = 31111, z = 8}
- {x = 33377, y = 31110, z = 8}
- {x = 33376, y = 31110, z = 8}
- {x = 33375, y = 31108, z = 8}
- {x = 33375, y = 31107, z = 8}
- {x = 33374, y = 31107, z = 8}
- {x = 33373, y = 31107, z = 8}
- {x = 33373, y = 31108, z = 8}
- {x = 33379, y = 31106, z = 8}
- {x = 33378, y = 31106, z = 8}
- {x = 33377, y = 31106, z = 8}
- {x = 33377, y = 31105, z = 8}
- {x = 33379, y = 31105, z = 8}
- {x = 33379, y = 31104, z = 8}
- {x = 33378, y = 31104, z = 8}
- {x = 33377, y = 31104, z = 8}
- {x = 33382, y = 31103, z = 8}
- {x = 33381, y = 31103, z = 8}
- {x = 33382, y = 31102, z = 8}
- {x = 33380, y = 31102, z = 8}
- {x = 33382, y = 31101, z = 8}
- {x = 33381, y = 31101, z = 8}
- {x = 33380, y = 31101, z = 8}
- {x = 33377, y = 31102, z = 8}
- {x = 33376, y = 31102, z = 8}
- {x = 33375, y = 31102, z = 8}
- {x = 33375, y = 31101, z = 8}
- {x = 33376, y = 31101, z = 8}
- {x = 33375, y = 31100, z = 8}
- {x = 33376, y = 31100, z = 8}
- {x = 33377, y = 31100, z = 8}

8016
- {x = 33383, y = 31093, z = 8}
- {x = 33382, y = 31093, z = 8}
- {x = 33382, y = 31085, z = 8}

8017
- {x = 33381, y = 31093, z = 8}
- {x = 33381, y = 31085, z = 8}

8018
- {x = 33373, y = 31075, z = 8}
- {x = 33372, y = 31075, z = 8}
- {x = 33371, y = 31075, z = 8}
- {x = 33370, y = 31075, z = 8}
- {x = 33369, y = 31075, z = 8}
- {x = 33368, y = 31075, z = 8}

8019
- {x = 33360, y = 31080, z = 8}
- {x = 33360, y = 31079, z = 8}
- {x = 33360, y = 31078, z = 8}

8020
- {x = 33346, y = 31075, z = 8}
- {x = 33346, y = 31074, z = 8}
- {x = 33346, y = 31073, z = 8}

8023
- {x = 33330, y = 31077, z = 8}
- {x = 33330, y = 31076, z = 8}

12382
- {x = 33216, y = 31067, z = 9}

12383
- {x = 33076, y = 31218, z = 8}
- {x = 33076, y = 31219, z = 8}

8026
- {x = 33236, y = 31220, z = 10}
- {x = 33237, y = 31220, z = 10}
- {x = 33238, y = 31220, z = 10}
- {x = 33239, y = 31220, z = 10}
- {x = 33240, y = 31220, z = 10}
- {x = 33241, y = 31220, z = 10}
- {x = 33242, y = 31220, z = 10}

8013
- {x = 33349, y = 31123, z = 5},
- {x = 33349, y = 31124, z = 5},
- {x = 33349, y = 31125, z = 5},
- {x = 33349, y = 31126, z = 5},
- {x = 33349, y = 31127, z = 5}

8014
- {x = 33258, y = 31080, z = 8}
- {x = 33266, y = 31084, z = 8}
- {x = 33259, y = 31089, z = 8}
- {x = 33263, y = 31093, z = 8}

### uid

1109
- {x = 33136, y = 31249, z = 6}

3186
- {x = 33092, y = 31122, z = 12}
- {x = 33111, y = 31123, z = 12}

9263
- {x = 33111, y = 31123, z = 12}

3197
- {x = 33072, y = 31150, z = 15}

3168
- {x = 33261, y = 31076, z = 8}

3167
- {x = 33356, y = 31124, z = 7}

3175
- {x = 33362, y = 31202, z = 8}

3171

- {x = 33370, y = 31067, z = 9}

3172

- {x = 33359, y = 31070, z = 9}

3173

- {x = 33349, y = 31075, z = 8}

3174

- {x = 33351, y = 31069, z = 9}

destination from teleports should be removed:
- {x = 33092, y = 31122, z = 12}
- {x = 33136, y = 31248, z = 6}
- {x = 33211, y = 31067, z = 9}
- {x = 33084, y = 31213, z = 8}
- {x = 33240, y = 31249, z = 10}
- {x = 33359, y = 31395, z = 9}
- {x = 33360, y = 31395, z = 9}
- {x = 33365, y = 31415, z = 10}

### Position: 32842, 32666, 8 missing rock Position: 32845, 32668, 8 missing large hole 
<details>
  <summary>Click to expand!</summary>
  
![image](https://user-images.githubusercontent.com/22598283/179751834-ed421d07-bda8-4263-9021-6e6ee3408414.png)
![image](https://user-images.githubusercontent.com/22598283/179751860-8f93759a-85f9-4f9a-a354-ef51949806e4.png)

</details>

### Position: 32842, 32646, 8 large hole missing
<details>
  <summary>Click to expand!</summary>
  
![image](https://user-images.githubusercontent.com/22598283/179744494-a678bbd5-d98c-4ad9-a811-d8cd34320dcb.png)
![image](https://user-images.githubusercontent.com/22598283/179744445-fa3fc36f-17b1-4862-8928-d0a4bacfafda.png)

</details>

### teleport in prison should be removed: 
- {x = 33357, y = 31207, z = 8}

### uid that can be removed:
3166
- {x = 33357, y = 31123, z = 5}

</details>

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed, thanks for your reports.
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
