### ISSUE TITLE
[MAP] underground port hope tarantulas map missing

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#726]
### Priority

Low

### Area

- [X] Map

### What happened?

<details>
  <summary>Undone</summary>
  

- [x] Position: 32785, 32696, 9 map missing

<details>
  <summary>Click to expand!</summary>
  
![image](https://user-images.githubusercontent.com/22598283/179743357-35a7b968-7d47-45be-8414-cad85c813304.png)
![image](https://user-images.githubusercontent.com/22598283/179743452-dd09a5a8-e316-4eb1-8817-0f226f2f49b4.png)
![image](https://user-images.githubusercontent.com/22598283/179743703-0cab9425-fcd3-4c59-91cb-c94f7fa7da58.png)
![image](https://user-images.githubusercontent.com/22598283/179743726-0cd4e910-1ba1-4ce3-a8fe-37573491cb8a.png)
![image](https://user-images.githubusercontent.com/22598283/179743793-995e310a-21aa-4c79-8b9e-10608cdcdfbc.png)
![image](https://user-images.githubusercontent.com/22598283/179743861-4cce890a-a331-4940-99c4-fbaf5d836cb7.png)
![image](https://user-images.githubusercontent.com/22598283/179743907-3aae5d49-4bcb-4ae5-8b58-59e1fbe07b9d.png)
![image](https://user-images.githubusercontent.com/22598283/179743952-42e6a75d-7177-4b3e-8115-db57a29f4c8f.png)
![image](https://user-images.githubusercontent.com/22598283/179743995-a29593b4-17d2-4625-8702-9caa084accd2.png)
![image](https://user-images.githubusercontent.com/22598283/179744027-541f73c8-5f6c-46a2-9791-23abea8f60ec.png)
![image](https://user-images.githubusercontent.com/22598283/179744074-ad819f0b-0e75-4534-bc9e-57d1bd8286f1.png)
![image](https://user-images.githubusercontent.com/22598283/179744098-e65628a4-1f1a-494b-a9f2-69650dcbbd24.png)
![image](https://user-images.githubusercontent.com/22598283/179744131-1a7ba021-5096-40d3-96bd-f1f0f36bda05.png)
![image](https://user-images.githubusercontent.com/22598283/179744158-6f8f0132-baa7-4e0c-a808-9bf462a31831.png)
![image](https://user-images.githubusercontent.com/22598283/179744196-0a3d1e8f-80b1-452c-a643-72d95e680fc1.png)
![image](https://user-images.githubusercontent.com/22598283/179744228-16e74f5d-c56e-4603-a9fc-08ce857628e9.png)
![image](https://user-images.githubusercontent.com/22598283/179744259-e37b88ac-45d7-4952-8c91-ad648d77fae6.png)
</details>

- [x] Position: 32845, 32668, 9 missing map

<details>
  <summary>Click to expand!</summary>
  
![image](https://user-images.githubusercontent.com/22598283/179752615-992112c5-9e7f-43bf-bf48-7c1d73a7ab20.png)

</details>

- [x] Position: 32168, 31919, 8 missing tapestry, Position: 32174, 31916, 8 wrong vortex id, Position: 32176, 31914, 8 and Position: 32176, 31917, 8 missing rubbish and torn book

<details>
  <summary>Click to expand!</summary>
  
![image](https://user-images.githubusercontent.com/22598283/180636640-8173e1f7-eaf4-456a-8122-220cf93aa954.png)
![image](https://user-images.githubusercontent.com/22598283/180636632-4b4072ac-5715-443e-90ab-965b03b0be7e.png)

</details>

</details>

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Hello there, i was looking to track these maps, but i think they are already on the otbr map, aren't they?
Please check those, starting on position {x = 32726, y = 32793, z = 8}.
![image](https://user-images.githubusercontent.com/11639062/183906320-5a4b68ff-9c59-46d1-bac5-71ec882b1986.png)

If it isn't this map, please could you specify me the location, so i can try to get these?

**Comment by rigis1** [comment]
this isn't that map 
here you have [MAP position](https://tibiamaps.io/map#32785,32696,9:2)
and for the second part [MAP position](https://tibiamaps.io/map#32845,32668,9:3)

**Comment by guispiller** [comment]
yep, sorry about that, haven't seen the expand section on your issue :KEK:
Sorry about that, i'll find these maps, thank you

**Comment by majestyotbr** [comment]
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
Thanks to @guispiller for the map contribution.
