### ISSUE TITLE
Sight of Surrender spawn

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#729]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

Im not sure if map here should look like this

11:32 You see unknown tile.
Client ID: 20324
Position: 33549, 32351, 7

![image](https://user-images.githubusercontent.com/107372680/180484033-f5800070-79e2-4ec9-b0a4-fd48f60566f9.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Yes, it looks like this. Not an issue, closed.

![43sd2qu28ir71](https://user-images.githubusercontent.com/11639062/180487726-eb2a3012-56ae-49f7-a804-fdb6be829cda.jpg)
