### ISSUE TITLE
[MAP] Ghoul Room Quest door

### ISSUE THREAD

**Issue by Austerror** [opentibiabr/otservbr-global#737]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

Location: {x = 32506, y = 32175, z = 14}
Item 5106 (closed door - it is locked) should be 5107 (closed door) with actionId 3600
![image](https://user-images.githubusercontent.com/5996714/181747459-5111f4b5-0a74-4ac6-8cfe-8fa032aa3859.png)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed, thanks for your report.
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
