### ISSUE TITLE
[MAP] Cults of Tibia (Life) e Sea Serpent Area 2

### ISSUE THREAD

**Issue by CorwenCrow** [opentibiabr/otservbr-global#739]
### Priority

Low

### Area

- [ ] Datapack
- [ ] Source
- [X] Map
- [ ] Other

### What happened?

Na quest Cults of Tibia na parte (Life) a porta não abre e o NPC Angelo não está dando a quest, ele está perto da porta que fica nesse local
![image](https://user-images.githubusercontent.com/110359393/182409513-11ef0be4-be11-4419-86f2-b5deb9cfa389.png)
normalmente você fala com ele e a porta fica liberada pra ir nas putrid mummy ali e alem disso tem pouca putrid mummy, no spawn do global tem bem mais por volta de 4-5 por intercessão (e não tem GS em todos os andares só no andar do Oasis tem 2)
Pra acessar esse local é pela Minotower em Darashia
![image](https://user-images.githubusercontent.com/110359393/182412046-b3eb64e2-e0b6-4322-831e-fe1519c7b154.png)
Só descer até o ultimo andar e descer no buraco que tu ta lá já
Na Sea Serpent Area 2 só tem o problema de ter pouco Young Sea Serpent no global tem tipo uns 2 desses pra cada Sea Serpent nos dois andares (normalmente você termina o bestiary deles faltando uns 400 Sea Serpent normal) o acesso pra cave é no barco do Captain Haba em Svargrond
![image](https://user-images.githubusercontent.com/110359393/182411187-f8ba2506-7b55-408b-9f9c-3b98127f26ec.png)
![image](https://user-images.githubusercontent.com/110359393/182411341-f5b80cdb-c033-4287-a4bc-ae0fd10d58a3.png)
Não testei se a quest do Captain Haba ta funcionando vou testar depois e dou um edit aqui.

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
These issues are not map-intended, this can be fixed on monster-spawns.xml directly
