### ISSUE TITLE
[MAP] changes to map 

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#754]
### Priority

Low

### Area
- [X] Map
### What happened?

# Changes need for #753
- [x] {x = 33195, y = 31765, z = 1} add aid 2001
- [x] {x = 33201, y = 31763, z = 1} remove flame
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/185711209-f96ffdc0-a8bd-4b7a-be43-3b40bd77dfd3.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/185711487-a54d66f1-f1c4-4a17-a978-5023e2410b79.png)
</details>

- [x] {x = 32165, y = 31294, z = 6} remove hole
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184479604-5ba2925c-61ca-4b8c-bfdb-e031c1e17978.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184479484-e8ac7fd7-d828-4ef7-8145-89a8119511fa.png)
</details>

- [x] {x = 32305, y = 32254, z = 9} change corpse id, set aid 2001 and remove uid
<details>
  <summary>Details</summary>

## Looks like
![2022-08-13](https://user-images.githubusercontent.com/22598283/184479156-0fd6613b-b84c-4ffe-9fb1-85aeaa84d98e.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184479176-ad141504-6bfe-4b9b-84f3-643f023905b6.png)
</details>

- [x] {x = 32348, y = 31128, z = 6} remove teleport and insert balista
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184510004-d6e3c9a2-2cf3-4f74-aac0-e5d43a9fb47f.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184510191-a501b98c-5777-4b5c-9b09-07fffa16386a.png)

</details>

- [x] {x = 31938, y = 31042, z = 6} remove teleport
- [x] {x = 31939, y = 31049, z = 6} remove teleport
- [x] {x = 31946, y = 31042, z = 6} remove teleport and add balista
- [x] {x = 31946, y = 31041, z = 6} remove sign
- [x] {x = 31938, y = 31041, z = 6} add invisible? walkable floor
- [x] {x = 31939, y = 31050, z = 6} add invisible? walkable floor
- [x] {x = 31943, y = 31046, z = 6} remove teleport
- [x] {x = 31943, y = 31046, z = 7} add teleport
- [x] {x = 31943, y = 31046, z = 6} remove ladder
- [x] remove protection zone from ship upper except {x = 31938, y = 31042, z = 6} and {x = 31939, y = 31049, z = 6}
- [x] remove protection zone from ship under
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184510262-c493b201-8720-44af-9826-a08abe100cef.png)
![image](https://user-images.githubusercontent.com/22598283/184510534-1ba9c08b-1ab3-4f54-a5b8-a9e1081e89de.png)

## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184510441-1f3e4a85-c9fc-4d64-b000-7a311d71fc2f.png)
![image](https://user-images.githubusercontent.com/22598283/184510471-315e879e-9174-4b80-8b9b-2137275df655.png)
![image](https://user-images.githubusercontent.com/22598283/184510476-a8372048-3a8e-4f3d-8fcb-6ec32e3e5a2e.png)
![image](https://user-images.githubusercontent.com/22598283/184510522-9aad0164-dd8a-48c9-bfff-dbff155c1bac.png)
![image](https://user-images.githubusercontent.com/22598283/184519647-126c19c0-1eab-428d-99dc-1f2a4961491e.png)

</details>

Cormaya
- [x] {x = 33256, y = 31986, z = 8} missing wall banner
- [x] {x = 33256, y = 31983, z = 8} missing wall banner
- [x] {x = 33256, y = 31982, z = 8} missing wall banner
- [x] {x = 33256, y = 31980, z = 8} torch positon should be {x = 33256, y = 31981, z = 8} 
- [x] {x = 33261, y = 31984, z = 8} should be vortex
- [x] {x = 33259, y = 31977, z = 8} missing wall banner
- [x] {x = 33259, y = 31977, z = 8} torch positon should be {x = 33260, y = 31977, z = 8} 
- [x] {x = 33261, y = 31977, z = 8} missing trophy
- [x] {x = 33262, y = 31977, z = 8} missing trophy
- [x] {x = 33264, y = 31977, z = 8} torch positon should be {x = 33263, y = 31977, z = 8}
- [x] {x = 33264, y = 31977, z = 8} missing wall banner
- [x] object from {x = 33515, y = 31438, z = 13} to {x = 33514, y = 31438, z = 13}
- [x] floor decoration from {x = 33515, y = 31437, z = 13} to {x = 33514, y = 31437, z = 13}
- [x] {x = 33521, y = 31438, z = 13} wrong object
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184524905-96466899-55a4-41e6-97b6-0f50d08e2abd.png)
![image](https://user-images.githubusercontent.com/22598283/184525223-6c39adac-8541-4e8c-a759-96eb3cbd5dda.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184524964-c27d8a81-e80c-4d24-bf4e-db9bad005283.png)
![image](https://user-images.githubusercontent.com/22598283/184525202-9a041949-bab8-452e-bd35-55003c3f04ad.png)
![image](https://user-images.githubusercontent.com/22598283/184525270-9098a40f-5593-4546-8d98-ec34f94c1981.png)

</details>

Darashia
- [x] {x = 33288, y = 32473, z = 9} add vortex
- [x] {x = 33287, y = 32473, z = 9} remove teleport
- [x] {x = 33283, y = 32472, z = 9} object from, to {x = 33283, y = 32471, z = 9}
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184525448-ab3d4da1-0769-4eaf-8a01-a47a3a66c98b.png)

## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184525467-2dad6789-0442-4d7d-af46-11e4988ba1dd.png)
![image](https://user-images.githubusercontent.com/22598283/184525475-9eb0207e-759b-493f-84c4-904cafb06877.png)

</details>

Edron
- [x] {x = 33194, y = 31692, z = 8} missing decoration 
- [x] {x = 33195, y = 31694, z = 8} remove teleport
- [x] {x = 33196, y = 31694, z = 8} add vortex
- [x] {x = 33191, y = 31693, z = 8} missing banner 
- [x] {x = 33191, y = 31694, z = 8} missing banner 
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184525627-96e42f3b-a2cd-436e-8883-ec1ea8b67848.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184525632-99ca3031-2ce9-4ff7-8258-33fb8ab70eb1.png)
</details>

Ghostland
- [x] {x = 32190, y = 31817, z = 8} should be vortex
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184525849-e17b4ecf-64bc-4a94-b48a-0f83f752f95b.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184525856-bfe141d7-5947-41bf-9e41-180f42dd0b33.png)
</details>

Femor Hills
- [x] {x = 32538, y = 31843, z = 6} wrong object
- [x] {x = 32538, y = 31846, z = 6} wrong object
- [x] {x = 32538, y = 31849, z = 6} wrong object
- [x] {x = 32547, y = 31843, z = 6} wrong object
- [x] {x = 32547, y = 31846, z = 6} wrong object
- [x] {x = 32547, y = 31849, z = 6} wrong object
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184526034-4f8b3295-5812-4dd0-b913-b9e2faed88c4.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184526004-3b8e8089-0b96-4247-85f8-2c30c4d6b3bc.png)
![image](https://user-images.githubusercontent.com/22598283/184526049-7b46d443-e36f-4f10-837e-6ba43f5b204e.png)

</details>

Folda
- [x] {x = 32008, y = 31559, z = 7} missing object
- [x] {x = 32007, y = 31561, z = 7} missing ice
- [x] {x = 32007, y = 31560, z = 7} wrong ice
- [x] {x = 32007, y = 31559, z = 7} remove ice
- [x] {x = 32007, y = 31558, z = 7} wrong ice
- [x] {x = 32007, y = 31557, z = 7} missing ice
- [x] {x = 32007, y = 31556, z = 7} wrong ice
- [x] {x = 32007, y = 31555, z = 7} wrong ice
- [x] {x = 32008, y = 31554, z = 7} remove ice
- [x] {x = 32009, y = 31554, z = 7} wrong ice
- [x] {x = 32010, y = 31554, z = 7} remove ice
- [x] {x = 32011, y = 31554, z = 7} wrong ice
- [x] {x = 32013, y = 31554, z = 7} wrong ice
- [x] {x = 32014, y = 31554, z = 7} wrong ice
- [x] {x = 32015, y = 31554, z = 7} missing ice
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184526175-f3b8ec52-7762-4cb3-91bc-c6011a9d068d.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184526171-9779dea8-cbd4-45e6-9061-1417dda940e8.png)

</details>

Vengoth
- [x] {x = 32955, y = 31530, z = 7} missing object
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184526292-4bcb629a-43e3-4a89-b413-22c4cbc3fdb9.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184526302-6162465d-403a-4a41-909f-feff8e287f3c.png)
![image](https://user-images.githubusercontent.com/22598283/184526306-299d066a-aa69-4cc3-b547-bc3147f9c168.png)

</details>

Thais
- [x] {x = 32345, y = 32169, z = 12} remove teleport
- [x] {x = 32345, y = 32168, z = 12} add vortex
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/184822546-dbeb477c-51e7-41e1-8a07-b3a89dea4dd5.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/184822742-58ee4425-eb07-4b2e-9c87-14c35bc7e298.png)

</details>

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed, thanks for your reports.
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
