### ISSUE TITLE
Error Npc's

### ISSUE THREAD

**Issue by luiscaldera** [opentibiabr/otservbr-global#755]
### Priority

High

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

Hi, I'm using otservbr in ubuntu 20.04, I just updated version 1290 and it's showing me an error in the console when using certain npcs such as (Hanna, flint, yasior and all the djin) they are for the moment the ones I've tried, I add print of the error displayed.
the exact line of the error is the following: 
npcType.onSellItem = function(npc, player, clientId, subtype, amount, name, totalCost)
![image](https://user-images.githubusercontent.com/35881739/184548713-78961d38-9d97-4896-b3a0-9c9906e6048c.png)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Our source and datapack are not yet updated to protocol 12.90. It's not an issue to be reported on github. 
If you are testing our PRs from source and datapack, you can report errors at the PR comments.
