### ISSUE TITLE
[MAP] aid to remove and objects to change

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#759]
### Priority

Low

### Area
- [X] Map
### What happened?

# Changes need for #758 
- [x] {x = 33360, y = 31350, z = 7} change to locked door
- [x] {x = 33368, y = 31331, z = 7} change to locked door
- [x] {x = 33377, y = 31321, z = 1} remove aid
- [x] {x = 32506, y = 32175, z = 14} remove aid and change to locked door
- [x] {x = 33306, y = 31349, z = 8} remove aid and destination
- [x] {x = 33310, y = 31325, z = 8} remove aid
- [x] {x = 33329, y = 31333, z = 9} remove aid
- [x] {x = 33296, y = 31287, z = 9} remove aid
- [x] {x = 33297, y = 31287, z = 9} remove aid
- [x] {x = 33298, y = 31287, z = 9} remove aid
- [x] {x = 33296, y = 31288, z = 9} remove aid
- [x] {x = 33298, y = 31288, z = 9} remove aid
- [x] {x = 33298, y = 31289, z = 9} remove aid
- [x] {x = 33297, y = 31289, z = 9} remove aid
- [x] {x = 33382, y = 31293, z = 7} remove aid
- [x] {x = 33373, y = 31309, z = 7} remove aid
- [x] {x = 33344, y = 31348, z = 7} remove aid
- [x] {x = 33328, y = 31350, z = 7} remove aid
- [x] {x = 33344, y = 31348, z = 7} missing protected zone
- [x] {x = 33344, y = 31347, z = 7} missing protected zone
- [x] {x = 33345, y = 31346, z = 7} missing protected zone
- [x] {x = 33346, y = 31346, z = 7} missing protected zone
- [x] {x = 33345, y = 31347, z = 7} missing protected zone
- [x] {x = 33346, y = 31347, z = 7} missing protected zone
- [x] {x = 33345, y = 31348, z = 7} missing protected zone
- [x] {x = 33346, y = 31348, z = 7} missing protected zone
- [x] {x = 33345, y = 31349, z = 7} missing protected zone
- [x] {x = 33346, y = 31349, z = 7} missing protected zone
- [x] {x = 33328, y = 31352, z = 7} missing protected zone
- [x] {x = 33328, y = 31351, z = 7} missing protected zone
- [x] {x = 33327, y = 31351, z = 7} missing protected zone
- [x] {x = 33327, y = 31350, z = 7} missing protected zone
- [x] {x = 33326, y = 31349, z = 7} missing protected zone
- [x] {x = 33326, y = 31350, z = 7} missing protected zone
- [x] {x = 33326, y = 31351, z = 7} missing protected zone
- [x] {x = 33326, y = 31352, z = 7} missing protected zone
- [x] {x = 33326, y = 31353, z = 7} missing protected zone
- [x] {x = 33327, y = 31353, z = 7} missing protected zone
- [x] {x = 33352, y = 31318, z = 7} change itemId to 23741
- [x] {x = 33366, y = 31323, z = 5} change itemId to 23741
- [x] {x = 33374, y = 31340, z = 4} change itemId to 23741
- [x] {x = 33384, y = 31285, z = 7} change itemId to 23740
- [x] {x = 33324, y = 31268, z = 8} change itemId to 23740
- [x] {x = 33308, y = 31304, z = 9} change itemId to 23740
- [x] {x = 32519, y = 32911, z = 7} change from locked door to closed door
## Changes to objects
- [x] {x = 33366, y = 31343, z = 7} remove aid and change to quest door
- [x] {x = 33363, y = 31346, z = 7} remove aid and change to quest door
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/185810507-3a22ca00-62cc-43e6-a731-f5386c80ecc5.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/185810886-f20230eb-9758-4605-b3f4-044575b239d1.png)
</details>

- [x] {x = 33382, y = 31293, z = 7} boat wrong location
<details>
  <summary>Details</summary>

## Looks like
![image](https://user-images.githubusercontent.com/22598283/185897220-ef7a29b7-3aa4-4f68-99ae-c8fd7c5531ab.png)
## Should looks like
![image](https://user-images.githubusercontent.com/22598283/185897596-fc69712f-731a-4a32-bc74-b45d65439750.png)
</details>

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Fixed, thanks for your reports.
Updated otservbr-global map available in:
https://github.com/opentibiabr/otservbr-global/releases/download/stable-v1.4.0/otservbr.otbm
