### ISSUE TITLE
Killing in the name off - Boss Teleports

### ISSUE THREAD

**Issue by AdversarioV** [opentibiabr/otservbr-global#775]
### Priority

Low

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

The teleports after adding (I believe) fix #731 , they work...but they generate an error on the console every time anybody steps in the portal 

![image](https://user-images.githubusercontent.com/107372680/187118335-135a16b5-7011-417e-a230-e152d3b67d00.png)

second, they used to bounce you back if you were not on that boss quest, now you can stand on them generating the error on the console

![image](https://user-images.githubusercontent.com/107372680/187118678-586754a1-39bb-4d42-b01c-9dfe35d0e91a.png)

### What OS are you seeing the problem on?

Ubuntu 20.04, Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
Tested with god character and normal character, working here without generate error on the console. 
If you are running otservbr-global datapack, check if your scripts and map are updated.

**Comment by AdversarioV** [comment]
I redownloaded the map, and the script folder, error no longer appears on the console, however.....the teleport does not work, i do have the correct storage
