### ISSUE TITLE
water buffalo can stack

### ISSUE THREAD

**Issue by s3baz12** [opentibiabr/otservbr-global#779]
### Priority

Low

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

water buffalo can stack
https://youtu.be/fMmoPTEaCNc

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Can't open the video, it says it's private. Could you please put it public, or detail on text?

**Comment by s3baz12** [comment]
https://youtu.be/fMmoPTEaCNc
try right now

**Comment by QuebradaZN** [comment]
`monster.flags = {
	summonable = false,
	attackable = true,
	hostile = true,
	convinceable = false,
	pushable = true,
	rewardBoss = false,
	illusionable = true,
	canPushItems = false,
	canPushCreatures = false,
	staticAttackChance = 80,
	targetDistance = 1,
	runHealth = 0,
	healthHidden = false,
	isBlockable = false,
	canWalkOnEnergy = false,
	canWalkOnFire = false,
	canWalkOnPoison = false
}`

**Comment by s3baz12** [comment]
![image](https://user-images.githubusercontent.com/97344089/188640944-db531772-60f6-44c9-a4ee-03adac0b950e.png)

**Comment by s3baz12** [comment]
[QuebradaZN](https://github.com/QuebradaZN) i tried yours but is the same

**Comment by QuebradaZN** [comment]
@s3baz12 
It's not the same
![image](https://user-images.githubusercontent.com/47014952/188680484-faf8aea0-5409-449e-883b-7c5e251df5d2.png)

**Comment by s3baz12** [comment]
I meant that I set these parameters according to what you gave me and there is still a problem

**Comment by QuebradaZN** [comment]
> I meant that I set these parameters according to what you gave me and there is still a problem

The screen you sent does not agree with what I sent!

**Comment by s3baz12** [comment]
I'm sorry, I made a mistake, I set it up and it works correctly

**Comment by s3baz12** [comment]
thank you for you help and please update the repository
