### ISSUE TITLE
"cloosing doors"

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global#781]
Erros com portas:
numero 1 : portas só ti empurram para 1 direção ao serem fechadas.
![image](https://user-images.githubusercontent.com/52710697/70174941-9a7c8e80-16b4-11ea-93ac-8914cbad058c.png)
![image](https://user-images.githubusercontent.com/52710697/70175424-75d4e680-16b5-11ea-97a1-48d8e9a1b9ed.png)

ao tentar fechar a porta, com um objeto ao lado, que deveria "empurrar" o jogador para o lado oposto ao objeto <- de acordo com a foto, ele retorna o numero "2".
![image](https://user-images.githubusercontent.com/52710697/70175103-d7488580-16b4-11ea-9be6-daa43d3164a5.png)
obs: um item que não seja possivel andar ( mw, wg, ou qualquer objeto que não seja possivel andar), o jogador ao fechar a porta, deve ser movido, para o lado OPOSTO, se os 2 LADOS estiverem BLOQUEADOS de qualquer maneira, a porta não poderá ser fechada, ela ficará aberta, até algum dos 2 lados serem desbloqueados, assim podendo dar close door.

numero 2: algumas portas não empurram o jogador para lugar algum, fazendo com o que o jogador fique dentro da porta ao fecha-la.
![image](https://user-images.githubusercontent.com/52710697/70175192-03fc9d00-16b5-11ea-98bc-ceca9e9dec65.png)
![image](https://user-images.githubusercontent.com/52710697/70175204-0b23ab00-16b5-11ea-8509-ce1172de2225.png)

**Comment by lBaah** [comment]
Testa

```
		if doorCreature then
			toPosition.x = toPosition.x + 1 -- empurrando para direita
			local query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.x = toPosition.x - 1 --  move para esquerda (posição original)
				toPosition.y = toPosition.y + 1 -- move para cima
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.y = toPosition.y - 2 -- move para baixo
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.x = toPosition.x - 1 --  move para esquerda
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then
				player:sendTextMessage(MESSAGE_STATUS_SMALL, query)
				return true
			end

			doorCreature:teleportTo(toPosition, true)
		end
```

**Comment by Lycanzito** [comment]
Testado, continua bugado..
Agora o jogador é jogado para o norte esquerda, se tem alguma coisa na frente.
na hipótese de não ter os 2 sqms descritos, retorna o numero "2"
e a porta descrita da livraria, continuam fechando com o jogador dentro.
Segue video:
https://www.youtube.com/watch?v=qtYq4sauzKw



Código:
```
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	local itemId = item:getId()
	if table.contains(questDoors, itemId) then
		if player:getStorageValue(item.actionid) ~= -1 then
			item:transform(itemId + 1)
			player:teleportTo(toPosition, true)
		else
			player:sendTextMessage(MESSAGE_INFO_DESCR, "The door seems to be sealed against unwanted intruders.")
		end
		return true
	elseif table.contains(levelDoors, itemId) then
		if item.actionid > 0 and player:getLevel() >= item.actionid - 1000 then
			item:transform(itemId + 1)
			player:teleportTo(toPosition, true)
		else
			player:sendTextMessage(MESSAGE_INFO_DESCR, "Only the worthy may pass.")
		end
		return true
	elseif table.contains(keys, itemId) then
		if target.actionid > 0 then
			if item.actionid == target.actionid and doors[target.itemid] then
				target:transform(doors[target.itemid])
				return true
			end
			player:sendTextMessage(MESSAGE_STATUS_SMALL, "The key does not match.")
			return true
		end
		return false
	end

	if table.contains(horizontalOpenDoors, itemId) or table.contains(verticalOpenDoors, itemId) then
		local doorCreature = Tile(toPosition):getTopCreature()

		if doorCreature then
			toPosition.x = toPosition.x + 1 -- empurrando para direita
			local query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.x = toPosition.x - 1 --  move para esquerda (posição original)
				toPosition.y = toPosition.y + 1 -- move para cima
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.y = toPosition.y - 2 -- move para baixo
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.x = toPosition.x - 1 --  move para esquerda
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then
				player:sendTextMessage(MESSAGE_STATUS_SMALL, query)
				return true
			end

			doorCreature:teleportTo(toPosition, true)
		end

--		if doorCreature then
--			toPosition.x = toPosition.x + 1
--			local query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
--			if query ~= RETURNVALUE_NOERROR then
--				toPosition.x = toPosition.x - 1
--				toPosition.y = toPosition.y + 1
--				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
--			end
--
--			if query ~= RETURNVALUE_NOERROR then
--				player:sendTextMessage(MESSAGE_STATUS_SMALL, query)
--				return true
--			end
--
--			doorCreature:teleportTo(toPosition, true)
--		end

		if not table.contains(openSpecialDoors, itemId) then
			item:transform(itemId - 1)
		end
		return true
	end

	if doors[itemId] then
		if item.actionid == 0 then
			item:transform(doors[itemId])
		else
			player:sendTextMessage(MESSAGE_INFO_DESCR, "It is locked.")
		end
		return true
	end
	return false
end

```

**Comment by lBaah** [comment]
```
		if doorCreature then
			toPosition.x = toPosition.x + 1 -- empurrando para direita
			local query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.x = toPosition.x - 1 --  move para esquerda (posição original)
				toPosition.y = toPosition.y + 1 -- move para cima
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.y = toPosition.y - 2 -- move para baixo
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
				toPosition.x = toPosition.x - 1 --  move para esquerda
				toPosition.y = toPosition.y - 1
				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
			end

			if query ~= RETURNVALUE_NOERROR then
				player:sendTextMessage(MESSAGE_STATUS_SMALL, query)
				return true
			end

			doorCreature:teleportTo(toPosition, true)
		end
```

Pra que as portas funcionem você precisa registrar na tabela Doors os ids.

Dica: use --[[ ]] para comentários de mais de uma linha
```
 --[[
    print(10)
isso não vai ser executado
porque está dentro um bloco
de comentário de multiplas linhas
    --]]
```

Outra coisa, eu comentei o código. Vai jogando com os valores :) Pelo menos tenta né

**Comment by Lycanzito** [comment]
> ```
> 		if doorCreature then
> 			toPosition.x = toPosition.x + 1 -- empurrando para direita
> 			local query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
> 			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
> 				toPosition.x = toPosition.x - 1 --  move para esquerda (posição original)
> 				toPosition.y = toPosition.y + 1 -- move para cima
> 				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
> 			end
> 
> 			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
> 				toPosition.y = toPosition.y - 2 -- move para baixo
> 				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
> 			end
> 
> 			if query ~= RETURNVALUE_NOERROR then -- se houve erro ao mover
> 				toPosition.x = toPosition.x - 1 --  move para esquerda
> 				toPosition.y = toPosition.y - 1
> 				query = Tile(toPosition):queryAdd(doorCreature, bit.bor(FLAG_IGNOREBLOCKCREATURE, FLAG_PATHFINDING))
> 			end
> 
> 			if query ~= RETURNVALUE_NOERROR then
> 				player:sendTextMessage(MESSAGE_STATUS_SMALL, query)
> 				return true
> 			end
> 
> 			doorCreature:teleportTo(toPosition, true)
> 		end
> ```
> 
> Pra que as portas funcionem você precisa registrar na tabela Doors os ids.
> 
> Dica: use --[[ ]] para comentários de mais de uma linha
> 
> ```
>  --[[
>     print(10)
> isso não vai ser executado
> porque está dentro um bloco
> de comentário de multiplas linhas
>     --]]
> ```
> 
> Outra coisa, eu comentei o código. Vai jogando com os valores :) Pelo menos tenta né

em relação a registrar, todas estão registradas no global.lua

Do jeito que está, esta empurrando 2 sqms longe agora.
![image](https://user-images.githubusercontent.com/52710697/70296426-634bd180-17c9-11ea-97f2-ed0bd277dcdd.png)

Tentei.. tentei.. tentei mesmo :/
todas alterações que eu fiz, faziam com que a porta parece de funcionar.

não consegui, se alguém conseguir por favor, disponibilizar, obrigado <3

**Comment by dudantas** [comment]
Eu tenho a solução para o problema de fechar a porta o player continuar dentro dela. Porém nao tenho a solução para verificar se a toPosition tá bloqueada e então ele manda para outra.
E mesmo assim teria que verificar se tem algo livre, e se não tiver nenhum lugar livre pra enviar o player, não ser possível fechar a porta.

**Comment by dudantas** [comment]
@Lycanzito quando você for descrever um item que não está funcionando, por gentileza botar o ID dele pra que a gente possa fazer os testes.
