### ISSUE TITLE
EXALTATIONS FORGE AND DUST MONSTERS

### ISSUE THREAD

**Issue by Panicozera** [opentibiabr/otservbr-global#794]
### Priority

Missing Content

### Area

- [X] Datapack
- [X] Source
- [X] Map
- [ ] Other

### What is missing?

HELLO
i use this base for my ot, and e i have one question
have one system forge fork for this project for i make function in my ot?
have systems similars?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
The tier system is being developed and is in pull request, waiting for more people to test it, as soon as we finish it we will start the forge... Feel free to help with the tests. https://github.com/opentibiabr/canary/pull/366
