### ISSUE TITLE
[BUG] Active event from events.xml crashing server every midnight.

### ISSUE THREAD

**Issue by Tefcio** [opentibiabr/otservbr-global#798]
### Priority

Critical

### Area

- [X] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

If you have an active event(exp, skill, loot, spawn) the server crashes at 00:01. If there is no event - it does not crash.

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beats-dh** [comment]
This same issue is already open in the Canary repository, no need to repeat elsewhere!!!
