### ISSUE TITLE
Dummy does not train skill shielding

### ISSUE THREAD

**Issue by tutbarao** [opentibiabr/otservbr-global#811]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

All exercise training dummies should train skill shielding

### What OS are you seeing the problem on?

Debian 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by murilo09** [comment]
But it shouldn't train shielding.

**Comment by dudantas** [comment]
Cannot train shielding skill... The idea of the dummy is that you attack it to increase its aggressive damage. This is not the case with the shield.
