### ISSUE TITLE
spells buffer include player/monsters bug

### ISSUE THREAD

**Issue by mattyx14** [opentibiabr/otservbr-global#813]
**Describe the bug**
All spell with reducer skill give 65535 skills positives

**To Reproduce**
1. for example use utito tempo san

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Comment by lBaah** [comment]
Change:
https://github.com/opentibiabr/otservbr-global/blob/9732a56545584f0a0346796165fb5072c56c0189/data/spells/scripts/support/sharpshooter.lua#L9
to:
`skill:setParameter(CONDITION_PARAM_DISABLE_DEFENSE, true)`

**Comment by mattyx14** [comment]
yep :D

**Comment by Sargitarium** [comment]
Tested and work fine 100% with lBaah suggestion.......
