### ISSUE TITLE
Diamond Arrows/Spectral Bolt/Wand of Darkness

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global#836]
Estes Itens não contam tempo, se o player estiver Offline;

Problema grave com Spectral bolt/Diamond Arrows:
Estão sumindo com a action bar;

Video Explicativo:
https://www.youtube.com/watch?v=1Ymsy4ngfh0

**Comment by Elpera** [comment]
Hum, acho que o problema delas sumirem esta na parte de juntar as flechas de uma stack na outra, veja pelo video que o que acontece e que ele deve estar mandando as 99 para o slot e depois ele manda 1 da outra stack de 100 porem ao invez de juntar 99 + 1 ele some com a 99 e so deixa a 1

**Comment by Lycanzito** [comment]
> Hum, acho que o problema delas sumirem esta na parte de juntar as flechas de uma stack na outra, veja pelo video que o que acontece e que ele deve estar mandando as 99 para o slot e depois ele manda 1 da outra stack de 100 porem ao invez de juntar 99 + 1 ele some com a 99 e so deixa a 1

Então.. acho que isso só acontece com itens de tempo&stackaveis, no caso, esses são os 2 únicos itens.
me falaram que o problema seria no decaytime, algo desse tipo

**Comment by Elpera** [comment]
teoricamente esses itens nao poderiam stackar dessa maneira pois eles tem tempos diferentes , provavelmente falta um codigo de verificacao desse tempo na hora de tentar juntar eles.

**Comment by Lycanzito** [comment]
> teoricamente esses itens nao poderiam stackar dessa maneira pois eles tem tempos diferentes , provavelmente falta um codigo de verificacao desse tempo na hora de tentar juntar eles.

entao.. eles n juntam xD

**Comment by Elpera** [comment]
Nao sei onde achar esses dois scripts para olhar neles, um seria esse do tempo de decay do item e o outro seria o que stacka ao equipar com a hotkey

**Comment by Elpera** [comment]
eu acho que e nessa parte que tem que mudar, deve ter que adicionar uma verificacao se o item tem tempo e se esse tempo e igual

`
EquipObject.StackAdd = function(player, item, slotP, isStackable)
	if isStackable and item:getCount() < 100 and item:getCount() < player:getItemCount(item:getId()) then
		local itemId, count = item:getId(), 0
		while player:getItemCount(itemId) do
			if count == 100 then break end
			local _item = player:getItemById(itemId, true)
			if not _item then break end
			if _item:getCount() > 100 - count then
				_item:remove(100 - count)
				count = 100
			else
				count = count + _item:getCount()
				_item:remove()
			end
		end
		player:addItem(itemId, count, true, 1, slotP)
	else
		item:moveToSlot(player, slotP)
	end
end
`

o arquivo e o equipobject.lua logo no final (otservbr-global-develop\data\modules\scripts\equipobject)

**Comment by Lycanzito** [comment]
> eu acho que e nessa parte que tem que mudar, deve ter que adicionar uma verificacao se o item tem tempo e se esse tempo e igual
> 
> `EquipObject.StackAdd = function(player, item, slotP, isStackable) if isStackable and item:getCount() < 100 and item:getCount() < player:getItemCount(item:getId()) then local itemId, count = item:getId(), 0 while player:getItemCount(itemId) do if count == 100 then break end local _item = player:getItemById(itemId, true) if not _item then break end if _item:getCount() > 100 - count then _item:remove(100 - count) count = 100 else count = count + _item:getCount() _item:remove() end end player:addItem(itemId, count, true, 1, slotP) else item:moveToSlot(player, slotP) end end`
> 
> o arquivo e o equipobject.lua logo no final (otservbr-global-develop\data\modules\scripts\equipobject)

Bom.. Eu já queimei os restim dos meus neuronios kkkk, acho que amanhã alguém deve aparecer com a solução, os meninos são bons ai

**Comment by Lycanzito** [comment]
A.. outro erro, ao separar e depois juntar as diamonds arrows/spectral bolts, elas renovam seu tempo, para 1 hora.
