### ISSUE TITLE
Rings/Amulets or Wherever Issue

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global#848]
Ao trocar de ring/amulet 
se a backpack de um deles estiver cheia, não faz a troca.
(Não está sendo possível, pois o ring não esta indo para bp principal).

![image](https://user-images.githubusercontent.com/52710697/74583651-e9de1580-4fa7-11ea-88ad-9a517f0da857.png)

edit: RESOLVIDO :
Na Action bar, os aneis, estão contando +1, por exemplo.
Você tem 26 rings, e irá mostrar 27.

**Comment by mattyx14** [comment]
reproduce for my it

**Comment by Lycanzito** [comment]
> reproduce for my it

Right here :- )

https://www.youtube.com/watch?v=c3O2AsI-CR0

**Comment by Lycanzito** [comment]
> reproduce for my it

Want me to make any other test ?

**Comment by Lycanzito** [comment]
Editei o comentário principal, foi resolvido 1 parte da issue, com sucesso ! =)

obrigado !

**Comment by heberholanda** [comment]
![hotkey](https://user-images.githubusercontent.com/715547/96212935-38381f80-0f4e-11eb-9070-98df4a5c9e51.gif)
