### ISSUE TITLE
Question about limitation Market: ( issue ? )

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global#865]
It's possible to make questions, here right? xD

about this commit > commit/b17a428a866b26db5e9ed1c695396d80041e643e

For what reason, there is a limitation, of buying/selling itens on market?
For example: the max amount that is possible to sell each time, is 3000
![image](https://user-images.githubusercontent.com/52710697/74952611-447bd500-53df-11ea-871b-b57570a4d8e0.png)
( nopossible)

now is possible with 3k :
![image](https://user-images.githubusercontent.com/52710697/74952670-578ea500-53df-11ea-9538-79bcab6b0b2b.png)

also.. it's only possible to buy 500 each time.
![image](https://user-images.githubusercontent.com/52710697/74952792-86a51680-53df-11ea-9c85-d58522b5ec9c.png)

There is any reason for it?

**Comment by dudantas** [comment]
There was a bug where when placing many items on the market, when someone bought the very high offer (example 20000 items) when sending to the depot it crashes the distro. I don't know how it is now, it needs to be revised.

**Comment by Lycanzito** [comment]
> There was a bug where when placing many items on the market, when someone bought the very high offer (example 20000 items) when sending to the depot it crashes the distro. I don't know how it is now, it needs to be revised.

hm...
ok ^.- 
thanks 4 the info! : D

**Comment by dudantas** [comment]
https://github.com/opentibiabr/otservbr-global/commit/8964b1b722d4b17cfc902692caadd5066dd441a3

Vou fazer alguns testes e ver se crasha, se não crashar a gente já resolve esse issue.
