### ISSUE TITLE
Some quest doors not checking storage

### ISSUE THREAD

**Issue by VitorNM** [opentibiabr/otservbr-global#880]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Some quest doors, that you need to have a storage to pass, are not checking the storage and all players can pass trough it

**Screenshots**
![image](https://user-images.githubusercontent.com/29928255/75249691-7f9e4f80-57b5-11ea-9e31-69482a0c9268.png)

![image](https://user-images.githubusercontent.com/29928255/75249728-92188900-57b5-11ea-9aa8-8022b1eb9ea9.png)

**Additional context**
This character doesn't have the storage of the quest "The Thieves Guild Quest" and can enter in the prize room.

**Comment by dudantas** [comment]
Thanks for the report @VitorNM, solved.
