### ISSUE TITLE
 latest open backpack system

### ISSUE THREAD

**Issue by robertof157** [opentibiabr/otservbr-global#881]
**Is your feature request related to a problem? Please describe.**

## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Links**
If applicable, add links to help explain how this feature works.

**Additional context**

**Comment by Chapeleiiro** [comment]
latest open backpack system
