### ISSUE TITLE
Store ( Exp Boost ) 

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global#891]
Is possible to stack (time )  buying  experience boost.

![image](https://user-images.githubusercontent.com/52710697/75480013-43b6e600-597f-11ea-969e-c5d120d2318f.png)

How it should be: When You try to buy a exp boost, when u already have one actived:
 it should appears like this : 
![image](https://user-images.githubusercontent.com/52710697/75480103-6fd26700-597f-11ea-98b3-2d58354adb2d.png)

**Comment by FakeShinoda** [comment]
Do it by yourself [5]
