### ISSUE TITLE
lever bosses - Set/get exhaustion correction (#872) 

### ISSUE THREAD

**Issue by milkersky** [opentibiabr/otservbr-global#897]
After this update all lever bosses doesnt work. You can enter to boss room many times without cooldown. When you dont kill boss just enter to exit tp and after that you enter to boss room again there will be 2 bosses.

> Lua Script Error: [Action Interface]
> data/actions/scripts/farmine/Oberonlever.lua:onUse
> data/actions/scripts/farmine/Oberonlever.lua:64: attempt to call method 'setStorage' (a nil value)
> stack traceback:
>         [C]: in function 'setStorage'
>         data/actions/scripts/farmine/Oberonlever.lua:64: in function <data/actions/scripts/farmine/Oberonlever.lua:33>

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/75941182-c7843d00-5e6d-11ea-96a5-846ef46188e7.png)

Fixed
