### ISSUE TITLE
Falcon Shield upgrade 

### ISSUE THREAD

**Issue by VictorWalking** [opentibiabr/otservbr-global#906]
No upgrade do Falcon Shield o item "Grant of arms" não deve ser removido do player. 

Linha 14: 
https://github.com/opentibiabr/otservbr-global/blob/develop/data/actions/scripts/falcons/falcon_shield.lua

Enhancement: 
Adicionar os efeitos do 'anvil' e na máquina ao lado quando o shield for usado.
(CONST_ME_HITAREA) (CONST_ME_POFF) no anvil e a "fumacinha" na máquina ao lado.

Vídeos base:
https://youtu.be/3BmRvpYNRzA?t=82
https://youtu.be/qD963Wu8qKk?t=220

**Comment by rtsrick2017** [comment]
```
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if not target or type(target) ~= 'userdata' or not target:isItem() then
		return false
	end

	if player:getItemCount(32521) < 1 or player:getItemCount(32518) < 1 then
		return false
	end

	if target:getId() ~= 8671 or target:getPosition() ~= Position(33363, 31342, 7) then
		return false
	end

	local mould = Position(33361, 31341, 7)

	toPosition:sendMagicEffect(CONST_ME_POFF)
	toPosition:sendMagicEffect(CONST_ME_HITAREA)
	mould:sendMagicEffect(CONST_ME_SMOKE)
	player:removeItem(32521, 1)
	player:removeItem(32518, 1)
	player:addItem(32422, 1)
	item:remove(1)
	return true
end
```

**Comment by Sargitarium** [comment]
Test and work fine.... thx for contribution

**Comment by VictorWalking** [comment]
> Test and work fine.... thx for contribution

The "grant of arms" still being remove?
Did you tested?

**Comment by Sargitarium** [comment]
> > Test and work fine.... thx for contribution
> 
> The "grant of arms" still being remove?
> Did you tested?

Shield removed, grant of arms removed, patch of fine cloth removed....

**Comment by VictorWalking** [comment]
Grant of arms is not to be removed.

https://youtu.be/3BmRvpYNRzA?t=82
https://youtu.be/qD963Wu8qKk?t=220

**Comment by Sargitarium** [comment]
Before use...
![falcon_1](https://user-images.githubusercontent.com/42014600/77235260-0cf57980-6b93-11ea-9caf-192b80c13e1a.png)

After use...
![falcon_2](https://user-images.githubusercontent.com/42014600/77235300-56de5f80-6b93-11ea-8f11-7802c46da7ae.png)

-- I'm teste it 20x... all work fine

**Comment by VictorWalking** [comment]
> Before use...
> ![falcon_1](https://user-images.githubusercontent.com/42014600/77235260-0cf57980-6b93-11ea-9caf-192b80c13e1a.png)
> 
> After use...
> ![falcon_2](https://user-images.githubusercontent.com/42014600/77235300-56de5f80-6b93-11ea-8f11-7802c46da7ae.png)
> 
> -- I'm teste it 20x... all work fine

In Tibia Global, only patch of fine cloth and falcon sheild are removed.
Script needs to be fix yet.

**Comment by rtsrick2017** [comment]
@VictorWalking

```
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if not target or type(target) ~= 'userdata' or not target:isItem() then
		return false
	end

	if player:getItemCount(32521) < 1 or player:getItemCount(32518) < 1 then
		return false
	end

	if target:getId() ~= 8671 or target:getPosition() ~= Position(33363, 31342, 7) then
		return false
	end

	local mould = Position(33361, 31341, 7)

	toPosition:sendMagicEffect(CONST_ME_POFF)
	toPosition:sendMagicEffect(CONST_ME_HITAREA)
	mould:sendMagicEffect(CONST_ME_SMOKE)
	player:removeItem(32518, 1)
	player:addItem(32422, 1)
	item:remove(1)
	return true
end
```
