### ISSUE TITLE
svargrond arena door

### ISSUE THREAD

**Issue by Methemia** [opentibiabr/otservbr-global#913]
23:58 You see a closed door.
Item ID: 5132, Action ID: 26101
Position: 32227, 31066, 7 
when you try to open it, it throws you back

also the wote door (reward) does not work

**Comment by rtsrick2017** [comment]
Problably because the correct actionid should be 26100, instead of 26101, since it's set that way on lib/tables/storages

`-- Actions Reward Doors
		Greenhorn = 26100,
		Scrapper = 27100,
		Warlord = 28100`

Tested over here with the correct aid and it worked just fine.

**Comment by dudantas** [comment]
@Methemia test this opentibiabr/otservbr-global#983
