### ISSUE TITLE
missin attribute in werewolf helmet items.xml

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global#952]
<item id="24718" article="a" name="werewolf helmet">
		<attribute key="weight" value="2500" />
		<attribute key="armor" value="9" />

upgrade to:

	<item id="24718" article="a" name="werewolf helmet">
		<attribute key="weight" value="2500" />
		<attribute key="slotType" value="head" />		
		<attribute key="armor" value="9" />

**Comment by runRoots** [comment]
olha só mais um detalhe , pelo item editor quando fui ver  esse helmet esta marcado a opção multiuse ,  por conta disso não tem como usar , então sugiro remover tambem essa opçao pelo item editor
