### ISSUE TITLE
Reward System

### ISSUE THREAD

**Issue by marcomoa** [opentibiabr/OTServBR-Global#96]
Deve conter uma função de unique="1" aonde somente um item daquele pode dropar para não entregar o item a todos jogadores.

Mensagem de loot do reward system tem que aparecer em verde e não em branco igual loot normal

Ordem do reward tem que ser de cima para baixo e não o contrário.

countmin não funciona

O jogador pode criar varias contas, bater no boss morrer e não logar, ganhara loot

**Comment by LucasCPrazeres** [comment]
1. vc pode setar o valor do unique na hr do droploot, colocando um bool para checar se foi ou não dado o item
2. Isso é só mudar o valor da variável do sendTextMessage
3, no mesmo arquivo de gerar o loot, da para colocar o countmin
4. na hora de montar a tabela do dano no boss, é só substituir o getGuid para getId

**Comment by eduardodantas95** [comment]
@LucasCPrazeres se puder estar subindo este pull request, seria de grande ajuda.

**Comment by LucasCPrazeres** [comment]
@eduardodantas95  certo
