### ISSUE TITLE
monsters with hidehealth is not hidding health

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global#962]
hidehealth tag is not workingn properly, it is showing creature's hp bar in black to all players (usually only gms+ can see that)

It is supposed to hide both the creature hp bar and name, but instead it should everything and the hp bar is black

currently:

![image](https://user-images.githubusercontent.com/36482994/78072785-11314c00-7376-11ea-824c-14c60ebe4884.png)

how it's supposed to show:

![image](https://user-images.githubusercontent.com/36482994/78072810-1b534a80-7376-11ea-9b81-756ef511fbda.png)

**Comment by jlcvp** [comment]
Talvez seja o caso de não mandar at all o byte 0x8c ao invés de mandar 0

**Comment by jlcvp** [comment]
Consegui mandando no `ProtocolGame::AddCreature`
`creatureType = 5`

precisa investigar a partir de qual protocol essa flag pode ser ativada, testei no client 12.31
<img width="1130" alt="Screen Shot 2020-04-17 at 10 13 13" src="https://user-images.githubusercontent.com/2317417/79573049-64084480-8094-11ea-86f9-fda977b59ae0.png">

**Comment by gpedro** [comment]
related Johncorex/OTG-Premium-Version#23

**Comment by gpedro** [comment]
@jlcvp acredito que tenha sido 12x, por que até no Flash Client o atual funciona...

**Comment by jlcvp** [comment]
O elton testou a versão 11.40 e rolou. Eu vou assumir 11.20 que foi quando teve mais mudanças
