### ISSUE TITLE
walkback.lua - does not reset player's height

### ISSUE THREAD

**Issue by guiismiti** [opentibiabr/otservbr-global#998]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Walkback from walkback.lua does not reset the player's height - after walking back, the player still looks like he is stepping on a chest.

**To Reproduce**
1. Go to Position(32225, 31910, 15)
2. Step on the quest chest
3. See error
Note: walkback.lua:
If you replace
"creature:teleportTo(fromPosition, false)"
with
"player:teleportTo(fromPosition, true)"
it should solve the issue (but I'm not sure if there would be new issues - at least I haven't had any).

**Expected behavior**
The player should not look like he has an invisible chest under him after walking back.

**Screenshots**
How it is:
![as-is](https://user-images.githubusercontent.com/7709510/78611088-8dc39f00-783c-11ea-8594-45c9f618fb4c.png)

How it should be:
![to-be](https://user-images.githubusercontent.com/7709510/78611094-90be8f80-783c-11ea-8864-d7c841363cb8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
-

**Comment by biaggio12** [comment]
why would you even do that when player can't walk on quest chests ?
